koordinator-sh/koordinator

apis/extension/qos.go
pkg/slo-controller/config/constants.go
pkg/slo-controller/noderesource/configmap_event_handler.go

add LSE (latency sensitive exclusive)

✨ Introduce LSE into QoS Class

---

Makefile
cmd/koord-webhook/main.go
go.sum
pkg/client/clientset/versioned/typed/config/v1alpha1/fake/fake_clustercolocationprofile.go
pkg/client/clientset/versioned/typed/slo/v1alpha1/fake/fake_nodemetric.go
pkg/features/features.go
pkg/util/json.go
pkg/util/resource.go
pkg/util/selector.go
pkg/webhook/add_pod.go
pkg/webhook/pod/mutating/cluster_colocation_profile.go
pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
pkg/webhook/pod/mutating/mutating_handler.go
pkg/webhook/pod/mutating/webhooks.go
pkg/webhook/pod/validating/cluster_colocation_profile.go
pkg/webhook/pod/validating/cluster_colocation_profile_test.go
pkg/webhook/pod/validating/request_limit_validator.go
pkg/webhook/pod/validating/validating_handler.go
pkg/webhook/pod/validating/webhooks.go
scripts/generate_client.sh
vendor/k8s.io/apimachinery/pkg/api/validation/doc.go
vendor/k8s.io/apimachinery/pkg/api/validation/generic.go
vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go

- Add Pod mutating webhook handler that mutate target Pod satisfied ClusterColocationProfile
- Add Pod validating webhook handler that validate colocation constraints defined by Koordinator

add Pod Mutating/Validating webhook handler

---

apis/config/v1alpha1/cluster_colocation_profile_types.go
apis/config/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
pkg/slo-controller/noderesource/resource_calculator.go
pkg/util/pod.go
pkg/webhook/pod/mutating/cluster_colocation_profile.go
pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
pkg/webhook/pod/validating/cluster_colocation_profile.go
pkg/webhook/pod/validating/cluster_colocation_profile_test.go

Support config QoSClass/PriorityClass/ColocationPriority in Profile.
And webhook mutating Pod inject QoSClass etc, validating Pod without QosClass and so on.

support config QoSClass/PriorityClass/ColocationPriority in Profile

---

pkg/slo-controller/config/config.go
pkg/util/utils.go

remove duplicate function like Int64Ptr

---

Makefile
cmd/koord-manager/main.go
go.mod
pkg/koordlet/koordlet.go
pkg/koordlet/reporter/reporter_test.go
pkg/koordlet/util/node.go
pkg/koordlet/util/pod.go
pkg/slo-controller/config/config.go
pkg/slo-controller/config/constants.go
pkg/slo-controller/nodemetric/node_event_handler.go
pkg/slo-controller/noderesource/configmap_event_handler.go
pkg/slo-controller/noderesource/noderesource.go
pkg/slo-controller/noderesource/noderesource_controller.go
pkg/slo-controller/nodeslo/nodeslo_controller.go
pkg/slo-controller/nodeslo/nodeslo_controller_test.go
pkg/slo-controller/nodeslo/resource_strategy.go
pkg/slo-controller/nodeslo/resource_strategy_test.go

Add nodeslo controller

---

apis/config/v1alpha1/cluster_colocation_profile_types.go
config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml

fix typo in ClusterColocationProfile

🐛 Fix typo in ClusterColocationProfile

---

pkg/webhook/pod/mutating/cluster_colocation_profile.go
pkg/webhook/pod/mutating/cluster_colocation_profile_test.go

align the units of koordinator.sh/batch-cpu

---

apis/config/v1alpha1/cluster_colocation_profile_types.go
apis/extension/priority.go
config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
pkg/webhook/pod/validating/cluster_colocation_profile.go
pkg/webhook/pod/validating/cluster_colocation_profile_test.go

rename koordinator priority class name

---

README.md

add quick start link to website

---

apis/extension/priority.go
pkg/webhook/pod/validating/cluster_colocation_profile_test.go

change batch priority value range

---

README.md

add best practices in Quick Start section

---

Dockerfile

use default image user, so that koordlet has the permission to modify cgroup file.

use default image user

---

examples/spark-jobs/cluster-colocation-profile.yaml
examples/spark-jobs/service-account.yaml

Signed-off-by: zwzhang0107 <zuoweizhang@outlook.com>

update cluster colocation profile

---

.github/workflows/ci.yaml
.github/workflows/license.yml
CONTRIBUTING.md
README.md
docs/proposals/YYYYMMDD-template.md

Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Add contributing docs

Add contributing docs

---

Makefile
config/default/kustomization.yaml
config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_service.yaml
config/rbac/role.yaml
config/webhook/kustomization.yaml
config/webhook/kustomizeconfig.yaml
config/webhook/manifests.yaml
config/webhook/patch_manifests.yaml
config/webhook/service.yaml
pkg/webhook/add_pod.go
pkg/webhook/pod/mutating/cluster_colocation_profile.go
pkg/webhook/pod/validating/cluster_colocation_profile.go
pkg/webhook/pod/validating/cluster_colocation_profile_test.go
pkg/webhook/pod/validating/request_limit_validator.go
pkg/webhook/pod/validating/webhooks.go

fix webhook validating

---

.license/README.md
.license/dependency_decisions.yml

Config dependency licenses

---

.github/workflows/ci.yaml

update to latest version and skip cache to avoid errors.

🐛 Fix golangci-lint error

---

README.md

📖 Add Slack invite URL in README

---

pkg/koordlet/koordlet.go
pkg/koordlet/metricsadvisor/collector.go

Signed-off-by: mr-linus <mrfunky001@gmail.com>

add some error handlers

---

examples/nginx/nginx.yaml

🐛 Fix image tag typo

---

.github/workflows/ci.yaml
pkg/runtime/handler/containerd_runtime.go

🌱 Add staticcheck ci action

---

.github/workflows/ci.yaml
pkg/koordlet/statesinformer/states_informer_test.go

CI will fail due to data race, details meintioned in #77 . Ignore `Test_metaService_syncPods` temporarily to let the CI work.

⚠️ ignore Test_metaService_syncPods temporarily

---

.github/ISSUE_TEMPLATE/membership.yml
.github/workflows/ci.yaml
CONTRIBUTING.md
README.md
docs/community/community-membership.md

📖 Add membership doc & issue template

---

pkg/slo-controller/nodeslo/resource_strategy_test.go
pkg/util/config.go
pkg/util/utils_test.go

🐛 fix nodeslo syncing issue

---

CHANGELOG.md
CONTRIBUTING.md
README.md

📖 fix typo in docs

---

pkg/koordlet/resmanager/memory_evict.go
pkg/koordlet/resmanager/memory_evict_test.go
pkg/runtime/handler/fake_runtime.go
pkg/util/container.go
vendor/k8s.io/cri-api/pkg/apis/testing/fake_image_service.go
vendor/k8s.io/cri-api/pkg/apis/testing/fake_runtime_service.go
vendor/k8s.io/cri-api/pkg/apis/testing/utils.go
vendor/modules.txt

add ut for memory evict feature

🌱 add unit test for memory evict feature

---

pkg/koordlet/resmanager/resmanager.go

Signed-off-by: cheimu yimo@xiaohongshu.com
https://github.com/koordinator-sh/koordinator/pull/94#issuecomment-1120709905

Activate rdt res_ctrl in resmanager

---

pkg/util/container.go

Fix one small bug when glancing the code :)

fix(koordlet): fix be container memory request

---

pkg/slo-controller/config/config.go
pkg/slo-controller/noderesource/resource_calculator_test.go

add unit test for `resrouce_calculator.go` to increase code coverage

test(controller): add unit test for resource_calculator

---

pkg/slo-controller/config/config_test.go

increase code coverage of `pkg/slo-controller/config/config.go`

test(controller): add unit test for `config/config.go`

---

pkg/slo-controller/noderesource/noderesource.go
pkg/slo-controller/noderesource/noderesource_test.go

add unit test for `pkg/slo-controller/noderesource/noderesource.go` to increase code coverage

test(controller): add unit test for noderesource

---

.github/workflows/license.yml
pkg/koordlet/metricsadvisor/be_collector.go
pkg/koordlet/metricsadvisor/be_collector_test.go

style: format header to fix ci errors

---

pkg/scheduler/apis/config/doc.go
pkg/scheduler/apis/config/v1beta2/doc.go

koord-scheduler: update scheduler apis groupName

---

pkg/slo-controller/noderesource/configmap_event_handler_test.go

add unit test for `pkg/slo-controller/noderesource/configmap_event_handler.go`

test: add ut for configmap_event_handler

---

pkg/koordlet/resmanager/resmanager.go

fix: add CPU Evict check in isFeatureDisabled

---

.github/dependabot.yml

For further information, please check https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

chore: introduce dependabot

---

cmd/koord-manager/main.go
pkg/slo-controller/nodemetric/node_event_handler_test.go
pkg/slo-controller/noderesource/nodemetric_event_handler_test.go
pkg/slo-controller/noderesource/noderesource.go
pkg/slo-controller/noderesource/noderesource_controller.go
pkg/slo-controller/noderesource/noderesource_controller_test.go
pkg/slo-controller/noderesource/noderesource_test.go
pkg/webhook/pod/mutating/mutating_handler_test.go
pkg/webhook/pod/validating/validating_handler_test.go

add more tests

---

.github/workflows/ci.yaml

According to https://github.com/golangci/golangci-lint-action#performance, this action has already included a caching step. Additional caching would result some errors occasionally.

chore: remove additional cache in golangci-lint

---

CHANGELOG.md

add ChangeLog for v0.4.0

---

CONTRIBUTING.md
docs/contributors/first-pr.md
docs/contributors/good-pr.md

This PR introduce the proper workflow of creating a pull request in Koordinator Organization.
Let's go through this document in the upcoming weekly meeting before merging it.

docs: what is a good pull request

---

pkg/runtimeproxy/config/config.go
pkg/runtimeproxy/dispatcher/dispatcher.go
pkg/runtimeproxy/resexecutor/cri/container.go
pkg/runtimeproxy/resexecutor/cri/container_test.go
pkg/runtimeproxy/resexecutor/cri/pod.go
pkg/runtimeproxy/resexecutor/cri/pod_test.go
pkg/runtimeproxy/resexecutor/cri/utils.go
pkg/runtimeproxy/resexecutor/cri/utils_test.go
pkg/runtimeproxy/resexecutor/resource_executor.go
pkg/runtimeproxy/resexecutor/resource_executor_test.go
pkg/runtimeproxy/server/cri/criserver.go
pkg/runtimeproxy/server/docker/handler.go
pkg/runtimeproxy/store/manager.go

Signed-off-by: yimo <yimo@xiaohongshu.com>
implement cri version new runtime api
This pr implements cri scenario PreCreateContainerHook and PostStopPodSnadboxHook hook client behavior
#218

Implement cri scenario PreCreateContainerHook and PostStopPodSandboxHook

---

docs/contributors/logging.md

Knowing how and what to log is, to me, one of the hardest tasks a software engineer will have to do. Mostly because this task is akin to divination. It’s very hard to know what information you’ll need during troubleshooting. A good logging guide will help enhance our application logging for the great benefits of SREs.
fix #211
Let's go through this document in the upcoming weekly meeting before merging it.

docs: propose a logging convention

---

OWNERS
pkg/koordlet/OWNERS
pkg/runtimeproxy/OWNERS
pkg/scheduler/OWNERS
pkg/slo-controller/OWNERS
pkg/webhook/OWNERS

The quality of a person's code review is limited by their familiarity with the code under review. 
I update OWNERS file in each module, so koordinator-bot would know which reviewer should be assigned in the further PR.

chore: update OWNERS in each module

---

.github/workflows/ci.yaml

GitHub Action to build and push Docker images when a PR is merged into `main`.

ci: build & push docker when PR is merged into main

---

.github/workflows/ci.yaml
Dockerfile

ci: fix docker build context

---

apis/extension/constants.go
apis/extension/node.go
apis/extension/resource.go
apis/extension/scheduling.go

defines CPU orchestration APIs

---

docs/design-archive/koord-runtime-proxy-design-doc.md

fixed issue https://github.com/koordinator-sh/koordinator/issues/273

fixed setup kubelet docs, which caused kubelet startup exception

---

.github/workflows/release.yml
.gitignore
.goreleaser.yaml
.goreleaser/Dockerfile
Makefile

https://goreleaser.com/ is introduced to continuous deployment koord-runtime-proxy.

chore: add goreleaser

---

pkg/runtimeproxy/server/docker/handler_test.go
pkg/runtimeproxy/server/docker/server.go
pkg/runtimeproxy/server/docker/server_test.go

add more tests for docker-proxy

---

go.mod
go.sum

feat(deps): bump k8s.io/klog/v2 from 2.9.0 to 2.10.0

---

cmd/koord-scheduler/app/config/config.go
cmd/koord-scheduler/app/options/options.go
cmd/koord-scheduler/app/server.go
go.mod
go.sum
pkg/scheduler/frameworkext/framework_extender.go
pkg/scheduler/plugins/loadaware/load_aware_test.go

koord-scheduler: refactor framework extender init function

---

codecov.yml

ci: ignore generated files when calculating coverage

---

pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
pkg/koordlet/runtimehooks/hooks/hooks.go
pkg/koordlet/runtimehooks/protocol/container_context.go
pkg/koordlet/runtimehooks/protocol/pod_context.go
pkg/koordlet/runtimehooks/protocol/protocol.go
pkg/koordlet/runtimehooks/reconciler/reconciler.go
pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
pkg/koordlet/runtimehooks/rule/inject.go
pkg/koordlet/runtimehooks/rule/rule.go
pkg/koordlet/runtimehooks/runtimehooks.go
pkg/koordlet/runtimehooks/runtimehooks_test.go
pkg/koordlet/statesinformer/mockstatesinformer/mock.go
pkg/koordlet/statesinformer/register.go
pkg/koordlet/statesinformer/register_test.go
pkg/koordlet/statesinformer/states_informer.go
pkg/koordlet/statesinformer/states_nodeslo.go
pkg/koordlet/statesinformer/states_pod.go

add reconciler for runtime hook standalone work mode

---

docs/proposals/scheduling/20220701-pod-migration-job.md

This proposal defines a CRD-based Pod migration API, through which the descheduler or other automatic fault recovery components can evict or delete Pods more safely. At the same time, the proposal also describes the specific implementation details of the API.
#357

add PodMigrationJob CRD proposal 

---

docs/proposals/scheduling/20220701-schedule-gang.md

add proposal for gang scheduling

---

apis/extension/node.go
apis/scheduling/config/types.go
apis/scheduling/config/v1beta2/defaults.go
apis/scheduling/config/v1beta2/types.go
apis/scheduling/config/v1beta2/zz_generated.conversion.go
docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
pkg/scheduler/plugins/nodenumaresource/cpu_allocator.go
pkg/scheduler/plugins/nodenumaresource/plugin.go
pkg/scheduler/plugins/nodenumaresource/plugin_test.go

Support node cpu orchestration api

---

pkg/util/resource_test.go
pkg/util/system/cgroup_test.go
pkg/util/utils_test.go

chore: supply UT for pkg/util and pkg/util/system

---

hack/run-test.sh
pkg/koordlet/audit/auditor_test.go

curl http://:%d seems to fail on MacOS, set it to http://127.0.0.1:%d
http://localhost:%d will panic in go test -race which is hard to explain.

fix auditor test in MacOS

---

README-zh_CN.md
README.md

docs: add chinese version readme.md

---

pkg/koordlet/resmanager/cpu_suppress.go
pkg/koordlet/resmanager/cpu_suppress_test.go

fix: consider lse/lsr when cpu suppress (#234)

---

apis/extension/resource.go
apis/scheduling/v1alpha1/device_types.go
apis/scheduling/v1alpha1/zz_generated.deepcopy.go
apis/slo/v1alpha1/nodemetric_types.go
apis/slo/v1alpha1/resources.go
apis/slo/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/scheduling.koordinator.sh_devices.yaml
config/crd/bases/slo.koordinator.sh_nodemetrics.yaml

api: add device info into NodeMetric CRD

---

go.mod
go.sum
pkg/koordlet/metriccache/api.go
pkg/koordlet/metriccache/metric_cache.go
pkg/koordlet/metriccache/metric_cache_test.go
pkg/koordlet/metriccache/storage_tables.go
pkg/koordlet/metricsadvisor/collector.go
pkg/koordlet/metricsadvisor/collector_gpu.go
pkg/koordlet/metricsadvisor/collector_gpu_test.go
pkg/util/container.go
pkg/util/container_test.go
pkg/util/system/cgroup_resource.go

Signed-off-by: 黄金 <huangjin_henan@outlook.com>
fixes #323

koordlet: support collecting GPU metrics from node/pod/container

---

pkg/koordlet/resmanager/resmanager.go
pkg/util/feature.go

cleanup for koordlet/resmanager

chore: cleanup resmanager

---

pkg/koordlet/koordlet.go

Signed-off-by: Cheimu <xerhoneyfc@gmail.com>
Turn on pleg.

koordlet: Turn on pleg

---

pkg/features/koordlet_features.go
pkg/koordlet/metricsadvisor/collector.go
pkg/koordlet/metricsadvisor/collector_gpu.go

koordlet: introduce `Accelerators` feature gate for GPU related features

---

cmd/koord-manager/main.go
pkg/slo-controller/config/config.go
pkg/slo-controller/config/config_test.go
pkg/slo-controller/config/constants.go

make slo configmap name configurable

---

pkg/runtimeproxy/server/cri/criserver.go

Signed-off-by: Xiang Liu <lx1036@126.com>

[cherry-pick] fix criserver return typo

---

apis/extension/qos.go
pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go

change qos func name for old format adaption reason

---

ADOPTERS.md

docs: add ADOPTERS.md of Koordinator

---

go.mod
pkg/descheduler/apis/config/v1alpha2/default_plugins.go
pkg/descheduler/controllers/options/manager.go
pkg/descheduler/controllers/registry.go
pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/framework/plugins/defaultevictor/evictor.go
pkg/descheduler/framework/plugins/registry.go
pkg/descheduler/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
pkg/descheduler/framework/runtime/framework.go
pkg/descheduler/framework/runtime/registry.go
pkg/descheduler/framework/types.go
pkg/descheduler/informers/factory.go
pkg/descheduler/informers/generic.go
pkg/descheduler/metrics/metrics.go
pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/descheduler/profile/profile.go
pkg/descheduler/test/test_utils.go
pkg/descheduler/utils/pod.go
pkg/descheduler/utils/pod_test.go
pkg/descheduler/utils/predicates.go
pkg/descheduler/utils/predicates_test.go
pkg/descheduler/utils/priority.go
pkg/descheduler/utils/priority_test.go

koord-descheduler: implement descheduling framework

---

ADOPTERS.md

Signed-off-by: Cheimu <xerhoneyfc@gmail.com>
add xiaohongshu as koordinator adopter

[adopter] add xiaohongshu as koordinator adopter

---

pkg/descheduler/OWNERS
pkg/descheduler/apis/config/v1alpha2/default_plugins.go

fix koord-descheduler initialize profile error

---

apis/extension/node.go
docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
pkg/koordlet/statesinformer/states_noderesourcetopology.go
pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
pkg/scheduler/plugins/nodenumaresource/node_numa_info_test.go
pkg/scheduler/plugins/nodenumaresource/plugin.go

koord-scheduler: compatible with Pods using kubelet static CPU manager policy

---

ADOPTERS.md

docs: add maturity level in adopters.md

---

pkg/runtimeproxy/server/cri/criserver.go

bugfix: skip when pod sandbox not found

---

docs/proposals/scheduling/20220722-multi-hierarchy-elastic-quota-management.md

adjusted the description of elastic quota

---

apis/extension/resource.go
apis/extension/resource_test.go
pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
pkg/scheduler/plugins/nodenumaresource/plugin.go

Abstract cpuset scheduling protocols and give koordinator the ability to adapt to different cpuset scheduling protocols.

koord-scheduler: adapt to different cpuset scheduling protocols

---

pkg/descheduler/apis/config/types_pluginargs.go
pkg/descheduler/apis/config/v1alpha2/defaults.go
pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
pkg/descheduler/apis/config/validation/validation.go
pkg/descheduler/apis/config/validation/validation_pluginargs.go
pkg/descheduler/apis/config/validation/validation_pluginargs_test.go
pkg/descheduler/apis/config/validation/validation_test.go
pkg/descheduler/apis/config/zz_generated.deepcopy.go
pkg/descheduler/controllers/migration/controller.go
pkg/descheduler/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go

koord-descheduler: complete configuration

---

ADOPTERS.md

Signed-off-by: Wang Xiaoqiang <wangxiaoqiang@qiyi.com>
Add iQIYI adopter
NONE

ADOPTERS: add iQIYI

---

pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
pkg/scheduler/plugins/nodenumaresource/plugin.go
pkg/scheduler/plugins/nodenumaresource/plugin_test.go

This PR exports NodeNumaInfoCache and GetAvailableCPUs in NodeNUMAResource plugin for compatibility with internal protocols and implementations

koord-scheduler: export NodeNUMAInfoCache and getAvailableCPUs

---

pkg/scheduler/plugins/nodenumaresource/plugin.go

This PR abstract GetPodQoSClass in NodeNUMAResource plugin for compatibility with internal protocols and implementations

koord-scheduler: abstract GetPodQoSClass

---

docs/proposals/api-machinery/20220707-rename-extended-resource.md
pkg/koordlet/metricsadvisor/be_collector_test.go
pkg/koordlet/resmanager/be_reconcile_test.go
pkg/koordlet/resmanager/cpu_evict_test.go
pkg/scheduler/plugins/loadaware/load_aware.go
pkg/scheduler/plugins/loadaware/load_aware_test.go
pkg/slo-controller/noderesource/noderesource.go
pkg/slo-controller/noderesource/noderesource_controller_test.go
pkg/slo-controller/noderesource/noderesource_test.go
pkg/slo-controller/noderesource/resource_calculator.go
pkg/slo-controller/noderesource/resource_calculator_test.go
pkg/util/container.go
pkg/util/pod_test.go
pkg/webhook/pod/mutating/cluster_colocation_profile.go
pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
pkg/webhook/pod/validating/cluster_colocation_profile.go
pkg/webhook/pod/validating/cluster_colocation_profile_test.go

set kubernetes.io/batch-cpu as milli-core

---

pkg/descheduler/framework/runtime/framework.go

Other plugins may depend on the evictor plugin, so we should initialize the evictor plugin first.

koord-descheduler: init evictor plugin first

---

.golangci.yml
go.mod
pkg/runtimeproxy/server/docker/handler_test.go
pkg/runtimeproxy/server/docker/server.go
pkg/util/httputil/reverseproxy.go
pkg/util/httputil/reverseproxy_test.go

bugfix: fix exec exit with 126

---

pkg/scheduler/plugins/batchresource/batch_resource.go

koord-scheduler: fix typo

---

pkg/descheduler/framework/runtime/framework.go
pkg/descheduler/framework/runtime/framework_test.go
pkg/descheduler/framework/runtime/registry.go
pkg/descheduler/framework/runtime/registry_test.go

koord-descheduler: add tests for framework runtime

---

docs/proposals/api-machinery/20220707-rename-extended-resource.md

docs: format markdown

---

.github/workflows/codeql.yml

ci: add codeql in pipeline workflows

---

pkg/slo-controller/noderesource/noderesource.go
pkg/slo-controller/noderesource/noderesource_test.go

refactor batch node resource update

---

pkg/koordlet/resmanager/be_reconcile.go
pkg/koordlet/resmanager/cgroup_reconcile.go
pkg/koordlet/resmanager/cpu_evict.go
pkg/util/container.go
pkg/util/container_ext_resource.go
pkg/util/container_test.go
pkg/util/pod.go

mv container extend resource to independent file

---

pkg/koordlet/metriccache/config.go

Signed-off-by: huiwq1990 <huiwq1990@163.com>

fix metric-expire-seconds usage

---

ADOPTERS.md

Signed-off-by: zhushaohua <zshmmm@163.com>
Add adopter.
No
No need
No

adopters: add Quwan

---

pkg/koordlet/metriccache/metric_cache.go
pkg/koordlet/metriccache/storage.go
pkg/koordlet/metriccache/storage_test.go

fix: correct misspells in pkg/koordlet/metriccache

---

apis/extension/resource.go
apis/extension/scheduling.go

apis: add DeviceAllocations and methods

---

pkg/descheduler/apis/config/types_pluginargs.go
pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
pkg/descheduler/apis/config/validation/validation_pluginargs.go
pkg/descheduler/apis/config/validation/validation_pluginargs_test.go
pkg/descheduler/controllers/migration/controller.go
pkg/descheduler/controllers/migration/evictor/interpreter.go

Controls the execution speed of Evict to prevent excessive eviction from affecting availability.

koord-descheduler: support evict flow control to ensure availability

---

apis/extension/scheduling.go
pkg/koordlet/runtimehooks/config.go
pkg/koordlet/runtimehooks/hooks/gpu/gpu.go
pkg/koordlet/runtimehooks/hooks/gpu/gpu_test.go
pkg/koordlet/runtimehooks/protocol/container_context.go

feature: support inject NVIDIA_VISIBLE_DEVICES env

---

apis/extension/pod.go
pkg/koordlet/resmanager/cgroup_reconcile.go
pkg/koordlet/resmanager/configextensions/pod_qos_control.go
pkg/koordlet/resmanager/cpu_burst.go
pkg/koordlet/resmanager/pod_qos_control_test.go
pkg/koordlet/resmanager/resmanager.go

qos grep control extension

---

docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md

docs: update fine grained device proposal

---

Makefile

chore: update tools version

---

ADOPTERS.md

docs: reformat adopters list

---

.github/workflows/ci.yaml

ci: support aliyun hangzhou registry

---

.goreleaser/koordlet.dockerfile
docker/koordlet.dockerfile

chore: downgrade CUDA version to 11.2.2

---

pkg/scheduler/frameworkext/framework_extender.go

koord-scheduler: support custom SharedLister

---

pkg/descheduler/controllers/migration/controller_test.go

fix UT conflict after the last two descheduler commits are merged into the trunk

koord-descheduler: fix UT conflict

---

.goreleaser/koordlet.dockerfile
docker/koordlet.dockerfile

chore: add comments about CUDA version in dockerfile

---

pkg/runtimeproxy/resexecutor/cri/container_test.go
pkg/runtimeproxy/resexecutor/cri/pod_test.go

koord-runtime-proxy: add more tests

---

codecov.yml

ci: ignore apis & pkg/client in codecov

---

pkg/util/json_test.go

test: add Test_DumpJSON()

---

pkg/runtimeproxy/resexecutor/cri/container.go
pkg/runtimeproxy/resexecutor/cri/container_test.go
pkg/runtimeproxy/resexecutor/cri/utils.go
pkg/runtimeproxy/resexecutor/cri/utils_test.go
pkg/runtimeproxy/server/cri/runtime.go

koord-runtime-proxy: Introduce envs injecting under contianerd scenario

---

cmd/koord-manager/main.go
go.mod
go.sum
pkg/koordlet/koordlet.go
pkg/koordlet/statesinformer/config.go
pkg/koordlet/statesinformer/states_device.go
pkg/koordlet/statesinformer/states_device_test.go
pkg/koordlet/statesinformer/states_informer.go
pkg/koordlet/statesinformer/states_informer_test.go
pkg/slo-controller/noderesource/device_event_handler.go
pkg/slo-controller/noderesource/nodemetric_event_handler.go
pkg/slo-controller/noderesource/noderesource.go
pkg/slo-controller/noderesource/noderesource_controller.go
pkg/slo-controller/noderesource/noderesource_controller_test.go
pkg/slo-controller/noderesource/noderesource_test.go
pkg/util/node.go

feature: report gpu resource

---

go.mod
go.sum
pkg/koordlet/koordlet.go
pkg/koordlet/statesinformer/states_noderesourcetopology.go
pkg/util/system/cgroup_driver_linux.go
pkg/util/system/cgroup_driver_unsupported.go
pkg/util/system/common_linux.go
pkg/util/system/common_linux_test.go
pkg/util/system/cpu_manager_linux.go
pkg/util/system/cpu_manager_unsupported.go

feat: get kubelet pid through kubeletEndpoint port

---

.licenseignore
apis/extension/priority.go
apis/scheduling/config/types.go
apis/scheduling/config/v1beta2/types.go
cmd/koord-scheduler/main.go
docs/proposals/scheduling/20200901-gang-scheduling.md
pkg/scheduler/plugins/coscheduling/controller/podgroup.go
pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
pkg/scheduler/plugins/coscheduling/core/core.go
pkg/scheduler/plugins/coscheduling/core/core_test.go
pkg/scheduler/plugins/coscheduling/core/gang.go
pkg/scheduler/plugins/coscheduling/core/gang_cache.go
pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
pkg/scheduler/plugins/coscheduling/coscheduling.go
pkg/scheduler/plugins/coscheduling/coscheduling_test.go
pkg/scheduler/plugins/coscheduling/util/gang_helper.go

Enhance Scheduler-Plugins's Coscheduling by design the GangCache
the proposal #333

koord-scheduler: implement enhanced coscheduling

---

apis/extension/resource.go
apis/extension/scheduling.go
apis/extension/scheduling_test.go
cmd/koord-scheduler/main.go
pkg/scheduler/plugins/deviceshare/device_cache.go
pkg/scheduler/plugins/deviceshare/device_cache_test.go
pkg/scheduler/plugins/deviceshare/device_handler.go
pkg/scheduler/plugins/deviceshare/device_handler_test.go
pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/deviceshare/plugin_test.go
pkg/scheduler/plugins/deviceshare/pod_handler.go
pkg/scheduler/plugins/deviceshare/pod_handler_test.go
pkg/scheduler/plugins/deviceshare/utils.go
pkg/scheduler/plugins/deviceshare/utils_test.go

koord-scheduler: support device(GPU/RDMA/FPGA) sharing feature

---

pkg/koordlet/reporter/config.go
pkg/koordlet/reporter/config_test.go
pkg/koordlet/reporter/reporter.go

koordlet: startup flag replace int with time.Duration in reporter

---

pkg/scheduler/plugins/deviceshare/plugin_test.go

koord-scheduler: fix DeviceShare UT

---

.goreleaser.yaml

chore: add aliyun hangzhou registry when publish release

---

pkg/koordlet/resmanager/cpu_suppress.go

Signed-off-by: Guilhem Lettron <guilhem@barpilot.io>

fix: fix panic when NodeTopo is nil

---

.github/workflows/license.yml
hack/update-license-header.sh

chore: update license checker repo

---

go.mod
go.sum

feat(deps): bump github.com/NVIDIA/go-nvml

---

pkg/scheduler/plugins/elasticquota/controller.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/plugin_test.go
pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go

…ttest, and fix some ut failed
改UT的时候，发现原本准备plugin调用的UpdateRequest和UpdateUsed都被UpdatePodRequest和UpdatePodUsed取代了，所以改了一下写的比较早的UT的实现逻辑，规避了UpdateRequest和UpdateUsed的调用，将这两个函数删除。顺便修了几个UT。

koord-scheduler: optimize ElasticQuota UT

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go
pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
pkg/scheduler/plugins/elasticquota/core/quota_summary.go
pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
pkg/scheduler/plugins/elasticquota/plugin_service.go
pkg/scheduler/plugins/elasticquota/plugin_service_test.go
pkg/scheduler/plugins/elasticquota/quota_handler.go

Add API to help diagnose and analyze ElasticQuota problems.

koord-scheduler: add quota debug restful api

---

pkg/koordlet/statesinformer/states_device_linux.go
pkg/koordlet/statesinformer/states_device_linux_test.go

1. fix update Device CRD object failed  if koordlet restart or refresh
2. if the spec of device has not changed, ignore update.
fixes #629

koordlet: fix failed update existing Device CRD object

---

pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
pkg/scheduler/plugins/coscheduling/coscheduling_test.go
pkg/scheduler/plugins/coscheduling/plugin_service_test.go

fix coScheduling ut

---

pkg/scheduler/plugins/nodenumaresource/plugin_service.go
pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go

change the NodeNUMAResource plugin's API endpoints to use the same RestfulAPI style.

koord-scheduler: change NodeNUMAResource API endpoints

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/plugin_helper.go

koord-scheduler: fix quota panic if missing QuotaInfo

koord-scheduler: fix quota panic if missing QuotaInfo

---

pkg/koordlet/statesinformer/states_device_linux.go
pkg/slo-controller/noderesource/noderesource.go
pkg/slo-controller/noderesource/noderesource_test.go
pkg/util/resource.go

bugfix: not report when no gpu device

---

pkg/scheduler/plugins/coscheduling/coscheduling_test.go

fix CoScheduling ut:wg count negative bug

---

pkg/scheduler/plugins/elasticquota/controller.go
pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/plugin_helper.go

koord-scheduler: fix ElasticQuota panic when init

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go

chore: change ElasticQuota log level

---

pkg/koordlet/resmanager/memory_evict.go

fix the panic in memory evict candidate sorting when any pod metric is not found

koordlet: fix memory evict for nil podMetric

---

docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md

At present, Koordinator use `kubernetes.io` as resources' prefix , but the content of the proposal lags. 
Replace all resources name with `kubernetes.io`  with `koordinator.sh`

chore: update resource names in Fine-grained Device Scheduling proposal

---

pkg/scheduler/plugins/elasticquota/controller.go

koord-scheduler: fix ElasticQuota controller panic when update annotations

koord-scheduler: fix ElasticQuota controller panic when update annotations

---

pkg/scheduler/plugins/coscheduling/controller/podgroup.go

koord-scheduler: fix PodGroupController panic when init

---

pkg/koordlet/resmanager/cpu_burst.go
pkg/slo-controller/config/colocation_cm_event_handler_test.go
pkg/slo-controller/config/config.go
pkg/slo-controller/config/config_extender_test.go
pkg/slo-controller/config/config_test.go
pkg/slo-controller/config/zz_generated.deepcopy.go
pkg/slo-controller/noderesource/resource_calculator.go
pkg/slo-controller/noderesource/resource_calculator_test.go

support calculating batch memory resource based on pod requests instead of pod usages
#498

koord-manager: support calculate batch resource based on memory request

---

.github/ISSUE_TEMPLATE/bug-report.md

Signed-off-by: weizhou.ren <renweizhou.rwz@umeng.com>

chore: update bug issue template

---

pkg/scheduler/plugins/deviceshare/plugin.go

fix: correct pod informer delete event

---

cmd/koord-manager/main.go
pkg/scheduler/plugins/elasticquota/plugin_service_test.go
pkg/webhook/elasticquota/mutating/mutating_handle_test.go
pkg/webhook/elasticquota/mutating/mutating_handler.go
pkg/webhook/elasticquota/quota_topology.go
pkg/webhook/elasticquota/quota_topology_check.go
pkg/webhook/elasticquota/quota_topology_test.go
pkg/webhook/elasticquota/validating/validating_handler.go
pkg/webhook/elasticquota/validating/validating_handler_test.go
pkg/webhook/pod/validating/validating_handler.go
pkg/webhook/pod/validating/validating_handler_test.go

The main purpose is to reorganize the InjectCache function of the webhooks, only allow validate-quota to addEventHandlers.

koord-manager: modify quota-webhook

---

pkg/slo-controller/noderesource/noderesource.go

slo-controller report koordinator-gpu resource dimension

---

pkg/scheduler/plugins/coscheduling/core/gang_cache.go
pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go

fix gang by annotation create pg crd fail

---

pkg/koordlet/runtimehooks/protocol/container_context.go
pkg/koordlet/runtimehooks/protocol/protocol.go

this pr supplies cpushare inject logic in runtimehooks protocols

koordlet: supply cpushare inject logic in runtimehooks protocols

---

pkg/scheduler/plugins/nodenumaresource/plugin.go

this PR abstracts nodenumaresource plugin checklogic of QoS and priority.

koord-scheduler: abstract nodenumaresource plugin allowUseCPUSet

---

pkg/webhook/pod/validating/cluster_colocation_profile_test.go

chore: update ClusterColocationProfile UT

---

pkg/koordlet/pleg/pleg.go

Signed-off-by: huiwq1990 <huiwq1990@163.com>

fix pleg init err

---

cmd/koord-manager/main.go
pkg/features/features.go
pkg/features/koordlet_features.go
pkg/koordlet/statesinformer/states_noderesourcetopology.go

add webhook and node topo feature gates control

---

pkg/koordlet/executor/resource_update_executor.go
pkg/koordlet/resmanager/cpu_suppress.go

reducing nesting

---

pkg/koordlet/metriccache/api.go

fix typo in pkg/koordlet/metriccache/api.go

---

pkg/scheduler/plugins/coscheduling/controller/podgroup.go
pkg/scheduler/plugins/deviceshare/device_cache.go
pkg/scheduler/plugins/elasticquota/plugin_helper.go
pkg/scheduler/plugins/elasticquota/preempt.go

Signed-off-by: lucming <2876757716@qq.com>

making code easier to read

---

pkg/scheduler/plugins/compatibledefaultpreemption/preemption.go
pkg/scheduler/plugins/reservation/garbage_collection.go

…les in the preemption plugin
1. optimise the handling of error
2. optimise the initialisation logic of variables in the preemption plugin

code collation

---

pkg/koordlet/resmanager/cpu_evict.go
pkg/koordlet/resmanager/memory_evict.go

handling in this way can reduce the number of loops

fix:exit the loop when enough pods have been found to be evicted

---

pkg/koordlet/executor/resource_update_executor.go
pkg/koordlet/resmanager/cgroup_reconcile.go

fix: delete unused return args

---

config/manager/kustomization.yaml

`registry-vpc.cn-hangzhou.aliyuncs.com` is not a public address, switch to `registry.cn-hangzhou.aliyuncs.com`

chore: fix image registry in Kustomization

---

pkg/webhook/add_quota.go
pkg/webhook/api_debug_server.go
pkg/webhook/elasticquota/plugin_check_quota_meta_validate.go
pkg/webhook/elasticquota/quota_topology.go
pkg/webhook/elasticquota/validating/validating_handler.go
pkg/webhook/server.go

support webhook debug api

---

pkg/util/system/common_linux.go

fix: https://github.com/koordinator-sh/koordinator/issues/743

fix:failed to start nodeTopoInformer when tcp6 is not find in node

---

cmd/koordlet/main.go
cmd/koordlet/options/options.go
pkg/tools/cache/expiration_cache.go

koordlet: add pprof flag

---

apis/extension/resource.go
pkg/koordlet/statesinformer/states_device_linux.go
pkg/koordlet/statesinformer/states_device_linux_test.go
pkg/koordlet/statesinformer/states_device_unsupported.go
pkg/koordlet/statesinformer/states_informer.go
pkg/slo-controller/noderesource/noderesource.go
pkg/slo-controller/noderesource/noderesource_controller.go
pkg/slo-controller/noderesource/noderesource_test.go

koordlet report gpu model and driver version

---

pkg/util/system/config.go

This variable will be initialized to this value globally, and the global variable will be executed before init(), so there is no need to reassign it here.

fix: remove unnecessary reassignments

---

go.mod
go.sum
pkg/koordlet/metriccache/metric_cache.go
pkg/koordlet/metriccache/metric_cache_test.go
pkg/koordlet/metriccache/storage.go
pkg/koordlet/metriccache/storage_test.go
pkg/koordlet/metricsadvisor/collector.go

koordlet: add gc logs for metric cache

---

cmd/koord-scheduler/main.go

this PR export client-go metrics to help diagnose analysis problems for koord-scheduler.
fixes ##769

koord-scheduler: export client-go metrics

---

pkg/webhook/elasticquota/quota_handler.go
pkg/webhook/elasticquota/quota_info.go
pkg/webhook/elasticquota/quota_topology.go
pkg/webhook/elasticquota/quota_topology_check.go
pkg/webhook/elasticquota/quota_topology_test.go

Removed webhook's dependency on scheduler.

koord-manager: remove the quota webhook's dependency on koord-scheduler

---

pkg/webhook/pod/validating/cluster_colocation_profile_test.go
pkg/webhook/pod/validating/request_limit_validator.go

this PR add containerFilterFunc to requestLimitValidator in clusterColocationWebhook.

koord-manager: add containerFilterFunc in requestLimitValidator

---

config/rbac/role.yaml
pkg/slo-controller/noderesource/noderesource_controller.go
pkg/webhook/pod/mutating/cluster_colocation_profile.go

Supplement RBAC missed by koord-manager.

koord-manager: update RBAC

---

pkg/scheduler/plugins/elasticquota/node_handler.go

 koord-scheduler: fix ElasticQuota plugin don't clean node cache when node delete

---

pkg/descheduler/framework/runtime/framework.go
pkg/descheduler/framework/runtime/framework_test.go
pkg/descheduler/profile/profile.go
pkg/descheduler/profile/profile_test.go

Add test cases for descheduler profile.
NONE

koord-descheduler: add validator and tests for descheduler profile

---

config/rbac/scheduler_role.yaml

chore: remove scheduler Pod Update permissions

---

OWNERS_ALIASES

Add honpey into approvers alias:
runtime-proxy

Add honpey into approvers alias

---

OWNERS_ALIASES

Add saintube into approvers alias:
koordlet

Add saintube into approvers alias

---

pkg/scheduler/plugins/elasticquota/core/quota_info.go
pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/plugin_helper.go

Signed-off-by: fjding <dingfangjie@bytedance.com>
fixed quota deep copy and cyclestate

fixed quota deep copy and cyclestate

---

OWNERS_ALIASES

Add jasonliu747 into approvers alias

---

OWNERS_ALIASES

Add buptcozy into approvers alias

---

OWNERS_ALIASES

Add ZYecho into approvers alias

---

.github/workflows/codeql.yml
Makefile

ci: add cache to reduce the time of codeql

---

.github/workflows/ci.yaml

ci: simplify go build command

---

README-zh_CN.md
README.md

Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Add bi-weekly community meeting

Add bi-weekly community meeting

---

pkg/scheduler/plugins/elasticquota/plugin_helper.go
pkg/webhook/elasticquota/pod_check.go

Support the method of custom querying quota name

---

pkg/util/utils.go

Fix words typo in error message which returned by utils package.
NONE

utils: Fix words typo in error message

---

README-zh_CN.md
README.md

Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Update new slack channel in K8s workspace

Update new slack channel in K8s workspace

---

README-zh_CN.md

docs: add star history into README-zh_CN

---

pkg/scheduler/frameworkext/helper/synced_eventhandler.go

Make ForceSyncFromInformer easier to use.

koord-scheduler: make ForceSyncFromInformer easier to use

---

cmd/koordlet/main.go
config/manager/koordlet.yaml
pkg/features/koordlet_features.go
pkg/koordlet/runtimehooks/config.go
pkg/koordlet/runtimehooks/runtimehooks.go
pkg/koordlet/runtimehooks/runtimehooks_test.go
pkg/koordlet/statesinformer/states_informer_test.go

koordlet: release feature gates config

---

pkg/koordlet/pleg/pleg.go
pkg/koordlet/statesinformer/config.go
pkg/koordlet/statesinformer/config_test.go
pkg/koordlet/statesinformer/states_pods.go

memory limits of BE maybe too late to set if the pod sync interval is too long

koordlet: fix pleg to increase pod sync interval

---

config/rbac/descheduler_role.yaml

chore: update descheduler rbac

---

README-zh_CN.md

Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>

docs: fix community-membership url in README-zh_CN.md

---

README.md

docs: fix ci badge in README.md

---

README-zh_CN.md

docs: fix ci badge in README-zh_CN.md

---

pkg/koordlet/util/system/cgroup_resource.go

fix the range validator for cgroup resources `BlkioTRIopsName`...

koordlet: fix cgroup validators

---

pkg/descheduler/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go

koord-descheduler: remove duplicated validation

---

pkg/scheduler/plugins/deviceshare/device_cache.go
pkg/scheduler/plugins/deviceshare/plugin_test.go
pkg/scheduler/plugins/deviceshare/pod_handler_test.go

The DeviceShare plug-in allocates devices in ascending order of Minor to ensure predictable basic allocation logic.

koord-scheduler: DeviceShare plugin allocates devices in ascending order of Minor

---

pkg/scheduler/plugins/deviceshare/plugin.go

clean: resolve vet error

---

pkg/descheduler/framework/plugins/loadaware/low_node_load.go
pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go

koord-descheduler: fix LowNodeLoad when configuring nodeSelector

---

pkg/koordlet/statesinformer/extension_utils.go
pkg/koordlet/statesinformer/states_nodemetric.go

koordlet: support reporting extension resource in statesInformer

---

pkg/koordlet/statesinformer/states_nodemetric.go

koordlet: skip fillExtensionMap if podMetric is nil

---

pkg/koordlet/resmanager/cpu_suppress.go

Signed-off-by: Wang Xiaoqiang <wangxiaoqiang@qiyi.com>
fix log typo in cpu_suppress.go
NONE

koordlet: fix log typo

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go

koord-scheduler: fix GroupQuotaManager.updateMinQuotaNoLock

---

apis/scheduling/v1alpha1/pod_migration_job_types.go
pkg/descheduler/controllers/migration/controller.go

fix: https://github.com/koordinator-sh/koordinator/issues/1022

koord-descheduler: check pod ready when migrating

---

.github/stale.yml

Add stale config file

---

pkg/koordlet/metriccache/metric_cache.go
pkg/koordlet/metriccache/metric_cache_test.go
pkg/koordlet/metriccache/storage.go
pkg/koordlet/metriccache/storage_test.go
pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go

koordlet: add some logs for cpi and psi metric cache

---

test/e2e/slocontroller/batchresource.go

Fixe e2e BatchResource for custom namespaces.
#1069 fixes the problem when the customized slo-controller-config exists, but still has a trouble when the slo-controller-config does not exist.

e2e: fix e2e BatchResource for custom namespace

---

pkg/koordlet/resmanager/cpu_suppress.go

koordlet: fix kubelet policy nil

---

pkg/koordlet/metriccache/metric_cache.go
pkg/koordlet/qosmanager/metricsquery/metrics_query_test.go
pkg/koordlet/resmanager/metrics_query_test.go

fix:  https://github.com/koordinator-sh/koordinator/issues/911

koordlet: ensure report nodetopo after nodecpuinfo have already collected

---

pkg/slo-controller/noderesource/noderesource_controller.go

These three are already registered in batch resource plugin.
https://github.com/koordinator-sh/koordinator/blob/f8b4e311c603a635d95f7f4d7a57dfaf1932b7f7/pkg/slo-controller/noderesource/plugins/batchresource/plugin.go#L33-L37

koord-manager: remove duplicate registration in noderesource controller

---

docs/proposals/scheduling/20221227-node-resource-reservation.md

proposal for static cpu reservation.
Related pr:https://github.com/koordinator-sh/koordinator/pull/835

proposal: Node Resource Reservation

---

.github/workflows/ci.yaml
.github/workflows/license.yml
.github/workflows/release.yml

ci: disable cache when running actions/setup-go

---

pkg/koordlet/statesinformer/states_device_linux.go

koordlet: fix update Device object error
fix #1138

koordlet: fix update Device object error

---

pkg/descheduler/evictions/evictions.go

In kubernetes v1.20, only policy/v1beta1 eviction is supported, but the koord-descheduler compatibility method is incorrect. This PR fixes the issue.
fix #1135

koord-descheduler: improve compatibility with policy/v1beta1 eviction api

---

docs/proposals/scheduling/20221227-node-resource-reservation.md

docs: fix double-subtract node.anno.reserved

---

apis/extension/pod_evict.go
pkg/koordlet/koordlet.go
pkg/koordlet/resmanager/memory_evict_test.go
pkg/koordlet/resmanager/resmanager.go
pkg/koordlet/resmanager/resmanager_test.go
pkg/util/pod_evict.go

koordlet: pod eviction policy compatibility

---

pkg/koordlet/resmanager/cpu_evict_test.go

koordlet: fix cpu evict test

---

pkg/scheduler/plugins/deviceshare/pod_handler.go

koord-scheduler:  DeviceShare ensure NodeName is not empty when handling new Pod

---

pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go

koordlet: fix psicollector may cause other functions to block when started

---

pkg/descheduler/controllers/migration/controller.go
pkg/descheduler/controllers/migration/controller_test.go
pkg/descheduler/controllers/migration/filter.go

Filter migrationJobs in running state for migration reconcile.
fix #1150

koord-descheduler: filter migrationJobs in running state for migration reconcile

---

pkg/descheduler/framework/plugins/loadaware/low_node_load.go
pkg/descheduler/framework/plugins/loadaware/utilization_util.go

Optimize the log of the koord-descheduler plugin LowNodeLoad to improve readability and facilitate troubleshooting.

koord-descheduler: optimize LowNodeLoad logs

---

.github/workflows/ci.yaml

Allow Github action to run jobs in parallel. Greatly reduce the waiting time for test completion.

ci: run github actions job in parallel using matrix

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go
pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/plugin_helper.go
pkg/scheduler/plugins/elasticquota/plugin_test.go
pkg/scheduler/plugins/elasticquota/preempt.go

Reduce the calculation amount of QuotaInfo DeepCopy during preemption to optimize performance.
fix #1194

koord-scheduler: optimize ElasticQuota preemption performance

---

.licenseignore
test/e2e/scheduling/preemption.go

chore: update license ignore

---

pkg/koordlet/runtimehooks/hooks/hooks.go
pkg/koordlet/runtimehooks/rule/rule.go
pkg/koordlet/runtimehooks/runtimehooks.go

koordlet: cleanup runtimehooks code and remove the unused code
```
NONE
```

koordlet: cleanup runtimehooks and remove the unused code.

---

pkg/koordlet/statesinformer/states_pods.go

koordlet: improve newKubeletStub method.
```
NONE
```

koordlet: improve newKubeletStub method.

---

pkg/koordlet/statesinformer/states_device_linux.go
pkg/koordlet/statesinformer/states_informer.go

koordlet: fix statsinformer interface function implementation.
```
NONE
```

koordlet: fix statsinformer interface function implementation.

---

pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go

tests: add tests for LoadAwareScheduling estimator

---

pkg/koordlet/statesinformer/states_node.go

adjust node comparison method to improve program performance for nodeInformer event handler.
```
NONE
```

koordlet: adjust node comparison method to improve program performance

---

config/manager/koordlet.yaml
docker/koordlet.dockerfile

koordlet: update dockerfile and yaml file of koordlet

---

cmd/koord-descheduler/main.go

Provide Leaderelection metrics for koord-descheduler.

koord-descheduler: add leaderelection metric

---

pkg/koordlet/runtimehooks/protocol/container_context.go

bugfix: when cpuset is an empty string, error log

---

pkg/util/fieldindex/register.go

Use description table to describe the field indexers. This makes it easier to expand and add different indexers.

koord-manager: make fieldIndex register more scalable

---

pkg/koordlet/metrics/expire_metric.go
pkg/koordlet/metrics/expire_metric_test.go

Refactor the expiring metrics. Instead of running a GC goroutine for each metric vector, use a single goroutine to garbage collect expired metrics.
Improve the metric GC introduced in #1118.
- 10 gauge vectors and N metrics for each gauge.
- cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
```go
func BenchmarkMetricGC(b *testing.B) {
// ...
var wg sync.WaitGroup
metrics := generatePodMetrics(b.N, time.Now().Unix())
for i := 0; i < b.N; i++ {
m := metrics[i]
wg.Add(1)
go func() {
for j := 0; j < vecCount; j++ {
gcVecs[j].WithSet(m.labels, m.value)
}
wg.Done()
}()
}
wg.Wait()
}
```
```bash
$ # 1. (default) expireTime = 5 mins, interval = 1 min. Old 
BenchmarkMetricGC-12           63543             22914 ns/op           12005 B/op        279 allocs/op
$ # 1.(default) expireTime = 5 mins, …
```

koordlet: improve metric GC

---

cmd/koord-manager/main.go
cmd/koord-manager/options/controllers.go
cmd/koord-manager/options/options.go

Move the controller registration of the koord-manager into the options pkg instead of the main.go.

koord-manager: add controllers options

---

pkg/koordlet/resmanager/memory_evict.go

fix some log format errors
NONE

koordlet: fix log error

---

pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/deviceshare/plugin_test.go

DeviceShare skips zero requests.

koord-scheduler: DeviceShare skips zero requests

---

pkg/descheduler/controllers/migration/evictor/evictor_soft.go
pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/nodenumaresource/plugin.go
pkg/scheduler/plugins/reservation/plugin.go
pkg/util/utils.go
pkg/util/utils_test.go

koord-scheduler: optimize the patch implementation of the PreBind stage

koord-scheduler: optimize the patch implementation of the PreBind stage

---

cmd/koord-manager/options/options.go
cmd/koord-manager/options/options_test.go

Fix the bug of the koord-manager argument `--controllers` where all controllers are disabled by default.

koord-manager: fix options

---

pkg/scheduler/plugins/reservation/cache.go
pkg/scheduler/plugins/reservation/pod_eventhandler.go
pkg/scheduler/plugins/reservation/pod_eventhandler_test.go

koord-scheduler: complement Reservation plugin's Pod onUpdate handler.

koord-scheduler: complement Reservation plugin's Pod onUpdate handler

---

pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector.go
pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector.go
pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector_test.go
pkg/koordlet/metricsadvisor/framework/options.go
pkg/koordlet/metricsadvisor/framework/plugin.go
pkg/koordlet/metricsadvisor/framework/pod_filter.go
pkg/koordlet/metricsadvisor/framework/pod_filter_test.go
pkg/koordlet/metricsadvisor/metrics_advisor.go
pkg/koordlet/metricsadvisor/plugins_profile.go
pkg/koordlet/resourceexecutor/cgroup.go

Add PodFilter interface in metricsadvisor. It helps when we only want to use a plugin for collecting particular pods.

koordlet: add pod filter for metricsadvisor

---

pkg/descheduler/controllers/migration/reservation/util.go
pkg/descheduler/controllers/migration/reservation/util_test.go
pkg/features/features.go

make pvc reservation switchable
NONE

koord-descheduler: make pvc reservation switchable

---

pkg/scheduler/plugins/deviceshare/plugin.go

koord-scheduler: fix status is not handled correctly in DeviceShare

---

pkg/scheduler/frameworkext/framework_extender.go
pkg/scheduler/frameworkext/interface.go
pkg/scheduler/frameworkext/scheduler_adapter.go

Support internal special scenes.

koord-scheduler: add forget pod handler in extended handle

---

apis/config/v1alpha1/cluster_colocation_profile_types.go
config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml

koord-manager: remove priorityClassname validation in profile

---

OWNERS_ALIASES
pkg/yarn/OWNERS
pkg/yarn/controller/OWNERS
pkg/yarn/copilot/OWNERS

add some pkg dirs for YARN related modules, see https://github.com/koordinator-sh/koordinator/discussions/1297 for detailed desgins.

koord-yarn: add pkg dir for YARN related modules

---

pkg/scheduler/plugins/reservation/service_test.go

chore: resolve failed unit tests

---

apis/extension/resource.go
pkg/scheduler/plugins/deviceshare/utils.go
pkg/scheduler/plugins/deviceshare/utils_test.go

Supports the resource api of Hygon DCU accelerator device.

apis: support Hygon DCU device resource API

---

pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector.go
pkg/koordlet/pleg/pleg_test.go
pkg/koordlet/util/system/cgroup2.go
pkg/koordlet/util/system/cgroup_resource.go
pkg/koordlet/util/system/config.go
pkg/koordlet/util/system/util_test_tool.go

Fixes the flaky test `Test_beResourceCollector_Run()`.

koordlet: fix flaky test of BEResourceCollector

---

pkg/descheduler/evictions/utils/utils.go

fixes https://github.com/koordinator-sh/koordinator/issues/1348

koord-descheduler: compatible with k8s v1.21.x no policy/v1/eviction

---

pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go

#1335 has already supported Reservation, but if the Reservation has been deleted, maybe leaky some resources until waiting timeout.  This PR resolved the issue #1356 , reject the waiting reserve pod if Reservation has been deleted. 
fix #1356

koord-scheduler: reject waiting reserve pod if reservation has been deleted

---

pkg/scheduler/plugins/coscheduling/core/core.go
pkg/scheduler/plugins/coscheduling/core/gang_cache.go
pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go

Complement Coscheduling plugin's onPodUpdate handler.

koord-scheduler: complement Coscheduling plugin's onPodUpdate handler

---

pkg/koordlet/config/config.go
pkg/koordlet/koordlet.go
pkg/koordlet/prediction/config.go
pkg/koordlet/prediction/config_test.go
pkg/koordlet/prediction/peak_predictor.go
pkg/koordlet/prediction/peak_predictor_test.go
pkg/koordlet/prediction/predict_server.go
pkg/koordlet/prediction/predict_server_test.go
pkg/koordlet/prediction/prediction_test.go
pkg/koordlet/statesinformer/impl/states_informer.go
pkg/koordlet/statesinformer/impl/states_informer_test.go
pkg/koordlet/statesinformer/impl/states_nodemetric.go
pkg/koordlet/statesinformer/impl/states_nodemetric_test.go

koordlet: report the amount of reclaimable resources of the node

---

pkg/slo-controller/noderesource/framework/extender_plugin.go
pkg/slo-controller/noderesource/framework/extender_plugin_test.go
pkg/slo-controller/noderesource/framework/noderesource.go
pkg/slo-controller/noderesource/noderesource_controller.go
pkg/slo-controller/noderesource/plugins_profile.go
pkg/slo-controller/noderesource/resource_calculator.go
pkg/slo-controller/noderesource/resource_calculator_test.go

Enhance node-resource framework by adding NodeMetaSyncPlugin for updating node metadata.
It's helpful when we want to update node labels/annotations rather than the allocatable in node status.

koord-manager: enhance noderesource framework for updating node labels

---

pkg/koordlet/koordlet.go
pkg/koordlet/metriccache/util.go
pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
pkg/koordlet/prediction/predict_server.go
pkg/koordlet/resmanager/system_config.go
pkg/koordlet/resmanager/system_config_test.go
pkg/koordlet/runtimehooks/reconciler/reconciler.go

- Fixes the error in which the predict server is not setup.
- Revise log formatting.

koordlet: fix prediction setup

---

pkg/scheduler/plugins/deviceshare/device_handler_test.go
pkg/scheduler/plugins/deviceshare/pod_handler_test.go

koord-scheduler: remove unused tests in DeviceShare

---

pkg/scheduler/plugins/reservation/plugin.go
pkg/scheduler/plugins/reservation/plugin_test.go

Kubernetes Scheduling Framework v1.24  has supported return `framework.PreFilterResult` to improve the throughput, and Reservation plugin can return the nodeNames which has reservations that matched `ReservationAffinity`.
fix #1435

koord-scheduler: improve throughput with reservation via return PreFilterResult

---

pkg/scheduler/apis/config/v1beta2/types.go

koord-scheduler: fix missed json tag of internal configuration

---

apis/slo/v1alpha1/nodeslo_types.go
config/crd/bases/slo.koordinator.sh_nodeslos.yaml
pkg/koordlet/resmanager/cgroup_reconcile.go
pkg/koordlet/resmanager/cgroup_reconcile_test.go
pkg/koordlet/util/system/common.go

koordlet: change the `memory.high` calculation formula as 1.27

---

apis/extension/priority.go
pkg/koordlet/metrics/metrics.go
pkg/koordlet/metrics/metrics_test.go
pkg/koordlet/metrics/prediction.go
pkg/koordlet/metrics/resource_summary.go
pkg/koordlet/prediction/peak_predictor.go
pkg/koordlet/prediction/peak_predictor_test.go
pkg/koordlet/prediction/predict_server.go
pkg/koordlet/prediction/predict_server_test.go
pkg/koordlet/prediction/prediction.go
pkg/koordlet/prediction/prediction_test.go
pkg/koordlet/statesinformer/impl/states_nodemetric.go
pkg/util/resource.go
pkg/util/resource_test.go

koordlet: enhance the node prediction.
- Add the node priority predictor and the min predictor. s.t.
```
Reclaimable[Prod] := max(0, min(Requests[Prod] - Peak[Prod], sum(Request[ProdPod] - Peak[ProdPod])))
```

koordlet: enhance node prediction

---

pkg/koordlet/resmanager/resmanager.go
pkg/koordlet/resmanager/resmanager_test.go

Evict pod event object use pod better.
fixes #1449

koordlet: evict pod event object use pod

---

pkg/koordlet/koordlet.go
pkg/koordlet/util/system/cgroup_driver.go
pkg/koordlet/util/system/cgroup_driver_linux.go
pkg/koordlet/util/system/cgroup_driver_linux_test.go
pkg/koordlet/util/system/cgroup_driver_unsupported.go

koordlet: cleanup koordlet get the cgroup driver logic

---

pkg/descheduler/controllers/migration/controller_test.go
pkg/descheduler/controllers/migration/filter.go

This PR move expectedReplicas related check to filterExpectedReplicas and make it nonRetrivable.

koord-descheduler: podMigrationJob filterExpectedReplicas

---

pkg/koordlet/qosmanager/k8s/k8s.go

/cleanup fix a tiny variable😅
```
NONE
```

koordlet: rename kubeClinet to kubeClient

---

pkg/slo-controller/metrics/common.go
pkg/slo-controller/noderesource/framework/extender_plugin.go
pkg/slo-controller/noderesource/framework/extender_plugin_test.go
pkg/slo-controller/noderesource/framework/option.go
pkg/slo-controller/noderesource/framework/option_test.go
pkg/slo-controller/noderesource/noderesource_controller.go
pkg/slo-controller/noderesource/plugins_profile.go
pkg/slo-controller/noderesource/resource_calculator.go
pkg/slo-controller/noderesource/resource_calculator_test.go

- Add the SetupPlugin stage in the noderesource framework.
- Fix a bug where the prom metrics `slo_controller_nodemetric_spec_parse_count` and `slo_controller_nodeslo_spec_parse_count`  are misused.

koord-manager: add noderesource plugin setup options

---

pkg/koordlet/util/perf/perf_unsupported.go

koordlet: fix util/perf compilation errors on darwin

---

hack/run-test.sh
pkg/koordlet/util/system/cgroup2_test.go
pkg/koordlet/util/system/cgroup_test.go

Writing unittests codes with generative AI tools.

chore: add unittests

---

OWNERS_ALIASES

chore: adjust the order of reviewers

---

pkg/scheduler/apis/config/types.go
pkg/scheduler/apis/config/v1beta2/defaults.go
pkg/scheduler/apis/config/v1beta2/types.go
pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
pkg/scheduler/apis/config/v1beta2/zz_generated.defaults.go
pkg/scheduler/apis/config/validation/validation_pluginargs.go
pkg/scheduler/apis/config/zz_generated.deepcopy.go

Add new field `scoringStrategy` in DeviceShareArgs.
part of #1457

koord-scheduler: add scoring strategy in DeviceShareArgs

---

docs/proposals/scheduling/20230803-enhance-gpu-share-api.md

1. Clarify and restrict the usage of Device Resource APIs.
2. Add a new API to clearly express the semantics of GPU Share.

proposal: enhance GPU Share API

---

pkg/koordlet/prediction/peak_predictor.go
pkg/koordlet/statesinformer/impl/states_nodemetric.go

Improve peak predictor server. 
```
NONE
```

koordlet: improve peak predictor server

---

pkg/descheduler/apis/config/types_pluginargs.go
pkg/descheduler/apis/config/v1alpha2/defaults.go
pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
pkg/descheduler/apis/config/zz_generated.deepcopy.go
pkg/descheduler/controllers/migration/controller.go
pkg/descheduler/controllers/migration/controller_test.go
pkg/descheduler/controllers/migration/evict.go
pkg/descheduler/controllers/migration/filter.go
pkg/util/utils.go

enhancement of https://github.com/koordinator-sh/koordinator/pull/1533
pmj controller can assign many schedulers that can handle reservation.

koord-descheduler: pmj controller support assign many schedulers that can handle reservation

---

pkg/slo-controller/noderesource/device_resource_calculator.go

Optimize logs for reporting node devices

koord-manager: Optimize logs for reporting node devices

---

docs/proposals/20230608-nri-mode-resource-management.md

Fix CRIO versioni since CRIO support NRI from release-1.26.0

fix crio version

---

pkg/scheduler/frameworkext/helper/forcesync_eventhandler.go
pkg/scheduler/frameworkext/helper/forcesync_informer.go

Run E2E and find that the Case cannot pass, and the location discovery is a problem introduced by #1543 .

koord-scheduler: fix missing AddEventHandler with forceSyncEventHandler

---

.goreleaser.yaml
pkg/slo-controller/noderesource/noderesource_controller.go
pkg/slo-controller/noderesource/plugins_profile.go
pkg/util/resource.go
pkg/util/resource_test.go

1. koord-manager: fix the resource diff comparison when both old and new values are zero.
2. ci: refine the released runtime-proxy binary name.

koord-manager: fix noderesource update when compared values are zero

---

pkg/slo-controller/nodeslo/extender_config_test.go
pkg/slo-controller/nodeslo/extender_plugin.go
pkg/slo-controller/nodeslo/extender_plugin_test.go
pkg/slo-controller/nodeslo/nodeslo_controller.go
pkg/slo-controller/nodeslo/nodeslo_controller_test.go

koord-manager: fix node slo extension got overwriten

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go

fix OnPodUpdate
When pod update, the standby scheduler should update its usage cache

koord-scheduler: fix quota onPodUpdate

---

config/webhook/patch_manifests.yaml

Fix webhook patch manifests for pod update mutation

Fix webhook patch manifests for pod update mutation

---

cmd/koordlet/main.go

koordlet: fix http server with default pprof

koordlet: fix http server with default pprof

---

apis/extension/numa_aware.go

Add NUMA-aware topology policies, defined by the doc [NUMA Topology Scheduling](https://github.com/koordinator-sh/koordinator/blob/main/docs/proposals/scheduling/20230415-numa-topology-scheduling.md#numa-topology-policy)

apis: add NUMA-aware topology policies

---

docs/proposals/scheduling/20230811-node-resource-amplification.md

This PR is the proposal for #1539.

proposal: Node Resource Amplification

---

pkg/slo-controller/noderesource/device_resource_calculator.go
pkg/slo-controller/noderesource/device_resource_calculator_test.go

related pr: https://github.com/koordinator-sh/koordinator/pull/1594

koord-manager: cleanup node.alloc when device cr have been deleted

---

apis/extension/elastic_quota.go
pkg/scheduler/plugins/elasticquota/controller.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go
pkg/scheduler/plugins/elasticquota/core/quota_summary.go

fix runtime quota when quota is not allow lent resource

koord-scheduler: fix runtime quota when quota is not allow lent resource

---

hack/update-codegen.sh
pkg/client/clientset/versioned/typed/quota/v1alpha1/fake/fake_elasticquotaprofile.go
pkg/features/features.go
pkg/features/scheduler_features.go
pkg/scheduler/plugins/elasticquota/controller_test.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/node_handler.go
pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/plugin_test.go
pkg/scheduler/plugins/elasticquota/profile_handler.go
pkg/scheduler/plugins/elasticquota/profile_handler_test.go

add quota manager  for profile

Add multi quota tree

---

apis/scheduling/v1alpha1/device_types.go
config/crd/bases/scheduling.koordinator.sh_devices.yaml
config/crd/bases/slo.koordinator.sh_nodemetrics.yaml

apis: mark device health defaults to false

---

apis/extension/elastic_quota.go
apis/quota/v1alpha1/elastic_quota_profile_types.go
apis/quota/v1alpha1/zz_generated.deepcopy.go
cmd/koord-manager/options/controllers.go
cmd/koord-manager/options/scheme.go
config/crd/bases/quota.koordinator.sh_elasticquotaprofiles.yaml
pkg/quota-controller/profile/profile_controller.go
pkg/quota-controller/profile/profile_controller_test.go

add quota profile controller. It will update the quota

koord-manager: add quota profile controller

---

PROJECT
config/crd/kustomization.yaml
config/manager/kustomization.yaml
config/rbac/role.yaml
config/rbac/scheduler_role.yaml
pkg/quota-controller/profile/profile_controller.go

fix role for elasticquotaprofile

koord-manager: fix role for elasticquotaprofile

---

apis/extension/node_resource_amplification.go
apis/extension/node_resource_amplification_test.go

This PR introduces API and its utils for for node resource amplification.
Part of #1539

apis: introduce api for node resource amplification

---

config/webhook/manifests.yaml
pkg/webhook/elasticquota/validating/webhooks.go

ci: fix quota webhook verb

---

pkg/scheduler/plugins/elasticquota/plugin.go

koord-scheduler: ElasticQuota plugin implements EnqueueExtensions

---

apis/extension/elastic_quota.go
pkg/features/features.go
pkg/features/scheduler_features.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/helper.go
pkg/scheduler/plugins/elasticquota/core/helper_test.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go
pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/plugin_test.go
pkg/scheduler/plugins/elasticquota/preempt.go
pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go

koord-scheduler: add ElasticQuotaIgnoreOverhead feature-gate

---

pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
pkg/util/resource.go
pkg/util/resource_test.go

1. statesinformer: revise NRT reporting, mergeable update ZoneList so as to cooperate with NRT reporting of the other components.

koordlet: report NRT zone resources mergeable

---

pkg/koordlet/util/perf/perf_unsupported.go
pkg/koordlet/util/perf_group/perf_group_linux.go
pkg/koordlet/util/perf_group/perf_group_linux_test.go
pkg/koordlet/util/perf_group/perf_group_unsupported.go
pkg/koordlet/util/stat_test.go

koordlet: add perf cgroup unsupported

---

pkg/util/resource.go
pkg/util/resource_test.go
pkg/webhook/elasticquota/quota_topology_check.go
pkg/webhook/elasticquota/quota_topology_test.go

fix LessThanOrEqual for elastic quota webhook

koord-manager: fix  LessThanOrEqual in elastic quota

---

Makefile
hack/libpfm.sh

Add libpfm4 build script for Makefile.
fixes #1654 
run `make test`

Makefile: fix libpfm4 make test

---

apis/extension/elastic_quota.go
pkg/features/features.go
pkg/features/scheduler_features.go
pkg/scheduler/plugins/elasticquota/controller.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go
pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
pkg/webhook/elasticquota/quota_info.go
pkg/webhook/elasticquota/quota_topology_check.go
pkg/webhook/elasticquota/quota_topology_test.go

add ElasticQuotaGuaranteeUsage featuregate go guarantee usage

koord-scheduler: add ElasticQuota Guaranteed usage

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go

koord-scheduler: export min/max getters of QuotaInfo as public

---

pkg/features/features.go
pkg/features/scheduler_features.go
pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/plugin_helper.go
pkg/scheduler/plugins/elasticquota/pod_handler.go
pkg/scheduler/plugins/elasticquota/pod_handler_test.go
pkg/webhook/elasticquota/pod_check.go

add a feature gate to disable  default quota

add DisableDefaultQuota featuregate

---

pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go

koord-scheduler: LoadAware supports node amplification ratios

---

pkg/scheduler/plugins/elasticquota/plugin_service.go
pkg/scheduler/plugins/elasticquota/plugin_service_test.go

koord-scheduler: update elastic quota endpoint

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go
pkg/scheduler/plugins/elasticquota/plugin_test.go

inplace update quota min and max

koord-scheduler: inplace update quota min and max

---

pkg/scheduler/plugins/elasticquota/quota_handler.go
test/e2e/quota/multi_tree.go
test/e2e/quota/quota.go
test/e2e/quota/quota_guaranteed.go

e2e: add basic quota e2e cases

---

pkg/scheduler/plugins/nodenumaresource/resource_manager.go
pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go

Node A has two NUMA Nodes, and each NUMA Node has 52 CPUs. Each NUMA Node is allocated 44 CPUs to Pods that need to be bound to the CPU, and 4 CPUs are allocated to Pods in CPU Share mode. And assume that the NUMA Topology Policy of node A is Restricted or BestEffort. At this time, a Pod requires 8 CPUs and requires binding. The correct result is to allocate 4 CPUs from each of the two NUMA Nodes because of the remaining capacity of the two NUMA Nodes. The sum is accumulated to meet the Pod needs. In the previous code, if this was not the result, there was a problem.

koord-scheduler: fix NodeNUMAResource allocate CPUSets on mixed CPUSet/Share NUMA Node

---

pkg/scheduler/plugins/coscheduling/core/core.go
pkg/scheduler/plugins/coscheduling/core/core_test.go
pkg/scheduler/plugins/coscheduling/coscheduling.go
pkg/scheduler/plugins/coscheduling/coscheduling_test.go

scheduler: modify coscheduling Less function with considering childScheduleCycle

---

pkg/scheduler/frameworkext/framework_extender.go
pkg/scheduler/frameworkext/scheduler_adapter.go
pkg/util/transformer/device_transformer.go
pkg/util/transformer/node_transformer.go
pkg/util/transformer/pod_transformer.go

Use sync.pool to reduce GC overhead and remove unnecessary object allocations.

scheduler: optimize memory allocations

---

pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
pkg/koordlet/statesinformer/impl/states_pods.go

There are too many logs in koordlet now, but adjusting the log level is useless.

pkg/koordlet: update some log level to silence log

---

pkg/scheduler/plugins/nodenumaresource/resource_manager.go
pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go

Modify NUMA-Aware hints generator implementation.
Some specific scenarios, such as pods requesting memory and huge-pages at the same time, or requiring CPU binding, may conflict with generating hints from resources only, resulting in the fact that although hints are generated, they are actually unusable. So we need to consider these conditions when producing hints.

scheduler: revise numa-aware hints generator

---

apis/extension/operating_pod.go
pkg/scheduler/frameworkext/reservation_info.go
pkg/scheduler/frameworkext/reservation_info_test.go

Some scenarios require changes to Reservation.Spec.Owners, so this change needs to be detected during Update.

scheduler: update reservationInfo ownerMatchers if reservation updated

---

pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
pkg/util/node.go

functions in `pkg/util/extended_resource.go` maybe overwritten, such as GetBatchMilliCPUFromResourceList

koord-manager: get node batch allocatable from extended resource

---

apis/extension/device_share.go

provide koordinator.sh/gpu.shared to express several gpus are expected to be shared

api: add koordinator.sh/gpu.shared

---

apis/extension/device_share.go

For documentation on hint api, please refer to #1529

apis: add device allocate hints

---

pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux.go
pkg/koordlet/metricsadvisor/devices/gpu/collector_gpu_linux_test.go
pkg/koordlet/metricsadvisor/devices/gpu/helper.go
pkg/koordlet/metricsadvisor/devices/gpu/helper_test.go
pkg/koordlet/statesinformer/impl/states_device_linux.go
pkg/koordlet/statesinformer/impl/states_device_linux_test.go
pkg/koordlet/util/device.go
pkg/koordlet/util/system/system_file.go

Koordlet reports the hardware topology of GPU, including NUMA Node ID, PCIe ID and Device Bus ID.

koordlet: report gpu device topology

---

pkg/scheduler/plugins/deviceshare/device_allocator.go
pkg/scheduler/plugins/deviceshare/device_allocator_test.go
pkg/scheduler/plugins/deviceshare/device_cache.go
pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/deviceshare/plugin_test.go
pkg/scheduler/plugins/deviceshare/reservation.go
pkg/scheduler/plugins/deviceshare/scoring.go
pkg/scheduler/plugins/deviceshare/scoring_test.go
pkg/scheduler/plugins/deviceshare/topology_hint.go
pkg/scheduler/plugins/deviceshare/topology_hint_test.go
pkg/scheduler/plugins/deviceshare/utils.go

DeviceShare supports numa-aware scheduling.
implements #228 - koord-scheduler supports NUMA Topology Alignment scheduling with Device

scheduler: DeviceShare supports numa-aware scheduling

---

pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go

scheduler: fix DeviceShare concurrent map read and map write

---

pkg/scheduler/plugins/deviceshare/topology_hint.go

scheduler: DeviceShare skips numa-aware if no device requests

---

pkg/koordlet/util/system/lscpu_arm64.go

koordlet: fix lscpu for arm64

---

Makefile

timeout option for lint
args for docker build

chores: add args for Makefile

---

pkg/scheduler/plugins/reservation/cache.go
pkg/scheduler/plugins/reservation/plugin.go
pkg/scheduler/plugins/reservation/plugin_test.go
pkg/scheduler/plugins/reservation/transformer.go

scheduler: Reservation supports preempting permitted pods

---

pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
pkg/scheduler/plugins/deviceshare/device_resources.go
pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/deviceshare/plugin_test.go
pkg/scheduler/plugins/deviceshare/reservation.go
pkg/scheduler/plugins/reservation/cache.go
pkg/scheduler/plugins/reservation/plugin.go
pkg/scheduler/plugins/reservation/plugin_test.go

scheduler: fix the calculation method in PreFilterExtension

---

pkg/scheduler/plugins/deviceshare/device_allocator.go
pkg/scheduler/plugins/deviceshare/devicehandler_default.go
pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go

Support DeviceHandler to selectively generate requests and replicas

scheduler: support DeviceHandler to selectively generate requests and replicas

---

pkg/scheduler/plugins/deviceshare/device_allocator.go
pkg/scheduler/plugins/deviceshare/devicehandler_default.go
pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go

Optimize the DeviceHandler interface and add Pod and Node parameters to facilitate DeviceHandler to perceive additional information and calculate requests and replicas.

scheduler: optimize DeviceHandler interface

---

pkg/scheduler/plugins/reservation/plugin.go
pkg/scheduler/plugins/reservation/plugin_test.go
pkg/scheduler/plugins/reservation/transformer.go

scheduler: remove useless code from Reservation plugin

---

.github/dependabot.yml

chore: only require security updates and exclude version updates

---

pkg/scheduler/plugins/deviceshare/scoring.go

scheduler: refine log in device share plugin

---

pkg/scheduler/plugins/reservation/plugin.go
pkg/scheduler/plugins/reservation/transformer.go

scheduler: fix skip logic in reservation plugin

---

pkg/descheduler/utils/sorter/helper.go
pkg/koordlet/metriccache/util.go
pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector.go
pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
pkg/koordlet/util/system/resctrl.go
pkg/koordlet/util/system/resctrl_linux.go
pkg/koordlet/util/system/resctrl_test.go
pkg/koordlet/util/system/resctrl_unsupported.go
pkg/koordlet/util/system/resctrl_unsupported_test.go
pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
pkg/scheduler/plugins/loadaware/pod_assign_cache_test.go
pkg/util/sloconfig/validator.go
pkg/util/sloconfig/validator_test.go
pkg/webhook/cm/plugins/sloconfig/checkers_test.go
pkg/webhook/cm/plugins/sloconfig/cpu_burst_checker_test.go
pkg/webhook/cm/plugins/sloconfig/resource_qos_checker_test.go
pkg/webhook/cm/plugins/sloconfig/resource_threshold_checker_test.go
pkg/webhook/cm/plugins/sloconfig/slo_config_plugin_test.go
pkg/webhook/cm/plugins/sloconfig/system_config_checker_test.go
pkg/webhook/cm/validating/validating_handler_test.go
pkg/webhook/node/plugins/sloconfig/slo_plugin_test.go
pkg/webhook/node/validating/validating_handler_test.go
pkg/webhook/util/writer/atomic/atomic_writer.go

chore: fix the found errors for the license header and deadcode. also, revise the logs in the podthrottled collector and metric cache.
These errors occasionally are linted when using the linter with a higher version. However, the linter's upgrade depends on the Golang version. e.g. The golangci-lint v1.51.2 requires go1.19. So let's separate the issues and just fix the lint errors in the current PR.

chore: fix some unlinted errors

---

pkg/koordlet/util/perf_group/perf_group_linux.go

fix memory leak in perfGroup module

koordlet: fix memory leak in perfGroup

---

pkg/scheduler/plugins/elasticquota/controller.go

scheduler: fix ElasaticQuota sync status missing decorate used

---

ADOPTERS.md

Add Asiainfo as Adopter
N/A
N/A
N/A
N/A

Add a new adopter

---

pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go

koordlet: fix metric record err

---

pkg/webhook/elasticquota/mutating/mutating_handle_test.go
pkg/webhook/elasticquota/quota_topology.go

fix webhook for root quota creation

webhook: fix webhook for root quota creation

---

pkg/webhook/pod/validating/verify_annotations.go
pkg/webhook/pod/validating/verify_annotations_test.go

webhook: remove some annotation verify

---

pkg/scheduler/plugins/reservation/plugin.go

scheduler: fix reservation restricted options

---

pkg/koordlet/metriccache/tsdb_storage.go
pkg/koordlet/statesinformer/impl/kubelet_stub.go

koordlet:
1. Fix the outdated configured Prometheus registry for the TSDB.
2. Fix the panic when the kubeletStub GetAllPods/GetKubeletConfiguration returns a nil response.

koordlet: fix GetAllPods error and wrong tsdb prometheus registry

---

pkg/features/features.go
pkg/features/scheduler_features.go
pkg/webhook/elasticquota/pod_check.go
pkg/webhook/elasticquota/quota_topology_test.go

This pr add a featureGate for users to remove the restriction of parent quota submit pods.

manager: add featuregate to remove the restriction of parent quota submit pods

---

.github/workflows/ci.yaml

CI workflow with codecov token

CI workflow with codecov token

---

README-zh_CN.md
README.md
SECURITY.md
embargo-policy.md

chores: add security docs

---

go.mod
pkg/koordlet/metriccache/config.go
pkg/koordlet/metriccache/config_test.go
pkg/koordlet/metriccache/mockmetriccache/mock_tsdb_storage.go
pkg/koordlet/metriccache/tsdb_storage.go
pkg/koordlet/prediction/prediction.go
pkg/koordlet/qosmanager/helpers/metrics_query.go
pkg/koordlet/qosmanager/helpers/metrics_query_test.go
pkg/koordlet/qosmanager/plugins/cpuburst/cpu_burst_test.go
pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict_test.go
pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress_test.go
pkg/koordlet/qosmanager/plugins/memoryevict/memory_evict_test.go
pkg/koordlet/statesinformer/impl/states_nodemetric.go
pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
pkg/koordlet/util/testutil/mock_utils.go

koordlet: add close for querier

---

pkg/scheduler/plugins/elasticquota/core/quota_info.go

scheduler: quota info deepcopy withou pod deepcopy

---

pkg/scheduler/plugins/coscheduling/core/gang.go
pkg/scheduler/plugins/coscheduling/core/gang_cache.go
pkg/scheduler/plugins/coscheduling/core/gang_test.go

scheduler: fix panic of podGroup and pod delete order issue

---

README-zh_CN.md
README.md

This PR added the OpenSSF Best Practices Badge in README files.

chores: add openssf best practices badge into README

---

pkg/webhook/node/mutating/mutating_handler.go
pkg/webhook/pod/mutating/mutating_handler.go

webhook: optimize webhook patchResponse function

---

pkg/koordlet/pleg/pleg_test.go

koordlet: revise flaky test in pleg

---

apis/extension/reservation.go
pkg/util/reservation/reservation.go

scheduler: support empty reservation affinity

---

pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
pkg/scheduler/plugins/deviceshare/plugin_test.go
pkg/scheduler/plugins/deviceshare/reservation.go
pkg/scheduler/plugins/deviceshare/reservation_test.go
pkg/scheduler/plugins/reservation/plugin.go
pkg/scheduler/plugins/reservation/plugin_test.go
pkg/scheduler/plugins/reservation/transformer.go
pkg/scheduler/plugins/reservation/transformer_test.go

scheduler: add reservation level event 

---

pkg/scheduler/plugins/coscheduling/coscheduling_test.go

scheduler: fix fairness ut

---

OWNERS_ALIASES

Add ZiMengSheng into approvers alias

---

pkg/scheduler/plugins/reservation/plugin.go

scheduler: fix reservation plugin clone concurrent read write

---

pkg/scheduler/plugins/elasticquota/pod_handler_test.go

scheduler: fix elastic quota TestPlugin_OnPodDelete random panic

---

pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go

PR #2066 has some merge conflict that was solved wrongly by system. This make the lint and unit-tests failed.

chore: fix low node load test after prod thresholds added

---

docs/proposals/koordlet/20231227-koordlet-resctrl-qos-enhance.md

Update more detail about supporting QoS class resctrl runtime hook

koordlet: update resctrl qos proposal

---

pkg/descheduler/framework/plugins/loadaware/utilization_util.go

fix descheduler prod usage log

koord-descheduler: fix descheduler log

---

pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/deviceshare/reservation.go

scheduler: reduce deviceShare memory overhead

---

go.mod
go.sum
pkg/koordlet/runtimehooks/nri/server.go
pkg/koordlet/runtimehooks/nri/server_test.go

Upgrade NRI to 0.6.1
fixes #2131

koordlet: upgrade nri to 0.6.1

---

apis/extension/device_share.go
docs/proposals/scheduling/20230803-device-allocate-hint-apis.md
pkg/scheduler/plugins/deviceshare/device_allocator.go
pkg/scheduler/plugins/deviceshare/device_allocator_test.go
pkg/scheduler/plugins/deviceshare/numa_topology.go
pkg/scheduler/plugins/deviceshare/plugin_test.go

scheduler: support device topology strategy

---

pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/deviceshare/plugin_test.go
pkg/scheduler/plugins/deviceshare/scoring.go
pkg/scheduler/plugins/nodenumaresource/plugin.go
pkg/scheduler/plugins/nodenumaresource/plugin_test.go
pkg/scheduler/plugins/nodenumaresource/scoring.go

scheduler: skip uncessary Filter&Score plugin

---

pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go

This PR add maxMigratingGlobally json tag to enable configuration of this arg.

koord-descheduler: fix maxMigratingGlobally arg json tag

---

pkg/scheduler/plugins/nodenumaresource/plugin.go
pkg/scheduler/plugins/nodenumaresource/plugin_test.go
pkg/scheduler/plugins/nodenumaresource/resource_manager.go

scheduler: return framework.Unschedulable when cpuPolicy not satisfied

---

pkg/koordlet/runtimehooks/hooks/hooks.go

A module may have multiple hooks, and the current logs cannot distinguish which specific hook was registered or invoked.
It is essential to add some necessary descriptive information.

koordlet: add some information to improve log readability

---

.github/workflows/e2e-k8s-1.22.yaml
.github/workflows/e2e-k8s-1.24.yaml
.github/workflows/e2e-k8s-1.28.yaml
.github/workflows/e2e-k8s-latest.yaml

- Add a disk GC step to free enough spaces to run E2E tests.

ci: add disk GC for E2E jobs

---

pkg/scheduler/plugins/deviceshare/numa_topology.go

scheduler: fix panic when NUMANode equals -1

---

go.mod
pkg/scheduler/plugins/coscheduling/core/core.go
pkg/scheduler/plugins/coscheduling/coscheduling_test.go

scheduler: fix too many ut log

---

config/manager/scheduler-config.yaml
pkg/scheduler/plugins/coscheduling/core/core.go
pkg/scheduler/plugins/coscheduling/core/core_test.go
pkg/scheduler/plugins/coscheduling/core/ganggroup.go
pkg/scheduler/plugins/coscheduling/coscheduling.go
pkg/scheduler/plugins/coscheduling/coscheduling_test.go

support scheduler v1 config
add preEnqueue phase for gang plugin
need merge https://github.com/koordinator-sh/koordinator/pull/2167 first, support scheduler config v1
https://github.com/koordinator-sh/koordinator/issues/2140

scheduler: add coscheduling preEnqueue

---

pkg/scheduler/plugins/coscheduling/core/core_test.go
pkg/scheduler/plugins/coscheduling/core/gang.go
pkg/scheduler/plugins/coscheduling/core/gang_cache.go
pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
pkg/scheduler/plugins/coscheduling/core/gang_summary.go
pkg/scheduler/plugins/coscheduling/core/ganggroup.go
pkg/scheduler/plugins/coscheduling/core/ganggroup_test.go
pkg/scheduler/plugins/coscheduling/coscheduling_test.go

schedler: move gang OnceSatified to gangGroupInfo

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go

fix pod update when pod creation is before quota creation

scheduler: fix pod update when pod creation is before quota creation

---

pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
pkg/scheduler/frameworkext/framework_extender.go

scheduler: fix panic when nonimatingInfo nil

---

apis/scheduling/v1alpha1/reservation_types.go

apis: add protobuf for reservation

---

pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/plugin_test.go

- koord-scheduler: Fix the Clone() of the ElasticQuota's cycle state.

scheduler: fix ElasticQuota state's Clone

---

pkg/descheduler/controllers/migration/util/util.go
pkg/descheduler/controllers/migration/util/util_test.go

koord-descheduler: fix migration controller max unavailable computing algorigthm

---

pkg/slo-controller/nodemetric/node_event_handler.go
pkg/slo-controller/nodemetric/node_event_handler_test.go

#2116
enqueue request when node update labels
running in local

koord-manager: nodeslo-controller enqueue request when node labels updated

---

pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
pkg/scheduler/frameworkext/reservation_info.go
pkg/scheduler/plugins/reservation/plugin.go
pkg/scheduler/plugins/reservation/plugin_test.go
pkg/scheduler/plugins/reservation/transformer.go
pkg/scheduler/plugins/reservation/transformer_test.go
pkg/util/reservation/reservation.go

- Support the reservation name and taints & tolerations in the reservation scheduling.
fixes #2183, #2184.

scheduler: support reservation name, taints and tolerations

---

apis/extension/device_share.go
apis/extension/device_share_test.go
docs/proposals/scheduling/20241008-gpu-partition-api.md

apis: GPU Partition related

---

pkg/scheduler/plugins/deviceshare/utils.go

scheduler: support amd

---

pkg/scheduler/plugins/deviceshare/device_allocator.go
pkg/scheduler/plugins/deviceshare/numa_topology.go
pkg/scheduler/plugins/deviceshare/topology_hint.go

scheduler: allocate tolerate numa-meaning-less device

---

apis/extension/device_share.go
apis/extension/device_share_test.go
pkg/scheduler/plugins/deviceshare/allocator_gpu.go
pkg/scheduler/plugins/deviceshare/allocator_gpu_helper_test.go

scheduler: fix partition binpack disorder

---

pkg/scheduler/plugins/deviceshare/device_allocator_test.go
pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
pkg/scheduler/plugins/deviceshare/devicehandler_gpu_test.go
pkg/scheduler/plugins/deviceshare/plugin_test.go
pkg/scheduler/plugins/deviceshare/reservation_test.go

scheduler: fix gpu shared bug

---

pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
pkg/scheduler/plugins/loadaware/load_aware_test.go

scheduler: fix scaling factor 100 for burstable pod

---

cmd/koord-manager/main.go
pkg/slo-controller/metrics/common.go
pkg/slo-controller/metrics/metrics.go
pkg/slo-controller/metrics/metrics_test.go
pkg/slo-controller/metrics/node_resource.go
pkg/util/metrics/koordmanager/leader.go
pkg/util/metrics/koordmanager/registry.go

koord-manager: mv slo-controller metrics to util

---

pkg/scheduler/frameworkext/framework_extender.go

当 Pod 由于 SchedulingCycle Invalid 失败时，设置 failedPlugin，避免 Pod 由于一些不相关的事件进入 BackoffQ

scheduler: setFailedPlugin when plugin transformer failed

---

pkg/scheduler/frameworkext/topologymanager/manager.go
pkg/scheduler/frameworkext/topologymanager/policy.go
pkg/scheduler/frameworkext/topologymanager/policy_best_effort.go
pkg/scheduler/frameworkext/topologymanager/policy_none.go
pkg/scheduler/frameworkext/topologymanager/policy_none_test.go
pkg/scheduler/frameworkext/topologymanager/policy_restricted.go
pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node.go
pkg/scheduler/frameworkext/topologymanager/policy_test.go
pkg/scheduler/plugins/deviceshare/topology_hint.go
pkg/scheduler/plugins/deviceshare/topology_hint_test.go

optimize NUMA Affinity Error, give which resource is unsatisfied

scheduler: make error more clear when numa-aware

---

pkg/scheduler/plugins/nodenumaresource/plugin.go

scheduler: fix singleNUMANodeExclusive not clone

---

pkg/scheduler/frameworkext/topologymanager/policy.go

scheduler: fix UT Fail cause map iterate

---

pkg/scheduler/frameworkext/framework_extender.go
pkg/scheduler/frameworkext/framework_extender_factory.go
pkg/scheduler/frameworkext/scheduler_monitor.go
pkg/scheduler/frameworkext/scheduler_monitor_test.go

scheduler: enhance the SchedulerMonitor for extensions.

scheduler: extend schedulerMonitor

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res_test.go

scheduler: delete quota inplace

---

pkg/scheduler/frameworkext/helper/forcesync_eventhandler.go
pkg/scheduler/frameworkext/helper/forcesync_eventhandler_test.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/quota_handler.go
pkg/scheduler/plugins/elasticquota/quota_handler_test.go

scheduler: add quota inplace

---

pkg/scheduler/plugins/elasticquota/quota_handler_test.go

scheduler: fix ReplaceQuotas ut

scheduler: fix ReplaceQuotas ut

---

cmd/koord-scheduler/app/server.go
pkg/scheduler/frameworkext/informer/informers.go
pkg/scheduler/frameworkext/informer/informers_test.go
pkg/scheduler/frameworkext/topologymanager/manager.go

scheduler: refactor custom informers for extensions.

scheduler: move custom informers for extension

---

pkg/koordlet/statesinformer/impl/states_pod_resources.go
pkg/koordlet/statesinformer/impl/states_pod_resources_test.go

koordlet: fix podresources not found

---

pkg/koordlet/statesinformer/impl/states_pod_resources.go
pkg/koordlet/statesinformer/impl/states_pod_resources_test.go

koordlet: fix UT for podresources

---

pkg/scheduler/plugins/nodenumaresource/reservation.go
pkg/scheduler/plugins/nodenumaresource/resource_manager.go

scheduler: optimize nodeNUMAResource performance

---

pkg/scheduler/plugins/nodenumaresource/topology_options.go
pkg/scheduler/plugins/nodenumaresource/topology_options_test.go

scheduler: fix numaNodeResource not reserve cpu

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go
pkg/scheduler/plugins/elasticquota/plugin_test.go
pkg/scheduler/plugins/elasticquota/quota_handler_test.go

scheduler: inplace update quota when quota parent change

scheduler: inplace update quota when quota parent change

---

pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go

scheduler: update quota tree when quota spec changed

---

apis/slo/v1alpha1/nodeslo_types.go
apis/slo/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/slo.koordinator.sh_nodeslos.yaml
pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress_test.go

koordlet: support to configure the min threshold for BECPUSuppress.

koordlet: BECPUSuppress supports cpuSuppressMinPercent

---

pkg/scheduler/frameworkext/scheduler_adapter.go

scheduler: make Activate invokable by handle

---

pkg/util/metrics/expire_metric.go
pkg/util/metrics/expire_metric_test.go

fix: https://github.com/koordinator-sh/koordinator/issues/2376

feature(GCmetrics): support GCHistogramVec for util package

---

pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile.go
pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile_test.go

- This PR https://github.com/koordinator-sh/koordinator/pull/2205/files has been inactive for a long time and we need to push forward the fix.

fix(koordlet):BlkIOReconcile plugin not using WaitForCacheSync method correctly to synchronize

---

pkg/scheduler/frameworkext/framework_extender.go
pkg/scheduler/plugins/reservation/plugin.go

scheduler: add log for diagnosize

---

pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/pod_handler.go
pkg/scheduler/plugins/reservation/plugin_test.go
pkg/scheduler/plugins/reservation/pod_eventhandler.go
pkg/scheduler/plugins/reservation/transformer.go
pkg/scheduler/plugins/reservation/transformer_benchmark_test.go
pkg/scheduler/plugins/reservation/transformer_test.go

scheduler: add elasticquota ForgetPod, enable lazyreservationrestore for preferred topologyspread

---

.github/workflows/e2e-k8s-1.22.yaml
.github/workflows/e2e-k8s-1.24.yaml
.github/workflows/e2e-k8s-1.28.yaml
.github/workflows/e2e-k8s-latest.yaml

ref: https://github.com/koordinator-sh/koordinator/actions/runs/14337905548/job/40189636250?pr=2395
https://github.com/actions/runner-images/issues/11101

chore: update actions runner image  to Ubuntu 22.04

---

apis/scheduling/v1alpha1/reservation_types.go
config/crd/bases/scheduling.koordinator.sh_reservations.yaml

- add default Pending phase when creating reservation

apis: add default Pending phase when creating reservation

---

pkg/scheduler/metrics/metrics.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pkg/scheduler/plugins/elasticquota/core/quota_info.go
pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/quota_handler.go

add metrics for elastic quota and refact UpdateQuota

scheduler: add metrics for elastic quota and refact UpdateQuota

---

pkg/scheduler/apis/config/types.go
pkg/scheduler/apis/config/v1/defaults.go
pkg/scheduler/apis/config/v1/types.go
pkg/scheduler/apis/config/v1/zz_generated.conversion.go
pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
pkg/scheduler/apis/config/v1beta3/defaults.go
pkg/scheduler/apis/config/v1beta3/types.go
pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
pkg/scheduler/plugins/loadaware/load_aware.go
pkg/scheduler/plugins/loadaware/pod_assign_cache.go
pkg/scheduler/plugins/reservation/controller/controller.go
pkg/scheduler/plugins/reservation/controller/controller_test.go
pkg/scheduler/plugins/reservation/controller/garbage_collection_test.go
pkg/scheduler/plugins/reservation/plugin.go

scheduler: reduce loadaware lock overhead, improve reservation args

---

pkg/scheduler/plugins/deviceshare/device_allocator.go
pkg/scheduler/plugins/deviceshare/device_cache.go
pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/deviceshare/plugin_test.go
pkg/scheduler/plugins/deviceshare/reservation.go

scheduler: support DispenseWithLRNDeviceAllocation

---

pkg/scheduler/apis/config/types.go
pkg/scheduler/apis/config/v1/defaults.go
pkg/scheduler/apis/config/v1/types.go
pkg/scheduler/apis/config/v1/zz_generated.conversion.go
pkg/scheduler/apis/config/v1beta3/defaults.go
pkg/scheduler/apis/config/v1beta3/types.go
pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
pkg/scheduler/apis/config/validation/validation_pluginargs.go
pkg/scheduler/plugins/reservation/controller/controller.go
pkg/scheduler/plugins/reservation/controller/controller_test.go
pkg/scheduler/plugins/reservation/controller/garbage_collection.go
pkg/scheduler/plugins/reservation/controller/garbage_collection_test.go
pkg/scheduler/plugins/reservation/plugin.go

fix: https://github.com/koordinator-sh/koordinator/issues/2400

scheduler: Add gcDurationSeconds field to ReservationArgs

---

pkg/scheduler/plugins/elasticquota/core/quota_info.go

scheduler: change quota info to rw lock

---

pkg/scheduler/plugins/deviceshare/device_allocator.go
pkg/scheduler/plugins/deviceshare/device_cache.go
pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/deviceshare/utils.go

scheduler: optimize filterNodeDevice

---

pkg/scheduler/metrics/metrics.go
pkg/scheduler/plugins/deviceshare/device_cache.go

scheduler: correct secondaryDeviceNotWellPlanned metric

---

pkg/scheduler/apis/config/types.go

update EnableRuntimeQuota param description,and the description under [config/v1](https://github.com/koordinator-sh/koordinator/blob/main/pkg/scheduler/apis/config/v1/types.go#L209) and [config/v1beta3](https://github.com/koordinator-sh/koordinator/blob/main/pkg/scheduler/apis/config/v1beta3/types.go#L209)  are right.

chore: update EnableRuntimeQuota param description

---

pkg/scheduler/plugins/deviceshare/allocator_gpu.go
pkg/scheduler/plugins/deviceshare/allocator_gpu_test.go

scheduler: fix shared gpu binpack bug

---

apis/extension/multi_scheduler.go
pkg/util/transformer/pod_transformer.go

scheduler: support multi-scheduler

---

pkg/scheduler/plugins/elasticquota/plugin.go
pkg/scheduler/plugins/elasticquota/plugin_helper.go
pkg/scheduler/plugins/elasticquota/plugin_test.go

scheduler: fix CheckParentQuota bug when multiquotatree

---

config/manager/scheduler-config.yaml

e2e: disable LoadAware Filter to fix flaky test

---

pkg/scheduler/plugins/deviceshare/device_cache.go
pkg/scheduler/plugins/deviceshare/device_cache_test.go

scheduler: fix calFreeWithPreemptible modify nodeDevice

---

pkg/scheduler/plugins/deviceshare/device_allocator.go
pkg/scheduler/plugins/deviceshare/plugin.go
pkg/scheduler/plugins/deviceshare/plugin_test.go
pkg/scheduler/plugins/deviceshare/utils.go

scheduler: gpuSharedPod doesn't fit secondaryDeviceWellPlanned

---

pkg/scheduler/apis/config/validation/validation_pluginargs.go
pkg/scheduler/plugins/nodenumaresource/plugin.go

chore: refactor ValidateNodeNUMAResourceArgs func and add miss NUMAScoringStrategy validate

---

pkg/webhook/elasticquota/quota_topology.go

scheduler: fix quota webhook panic

scheduler: fix quota webhook panic

---

pkg/scheduler/plugins/coscheduling/core/gang.go

scheduler: fix nodeName filter fail

---

pkg/koordlet/metricsadvisor/framework/config.go

[Fix](koordlet: fix resctrl metric releated flags's comment.)
NONE

koordlet: fix resctrl metric releated flags's comment.

---

pkg/scheduler/plugins/defaultprebind/plugin.go
pkg/util/utils.go
pkg/util/utils_test.go

- Revise the safe Patch in PreBind by adding a new function instead of affecting the original.

scheduler: revise PreBind safe Patch

---

pkg/scheduler/plugins/deviceshare/plugin.go

scheduler: support leave allocate logic to kubelet

---

pkg/scheduler/plugins/reservation/controller/controller.go
pkg/scheduler/plugins/reservation/controller/pod_eventhandler.go

- use RWMutex instead of Mutex

scheduler: use RWMutex instead of Mutex

---

README-zh_CN.md
README.md

Update meeting and docs link in readme

chores: update community meeting information

---

apis/config/v1alpha1/cluster_colocation_profile_types.go
config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml

manager: fix typo for colocationprofile

---

pkg/scheduler/frameworkext/framework_extender_factory.go
pkg/scheduler/plugins/coscheduling/core/core.go
pkg/scheduler/plugins/coscheduling/core/gang_context.go

scheduler: mark gangGroupScheduling with startTime and fix pod status

---

pkg/scheduler/frameworkext/scheduler_monitor.go

koord-scheduler
- Fix the noisy timeout logs about unhandled pods cached in the scheduler monitor.

scheduler: fix unhandled timeout in SchedulerMonitor

---

OWNERS_ALIASES

Update descheduler approvers

---

pkg/controller/colocationprofile/colocationprofile_util.go
pkg/controller/colocationprofile/colocationprofile_util_test.go

- support namespace selector for ClusterColocationProfile in controller

colocationprofile: support namespace selector for ClusterColocationProfile in controller

---

pkg/scheduler/apis/config/validation/validation_pluginargs.go

- add loadaware plugins Aggregated args Validate

scheduler: add loadaware plugins Aggregated Args Validate

---

pkg/scheduler/plugins/deviceshare/service_test.go

scheduler: fix flaky test

---

OWNERS
OWNERS_ALIASES

remove inactive approve to smooth review process

---

pkg/scheduler/metrics/metrics.go
pkg/scheduler/plugins/reservation/controller/controller.go
pkg/scheduler/plugins/reservation/controller/controller_test.go

fix: https://github.com/koordinator-sh/koordinator/issues/2499

scheduler: add ReservationResourceAllocated metrics in reservation controller

---

cmd/koord-descheduler/app/server.go
cmd/koord-scheduler/app/server.go

cmd: refactor SecureServing.Serve return in scheduler and descheduler

---

pkg/scheduler/plugins/elasticquota/node_handler.go
pkg/scheduler/plugins/elasticquota/quota_handler.go

- handle cache.DeletedFinalStateUnknown event in quota controller handler

scheduler: handle cache.DeletedFinalStateUnknown event in quota controller handler

---

pkg/koordlet/statesinformer/impl/states_nodemetric.go

fix: https://github.com/koordinator-sh/koordinator/issues/2572

koordlet: fix collectMetric() panic when nodeSLO is nil

---

pkg/scheduler/frameworkext/framework_extender.go
pkg/scheduler/frameworkext/framework_extender_test.go
pkg/scheduler/frameworkext/interface.go
pkg/scheduler/frameworkext/reservation_info.go
pkg/scheduler/plugins/reservation/controller/controller_test.go
pkg/scheduler/plugins/reservation/controller/garbage_collection_test.go
pkg/scheduler/plugins/reservation/nominator_test.go
pkg/scheduler/plugins/reservation/plugin.go
pkg/scheduler/plugins/reservation/plugin_benchmark_test.go
pkg/scheduler/plugins/reservation/plugin_test.go
pkg/scheduler/plugins/reservation/reservation_state.go
pkg/scheduler/plugins/reservation/scoring_test.go
pkg/scheduler/plugins/reservation/transformer.go
pkg/scheduler/plugins/reservation/transformer_test.go

- Implement the PreFilter, Filter, BeforePreFilter, AfterPreFilter logic for the reservation pre-allocation.
Fix part of #2150.

scheduler: support pre-allocation filter

---

apis/slo/v1alpha1/nodeslo_types.go
apis/slo/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/slo.koordinator.sh_nodeslos.yaml
pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
pkg/koordlet/pleg/watcher_linux_test.go
pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile_test.go
pkg/koordlet/qosmanager/plugins/sysreconcile/system_config.go
pkg/koordlet/qosmanager/plugins/sysreconcile/system_config_test.go
pkg/koordlet/runtimehooks/runtimehooks_test.go
pkg/koordlet/statesinformer/impl/states_device_unsupported.go
pkg/koordlet/util/system/common.go
pkg/koordlet/util/system/common_linux.go
pkg/koordlet/util/system/core_sched.go
pkg/koordlet/util/system/psi_test.go
pkg/koordlet/util/system/system_file.go
pkg/koordlet/util/system/system_file_test.go
pkg/koordlet/util/system/system_resource.go
pkg/koordlet/util/system/system_resource_test.go
pkg/koordlet/util/system/util_test_tool_test.go
pkg/runtimeproxy/server/docker/utils.go
pkg/slo-controller/nodeslo/nodeslo_cm_event_handler_test.go
pkg/slo-controller/nodeslo/nodeslo_controller_test.go
pkg/util/sloconfig/nodeslo_config.go

- koordlet
- Support enhanced parameters for Group Identity.
- Change the defaults SystemStrategy, only writing sysctl when specified in the slo-controller-config.
- Refine code.

koordlet: support enhanced group identity for gpu

---

apis/configuration/slo_controller_config.go
apis/configuration/zz_generated.deepcopy.go
pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
pkg/slo-controller/noderesource/plugins/util/util.go
pkg/util/resource.go
pkg/util/resource_test.go
pkg/util/sloconfig/colocation_config.go
pkg/util/sloconfig/colocation_config_test.go
pkg/webhook/cm/plugins/sloconfig/colocation_checker_test.go

Support batch resource max limit of nodeCapacity
while configurations exist, use it to limit

manager: support batch resource limit of nodeCapacity

---

pkg/scheduler/plugins/reservation/transformer.go

scheduler: don't invoke SnapshotSharedLister in parallizer

---

apis/extension/schedule_explanation.go
pkg/util/transformer/pod_transformer.go
pkg/util/transformer/pod_transformer_test.go

scheduler: add questionedObjectKet and topologyKeyToExplain

---

pkg/koordlet/statesinformer/impl/states_device_linux.go
pkg/koordlet/statesinformer/impl/states_device_linux_test.go

- koordlet: fix typo and update xpu condition/partition
NONE

koordlet: fix typo and update xpu condition/partition

---

pkg/scheduler/frameworkext/framework_extender_factory.go
pkg/scheduler/frameworkext/framework_extender_factory_test.go
pkg/scheduler/frameworkext/schedule_diagnosis.go
pkg/scheduler/frameworkext/schedule_diagnosis_test.go
pkg/scheduler/plugins/coscheduling/core/core.go
pkg/scheduler/plugins/coscheduling/core/core_test.go

scheduler: fill scheduleDiagnosis when pod or gang

---

.github/workflows/release.yml

device-daemon: add release
