koordinator-sh/koordinator

- .github/workflows/ci.yaml
- .github/workflows/license.yml
- Makefile
> 🌱 Better CI pipeline

- pkg/cache/expiration_cache.go
- pkg/cache/expiration_cache_test.go
- pkg/koordlet/resmanager/memory_evict.go
- pkg/koordlet/resmanager/resmanager.go
> 🌱 add expire cache

- examples/runtime-hook-server/koordlet.json
- pkg/runtime-manager/config/config.go
- pkg/runtime-manager/config/config_manager.go
Signed-off-by: pengyang.hpy <honpey@gmail.com>
load hookServer config file from local dir, config file example:
{
"remote-endpoint": "/var/run/koordlet.sock",
"failure-policy": "Ignore",
"runtime-hooks": [
"PreRunPodSandbox"
]
}
> Introduce HookServer config loading from /etc/runtime/hookserver.d/

- go.mod
- pkg/runtime-manager/dispatcher/dispatcher.go
- pkg/runtime-manager/dispatcher/hookclient.go
- pkg/runtime-manager/resource-executor/resource_executor.go
- pkg/runtime-manager/server/cri/criserver.go
- pkg/runtime-manager/server/cri/runtime.go
- pkg/runtime-manager/server/cri/utils.go
- pkg/runtime-manager/server/server.go
- pkg/runtime-manager/server/utils/utils.go
- vendor/google.golang.org/grpc/credentials/insecure/insecure.go
- vendor/modules.txt
Signed-off-by: pengyang.hpy <honpey@gmail.com>
Introduce framwork of RuntimeManager and cri-proxy
1. framework of runtimemanager, including:
server: intercept request from kubelet, and forward request to backend containerd/dockerd
resource-executor: parse intercepted request, genereate request to hook server and do checkpoint
dispatcher: mange hook server client and dispatch hook request to hook server
2. cri-proxy
part of 'server', intercept request from kubelet under containerd scenario
> Introduce framwork of RuntimeManager and cri-proxy

- pkg/koordlet/resmanager/resmanager.go
- pkg/koordlet/resmanager/resmanager_test.go
- pkg/koordlet/resmanager/strategy_util.go
- pkg/util/config.go
- pkg/util/system/resctrl.go
Add unit test for resmanager.go in koordlet
#69 
all checks in action passed
None
> 🌱  add unit test for resmanager

- Makefile
In Go 1.18, using go get to install go binaries is no longer supported, which breaks the go-get-tool step in the Makefile. 
This was originally taken from Kubebuilder, and it looks like the new recommended approach is to simply use go install: https://github.com/kubernetes-sigs/kubebuilder/pull/2486
This PR fixes all build dependencies to use the new method.
> ✨ Remove deprecated go get from Makefile

- pkg/koordlet/resmanager/reason.go
- pkg/koordlet/resmanager/resource_update_executor_test.go
- pkg/koordlet/resmanager/types.go
- pkg/slo-controller/config/config.go
- pkg/slo-controller/config/constants.go
- pkg/slo-controller/nodeslo/nodeslo_controller.go
- pkg/slo-controller/nodeslo/nodeslo_controller_test.go
- pkg/slo-controller/nodeslo/resource_strategy.go
- pkg/slo-controller/nodeslo/resource_strategy_test.go
Signed-off-by: bushuang.gbs <bushuang.gbs@alibaba-inc.com>
fixes #52
> Support cpu burst strategy

- pkg/runtime-manager/resource-executor/cri/container.go
- pkg/runtime-manager/resource-executor/cri/pod.go
- pkg/runtime-manager/resource-executor/cri/utils.go
- pkg/runtime-manager/resource-executor/resource_executor.go
- pkg/runtime-manager/server/cri/criserver.go
- pkg/runtime-manager/server/utils/utils.go
- pkg/runtime-manager/store/manager.go
- pkg/runtime-manager/utils/utils.go
1. parse cri protocol
2. generate hook request to RuntimeHookServer(koordlet)
3. merge response form RuntimeHookServer to cri request which would be transferred to backend containerd/dockerd
4. checkpoint basing on bolt
> Introduce cri request parsing/generate-hook-request/checkpoing logic

- CHANGELOG.md
> 📖  add changelog for v0.3

- .github/workflows/ci.yaml
Add cache for caching dependencies and build outputs to improve staticcheck execution time.
> chore: add cache for staticcheck

- pkg/koordlet/resmanager/memory_evict.go
- pkg/koordlet/resmanager/memory_evict_test.go
resolves https://github.com/koordinator-sh/koordinator/issues/85
> feat(koordlet): support memoryEvictLowerPercent in memory evict

- apis/slo/v1alpha1/nodeslo_types.go
- config/crd/bases/slo.koordinator.sh_nodeslos.yaml
add some range validation for fields.
> 🌱 add validation for CRD

- apis/slo/v1alpha1/nodeslo_types.go
- config/crd/bases/slo.koordinator.sh_nodeslos.yaml
memory.wmark_high should be min(memory.high, memory.limit_in_bytes) * memory.wmark_ratio in desc
fixes #136
> Modify memqos wmark ratio doc desc

- pkg/koordlet/audit/auditor_test.go
- pkg/koordlet/audit/event_logger_test.go
- pkg/koordlet/audit/logger_test.go
- pkg/koordlet/pleg/watcher_linux_test.go
- pkg/koordlet/resmanager/be_reconcile_test.go
- pkg/koordlet/resmanager/cgroup_reconcile_test.go
- pkg/koordlet/resmanager/cpu_burst_test.go
- pkg/koordlet/resmanager/cpu_suppress_test.go
- pkg/koordlet/resmanager/resctrl_reconcile_test.go
- pkg/koordlet/resmanager/resource_update_executor_test.go
- pkg/koordlet/runtimehooks/runtimehooks_test.go
- pkg/runtime/handler/containerd_runtime_test.go
- pkg/runtime/handler/docker_runtime_test.go
- pkg/runtime/runtime_test.go
- pkg/util/container_test.go
- pkg/util/meminfo_test.go
- pkg/util/pod_test.go
- pkg/util/stat_test.go
- pkg/util/system/cgroup_driver_linux_test.go
- pkg/util/system/cgroup_test.go
- pkg/util/system/common_linux_test.go
- pkg/util/system/resctrl_linux_test.go
- pkg/util/system/resctrl_test.go
- pkg/util/system/util_test_tool.go
- pkg/util/system/util_test_tool_test.go
- pkg/util/system/version_test.go
- pkg/util/utils_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
NONE
All tests should continue to pass. No leftover temporary directories when the tests finish.
> test: use `T.TempDir` to create temporary test directory

- docs/proposals/scheduling/20220510-load-aware-scheduling.md
Update resource usage estimation in the scoring algorithm and LoadAwareSchedulingArgs
> update LoadAwareScheduling proposal

- pkg/util/system/util_test_tool.go
Fix a failure of unit tests on mac os (but not fails CI in GitHub Actions).
The issue exists after PR #151 merged.
```bash
$ go test ./pkg/runtime/...
E0519 18:25:43.411020   40030 runtime.go:57] failed to get docker endpoint, error: docker endpoint does not exist
E0519 18:25:43.412342   40030 runtime.go:88] failed to get containerd endpoint, error: containerd endpoint does not exist
E0519 18:25:43.413709   40030 runtime.go:57] failed to get docker endpoint, error: docker endpoint does not exist
E0519 18:25:43.415042   40030 runtime.go:63] failed to create docker runtime handler, error: Unix socket path "/var/folders/wf/0n_kt22d1ld90gfmbq0k8z5c0000gp/T/Test_GetRuntimeHandlertest_have_dockerRuntime_but_need_containerd758888209/001/var/run/docke …
```
> chore: fix test tempdir generation

- .github/workflows/ci.yaml
- codecov.yml
- pkg/util/pod.go
- pkg/util/stat_test.go
enable coverage diff check by adding a `codecov.yaml`
#124 
check if CI fails when coverage diff is low
none
> update codecov configuration

- pkg/koordlet/metricsadvisor/be_collector.go
- pkg/koordlet/metricsadvisor/be_collector_test.go
- pkg/koordlet/metricsadvisor/collector.go
- pkg/util/container.go
- pkg/util/node.go
- pkg/util/stat.go
- pkg/util/stat_test.go
This PR will make metricadvisor be able to collect BE CPU metric.
> koordlet: support collect BE CPU metric

- .github/workflows/ci.yaml
- README.md
Since majority of programmer are using Mac for development, and deploy Koordinator in a Linux environment. So after https://github.com/koordinator-sh/koordinator/pull/151 , I think it's necessary to run github action on multiple environments like MacOS and Linux.
fixes #163
> ci: support running unit test on multiple os

- pkg/runtime-manager/server/cri/criserver.go
- pkg/runtime-manager/server/cri/image.go
- pkg/runtime-manager/server/cri/runtime.go
- pkg/runtime-manager/server/utils/utils.go
for kubelet, when --image-service-endpoint is not set, kubelet would use
the runtime socket as the image-service endpoint.
under kubelet using runtime-manager as remote runtime and image-service not configured scenario :
kubelet xx --container-runtime-endpoint=/var/run/runtime-manager/runtimemanager.sock
runtime-manager should implement image service proxy, otherwise there would be image related errors
as no image-service exists.
runtime-manager just forwards image request to backend containerd tranparently.
> Introduce image service proxy under cri scenario

- pkg/runtime-manager/dispatcher/dispatcher.go
- pkg/runtime-manager/dispatcher/hookclient.go
- pkg/runtime-manager/resource-executor/cri/container.go
- pkg/runtime-manager/resource-executor/cri/pod.go
- pkg/runtime-manager/resource-executor/resource_executor.go
- pkg/runtime-manager/server/cri/criserver.go
- pkg/runtime-manager/server/utils/utils.go
- pkg/runtime-manager/store/manager.go
1. set metaManager as inner class inside store package. other package call store.WritePodSandboxInfo
directly instead of getting a new Metamanager first.
2. resource-executor adapts for the new structed PodSandboxInfo/ContianerInfo
> runtime-manager: refactor codes about store and resource-exectutor

- pkg/features/koordlet_features.go
- pkg/koordlet/resmanager/config.go
- pkg/koordlet/resmanager/cpu_evict.go
- pkg/koordlet/resmanager/cpu_evict_test.go
- pkg/koordlet/resmanager/metrics_query.go
- pkg/koordlet/resmanager/metrics_query_test.go
- pkg/koordlet/resmanager/reason.go
- pkg/koordlet/resmanager/resmanager.go
> koordlet: support cpu evict feature

- pkg/slo-controller/nodemetric/node_event_handler.go
- pkg/slo-controller/nodemetric/node_event_handler_test.go
add unit test for `pkg/slo-controller/nodemetric/node_event_handler.go`
> test: add ut for node_event_handler

- cmd/koordlet/main.go
- examples/nginx/nginx.yaml
- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
- pkg/koordlet/runtimehooks/hooks/hooks.go
- pkg/koordlet/runtimehooks/rule/rule.go
- pkg/koordlet/runtimehooks/runtimehooks.go
- pkg/koordlet/runtimehooks/server/server.go
- pkg/koordlet/statesinformer/register.go
- pkg/koordlet/statesinformer/register_test.go
- pkg/koordlet/statesinformer/states_informer.go
- pkg/koordlet/statesinformer/states_nodeslo.go
- pkg/util/pod.go
Signed-off-by: zwzhang0107 <zuoweizhang@outlook.com>
#154
> add group identity plugin

- apis/slo/v1alpha1/nodeslo_types.go
- apis/slo/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/slo.koordinator.sh_nodeslos.yaml
`CPUEvictThresholdPercent` is no longer in used. This PR would remove it from `NodeSLO.Spec`
fixes #189
> api: remove deprecated field in NodeSLO

- cmd/koord-runtime-proxy/main.go
- go.mod
- go.sum
- pkg/runtimeproxy/server/docker/handler.go
- pkg/runtimeproxy/server/docker/server.go
- pkg/runtimeproxy/server/docker/utils.go
- pkg/runtimeproxy/server/docker/utils_test.go
- pkg/runtimeproxy/server/types/docker_types.go
> feature: support docker proxy

- docs/design-archive/koord-runtime-proxy-design-doc.md
> koord-runtime-proxy: add installation manual

- codecov.yml
- pkg/util/meminfo_test.go
1. update `codecov.yaml`, change PR blocking for project-level coverage into `-2%` (before: `-5%`)
2. add unit tests for meminfo.go
test CI blocking for coverage
> chore: update codecov.yaml

- pkg/runtimeproxy/server/docker/utils.go
- pkg/runtimeproxy/server/docker/utils_test.go
Signed-off-by: cheimu yimo@xiaohongshu.com
In runtime proxy, for Docker backend, the splitLablesAndAnnotations cannot successfully decode annotations.
> Fix bug where runtime proxy cannot decode annotations in Docker config

- pkg/util/cpuinfo.go
- pkg/util/system/lscpu.go
- pkg/util/utils.go
If a string is parsed into an int using strconv.Atoi, and subsequently that int is converted into another integer type of a smaller size, the result can produce unexpected values.
ref #240
> fix: incorrect coversion of an integer

- cmd/koord-runtime-proxy/main.go
Signed-off-by: Cheimu yimo@xiaohongshu.com
Try to clean up runtime proxy endpoint socket file when runtime proxy got unexpected panic
fixes #246
> Add Defer os.Remove before starting runtime proxy server 

- cmd/koord-runtime-proxy/main.go
- pkg/runtimeproxy/server/cri/criserver.go
There might be a situation where runtime-proxy was killed by `SIGKILL` signal. In this case, 
```
defer os.Remove(options.RuntimeProxyEndpoint)
``` 
won't have a chance to be executed. So it's better to re-create socket file before launching runtime-proxy.
None
> refactor: prune socket before launching runtime-proxy

- pkg/runtimeproxy/resexecutor/cri/container.go
- pkg/runtimeproxy/resexecutor/cri/container_test.go
Signed-off-by: Cheimu <xerhoneyfc@gmail.com>
Currently, when write to cache, there is no container id. This pr, for cri scenario will additionally add container id to cache.
> Add container id to container info when store to cache

- pkg/koordlet/audit/auditor.go
> refactor: replace reinvented wheel with `Get()` in standard library

- pkg/koordlet/metricsadvisor/be_collector.go
- pkg/koordlet/metricsadvisor/be_collector_test.go
- pkg/koordlet/metricsadvisor/collector.go
- pkg/util/container.go
- pkg/util/container_test.go
- pkg/util/pod.go
- pkg/util/pod_test.go
- pkg/util/stat.go
- pkg/util/stat_test.go
- pkg/util/system/cgroup_resource.go
- pkg/util/system/cgroup_test.go
change cpuacct.stat to cpuacct.usage
fixes #221
> change cpuacct.stat to cpuacct.usage

- pkg/runtimeproxy/server/docker/handler.go
Signed-off-by: cheimu <yimo@xiaohongshu.com>
Current docker proxy forgot to update hook response's cgroup parent field, so there is no updated information within cache. This pr fix this issue.
> docker-proxy: update podInfo and containerInfo with hook resp cgroupParent

- .github/workflows/ci.yaml
The test of MacOS is too slow. It is recommended that you can test locally when developing:
- `./hack/run-test.sh` to run all unittests
- `./hack/run-test.sh TestXX` to run the specified test
- `./hack/run-test.sh xx.go` to run tests in the xx.go file
> remove macos tests

- .github/workflows/ci.yaml
save some time from building docker images.
> ci: use matrix and cache to speed up the build

- pkg/koordlet/reporter/reporter.go
- pkg/koordlet/reporter/reporter_test.go
- pkg/slo-controller/noderesource/noderesource_controller.go
- pkg/slo-controller/noderesource/noderesource_controller_test.go
Fix the reconciliation of noderesource & reporter when the requested node is deleted.
Node deletion should not be reconciled by noderesource-controller.
link: [how does `controller-runtime` invoke `Reconcile()`](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.12.0/pkg/internal/controller/controller.go#L322)
> bugfix: fix noderesource-controller, reporter reconcile on node deletion

- pkg/koordlet/koordlet.go
- pkg/koordlet/statesinformer/config.go
- pkg/koordlet/statesinformer/config_test.go
- pkg/koordlet/statesinformer/states_informer.go
- pkg/koordlet/statesinformer/states_informer_test.go
- pkg/koordlet/statesinformer/states_node.go
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
> feature: report cpu info to noderesoucetopology

- pkg/koordlet/statesinformer/kubelet_stub.go
- pkg/koordlet/statesinformer/kubelet_stub_test.go
- pkg/koordlet/statesinformer/states_informer.go
- pkg/koordlet/statesinformer/states_informer_test.go
Signed-off-by: 黄金 <heikkihuang@kugou.net>
add read only port support for koordlet.
> feat: add read only port support for koordlet

- apis/extension/node.go
- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
- pkg/koordlet/runtimehooks/rule/rule.go
- pkg/koordlet/runtimehooks/runtimehooks.go
- pkg/koordlet/statesinformer/register.go
- pkg/koordlet/statesinformer/states_informer.go
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
> add cpuset allocator

- pkg/koordlet/runtimehooks/proxyserver/service.go
> add logs for proxy server

- .goreleaser.yaml
This PR would enable CGO when GoReleaser is compiling binaries.
> ci: enable CGO when GoReleaser compiles binaries

- pkg/koordlet/metricsadvisor/collector.go
- pkg/koordlet/reporter/reporter.go
- pkg/koordlet/resmanager/cgroup_reconcile.go
- pkg/koordlet/resmanager/cpu_burst.go
- pkg/koordlet/resmanager/memory_evict.go
improve the log verbosity of koordlet.
For example, when we use Centos 7, we don't expect an error-like log for the cgroup file `cpu.burst_us`, since this file may not exist on OSs other than Anolis OS.
reduce misunderstandings when koordlet is deployed with the default log level
some refactoring may conflict with #328
> improve koordlet log verbosity

- pkg/runtimeproxy/resexecutor/cri/pod.go
- pkg/runtimeproxy/server/docker/server.go
Currently, when proxy restart, the pod uids are not updated to cache, so hooks won't get any information about the id. This PR will add uids when proxy failover
> Add pod uid to pod meta when failover

- pkg/runtimeproxy/dispatcher/hookclient.go
Use the structure as the key of the map instead of string
refer：
https://github.com/golang/groupcache/blob/41bb18bfe9da5321badc438f91158cd790a33aa3/lru/lru.go#L36-L37
> cleanup: Use the structure as the key of the map instead of string

- pkg/koordlet/audit/config.go
- pkg/koordlet/audit/config_test.go
- pkg/koordlet/metriccache/config.go
- pkg/koordlet/metriccache/config_test.go
- pkg/koordlet/metricsadvisor/config.go
- pkg/koordlet/reporter/config_test.go
- pkg/koordlet/resmanager/config.go
- pkg/koordlet/resmanager/config_test.go
- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/config_test.go
- pkg/util/system/config.go
- pkg/util/system/config_test.go
The command parameter styles of koord-scheduler, koord-manager and koord-runtime-proxy basically follow the POSIX-compliant flags style, but the style of koordlet is relatively independent, such as KubeletIPAddr, KubeletSyncIntervalSeconds. This PR would keep them the same.
fixed #206
> style: unify the command parameter style of koordlet

- pkg/runtimeproxy/server/cri/criserver.go
When no hook is registered, the dispatch will return a nil rsp, which will cause panic for UpdateRequest
partly fixes #352 (the panic part)
> [koord-runtime-proxy]: fix panic when no hook registered

- apis/extension/resource.go
- apis/scheduling/config/types.go
- apis/scheduling/config/v1beta2/types.go
- pkg/scheduler/plugins/nodenumaresource/cpu_allocator.go
- pkg/scheduler/plugins/nodenumaresource/cpu_allocator_test.go
- pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
- pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
> koord-scheduler: support CPU exclusive policy

- pkg/runtimeproxy/resexecutor/cri/container.go
- pkg/runtimeproxy/resexecutor/cri/container_test.go
- pkg/runtimeproxy/resexecutor/cri/utils.go
- pkg/runtimeproxy/resexecutor/cri/utils_test.go
- pkg/runtimeproxy/server/docker/handler.go
- pkg/runtimeproxy/server/docker/utils.go
- pkg/runtimeproxy/server/docker/utils_test.go
Signed-off-by: Cheimu <xerhoneyfc@gmail.com>
Requests
* UpdateContainer - docker
* UpdateContainerResources - containerd
try to update container's resources by resources fields within the request. However current implementation directly drop the resources fields, which will block any update operation. This pr fix this problem.
> [koord-runtime-proxy] fix the loss of new updated resources from UpdateContainerResources request

- cmd/koord-scheduler/app/server.go
- cmd/koord-scheduler/main.go
- pkg/scheduler/frameworkext/framework_extender.go
add a framework extender for the koord-scheduler, which enables us to extend the native `frameworkImpl` methods (`RunPreFilterPlugins`, `RunFilterPlugins`, ...)
partially for #188
> add scheduling framework extender

- pkg/koordlet/metricsadvisor/collector.go
initJiffies use command "getconf CLK_TCK" to fetch the clock tick on current host.
However base image `gcr.io/distroless/base:latest` doesn't have this command. So this PR will allow koordlet to use the default value 10ms for jiffies if the command doesn't exist .
> koordlet: refine initJiffies with default value

- docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
There are three changes in this PR:
1. 
```
type DevicesSpec struct {
Items  []Device `json:"items"`
}
```
was removed
2.
`type DevicesStatus struct {}` was renamed to `type DeviceStatus struct {}`
3.
`ID` in `type DeviceInfo struct {}` was changed to `UUID`.
> docs: remove redundant field in Device CRD

- pkg/koordlet/audit/auditor.go
- pkg/koordlet/audit/auditor_test.go
> koordlet: optimize auditor UT with httptest.Server 

- docs/proposals/scheduling/20220701-simple-descheduler-framework.md
This proposal is based on the K8s community's [descheduler](https://github.com/kubernetes-sigs/descheduler) to design and implement the descheduler framework required by the koordinator.
fix #213
> add descheduler framework proposal

- pkg/koordlet/metriccache/api.go
- pkg/koordlet/metriccache/metric_cache.go
- pkg/koordlet/metriccache/metric_cache_test.go
- pkg/koordlet/metriccache/storage_tables.go
- pkg/koordlet/metricsadvisor/collector.go
- pkg/koordlet/metricsadvisor/collector_gpu.go
- pkg/koordlet/metricsadvisor/collector_gpu_test.go
- pkg/koordlet/reporter/reporter.go
- pkg/koordlet/reporter/reporter_test.go
Signed-off-by: 黄金 <huangjin_henan@outlook.com>
add gpu metrics to crd.
fixes #370
> feat: update GPU metrics in NodeMetric CRD

- pkg/koordlet/resmanager/cpu_suppress.go
- pkg/koordlet/resmanager/cpu_suppress_test.go
fix cfsquota to keep with be share pool，（exclude lse pod）
and remove status judgement to keep recover always work
> bugfix: always need to reset cpuset when cpu supress

- apis/extension/node.go
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
- pkg/util/system/cpu_manager_linux.go
- pkg/util/system/cpu_manager_unsupported.go
> feature: report pod alloc of Guaranteed pod and cpu manager policy

- .github/workflows/ci.yaml
- .goreleaser.yaml
- .goreleaser/koord-descheduler.dockerfile
- Makefile
- cmd/koord-descheduler/app/config/config.go
- cmd/koord-descheduler/app/options/configfile.go
- cmd/koord-descheduler/app/options/insecure_serving.go
- cmd/koord-descheduler/app/options/options.go
- cmd/koord-descheduler/app/options/scheme.go
- cmd/koord-descheduler/app/server.go
- cmd/koord-descheduler/main.go
- docker/koord-descheduler.dockerfile
> add koord-descheduler

- apis/extension/scheduling.go
- pkg/scheduler/eventhandlers/reservation_handler.go
- pkg/scheduler/plugins/reservation/garbage_collection.go
- pkg/scheduler/plugins/reservation/garbage_collection_test.go
- pkg/scheduler/plugins/reservation/rcache.go
- pkg/scheduler/plugins/reservation/rpod.go
- pkg/scheduler/plugins/reservation/utils.go
Fix reservation status updating when the plugin failed to patch pod with reservation info.
fixes #429
> fix reservation on pod patch failed

- pkg/scheduler/eventhandlers/reservation_handler.go
- pkg/scheduler/eventhandlers/reservation_handler_test.go
- pkg/scheduler/plugins/reservation/rpod.go
- pkg/scheduler/plugins/reservation/utils_test.go
Fix the event handler for unscheduled reservations in the mutil-scheduler scenario:
1. When multiple schedulers run in the same cluster, unscheduled reservations should only get enqueued for the specified scheduler (according to field `spec.template.spec.schedulerName`).
2. Ignore the deletion of expired reservations which have been existing before the scheduler started.
1. Create reservation objects with different scheduler names.
2. Check the log of the koord-scheduler about event handlers' processing.
3. Unscheduled reservations which specify other schedulers should not get enqueued in the koord-scheduler.
4. When the scheduler starts, no ERROR logs for removing expired reservations.
> fix reservation on mutil-scheduler

- apis/extension/scheduling.go
add some consts for gang scheduling
> api: add Gang api

- apis/extension/node.go
- docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/scheduler/plugins/nodenumaresource/node_numa_info.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
> koord-scheduler: support kubelet cpu manager policy

- pkg/descheduler/controllers/migration/controller.go
> koord-descheduler: release Reservation when PodMigrationJob completes or is deleted

- apis/scheduling/v1alpha1/reservation_types.go
- config/crd/bases/scheduling.koordinator.sh_reservations.yaml
- pkg/scheduler/eventhandlers/reservation_handler.go
- pkg/scheduler/eventhandlers/reservation_handler_test.go
- pkg/scheduler/plugins/reservation/garbage_collection.go
- pkg/scheduler/plugins/reservation/garbage_collection_test.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/rpod.go
Separate basic reservation validation into CRD validation and plugin validation, remove object enqueue validation
fixes #439 
1. use `kubectl create` to create an invalid reservation (e.g. with nil template, nil owner,  empty Owner)
2. check the validation message if the create failed
3. check the reservation status if the create succeeded
> koord-scheduler: improve reservation validation

- pkg/runtimeproxy/server/docker/handler.go
- pkg/runtimeproxy/server/docker/server.go
> bugfix: avoid pod terminating in docker

- docs/proposals/api-machinery/20220707-rename-extended-resource.md
> refactor extended resource with `kubernetes.io` namespace

- .github/workflows/ci.yaml
> ci: rolling back to golangci-lint 1.47.3

- apis/scheduling/v1alpha1/reservation_types.go
- config/crd/bases/scheduling.koordinator.sh_reservations.yaml
- docs/proposals/scheduling/20220609-resource-reservation.md
Update with `allocateOnce` API in Reservation.
#440
> apis: add allocateOnce in reservation

- Makefile
- apis/extension/constants.go
- apis/extension/resource.go
- pkg/koordlet/metricsadvisor/be_collector_test.go
- pkg/koordlet/resmanager/be_reconcile_test.go
- pkg/koordlet/resmanager/cpu_evict_test.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/loadaware/load_aware_test.go
- pkg/slo-controller/noderesource/noderesource.go
- pkg/slo-controller/noderesource/noderesource_controller_test.go
- pkg/slo-controller/noderesource/noderesource_test.go
- pkg/slo-controller/noderesource/resource_calculator.go
- pkg/slo-controller/noderesource/resource_calculator_test.go
- pkg/util/container.go
- pkg/util/pod_test.go
- pkg/webhook/pod/mutating/cluster_colocation_profile.go
- pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
- pkg/webhook/pod/validating/cluster_colocation_profile_test.go
> rename prefix of extended resource

- pkg/koordlet/metricsadvisor/collector_gpu_linux.go
- pkg/koordlet/metricsadvisor/collector_gpu_linux_test.go
- pkg/util/container.go
- pkg/util/container_test.go
Trying to fix security alert reported by CodeQL one by one.
> fix: use uint32 to record process id

- .github/workflows/ci.yaml
> ci: remove cache when setup go

- .github/workflows/codeql.yml
CodeQL is the analysis engine used by developers to automate security checks, and by security researchers to perform variant analysis. 
In CodeQL, code is treated like data. Security vulnerabilities, bugs, and other errors are modeled as queries that can be executed against databases extracted from code. 
This PR  would allow our CI to discover vulnerabilities across a codebase with CodeQL.
> ci: add codeql analysis in workflows

- cmd/koord-scheduler/main.go
- pkg/scheduler/plugins/batchresource/batch_resource.go
- pkg/scheduler/plugins/batchresource/batch_resource_test.go
> add extended resource schedule plugin for compatibility

- go.mod
- go.sum
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/util/system/common_linux.go
- pkg/util/system/common_linux_test.go
- pkg/util/system/common_unsupported.go
- pkg/util/system/cpu_manager_linux.go
- pkg/util/system/cpu_manager_unsupported.go
> feature: support read args from KubeletConfiguration

- apis/extension/scheduling.go
- pkg/scheduler/plugins/reservation/garbage_collection.go
- pkg/scheduler/plugins/reservation/garbage_collection_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/rcache.go
- pkg/scheduler/plugins/reservation/utils.go
Fix stale reservation statuses when pod failed to bind on reserved node or scheduler restarts unexpectedly.
fixes #468 
1. Start the koord-scheduler.
2. Submit an available reservation R.
3. Submit a pod P that allocates reserved resources.
4. Stop the koord-scheduler.
5. Delete the pod P.
6. Restart the koord-scheduler.
7. Wait about 1 minute and verify if the reservation status is corrected.
> koord-scheduler: fix stale reservation status

- pkg/scheduler/eventhandlers/reservation_handler.go
- pkg/scheduler/plugins/reservation/garbage_collection.go
- pkg/scheduler/plugins/reservation/hook.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/rcache.go
- pkg/scheduler/plugins/reservation/utils.go
Reservation supports `allocateOnce`.
Once a pod allocates an available reservation with `allocateOnce` set to true, the reservation will become `Succeeded` and no longer allocatable to other owners.
fixes #440 
1. Submit an available reservation with `allocateOnce` set.
2. Submit a pod A that matches the reservation.
3. Watch the reservation is allocated, and its status becomes `Succeeded`.
4. Submit another pod B that also matches the reservation (if it is available).
5. Check if the reservation is not allocatable to pod B.
> koord-scheduler: reservation support allocateOnce

- .github/workflows/ci.yaml
- Makefile
> ci: use fast-test to skip redundant steps in workflows

- apis/scheduling/v1alpha1/pod_migration_job_types.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/controllers/migration/reservation/interpreter.go
- pkg/descheduler/controllers/migration/reservation/reservation.go
- pkg/descheduler/controllers/migration/reservation/types.go
- pkg/descheduler/controllers/migration/reservation/util.go
> koord-descheduler: enable allocateOnce when creating Reservation

- apis/scheduling/v1alpha1/pod_migration_job_types.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/controllers/migration/reservation/reservation.go
> koord-descheduler: fix incorrect handling of Reservation's status

- cmd/koord-scheduler/app/server.go
- pkg/scheduler/eventhandlers/internal_handler.go
- pkg/scheduler/eventhandlers/reservation_handler.go
- pkg/scheduler/eventhandlers/reservation_handler_test.go
- pkg/scheduler/plugins/reservation/garbage_collection.go
- pkg/scheduler/plugins/reservation/garbage_collection_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/rcache.go
- pkg/scheduler/plugins/reservation/utils.go
1. Fix succeeded reservations' expiration: Succeeded reservations will not become `Failed`, and they will get cleaned up according to their succeeding timestamp.
2. Fix unschedulable reservations' retry: Once a reservation is marked as unschedulable, it will be put into the unschedulable queue and retry in later scheduling cycles.
fixes #499 
For the Fix 1.
1. submit a reservation whose `allocateOnce=true` and  `ttl` is small, then make it get Succeeded
2. check if the reservation would not become Failed
For the Fix 2.
1. submit a reservation that should get unschedulable for some reasons (e.g. request too many resources)
2. check if the scheduled condition timestamp in its status changes by the time
> koord-scheduler: fix succeeded reservation GC and unschedulable retry

- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_helper.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/utils.go
- pkg/util/cpuset.go
- pkg/util/cpuset_test.go
- pkg/util/pod.go
- pkg/util/pod_test.go
- pkg/util/utils.go
- pkg/util/utils_test.go
> refactor: move GeneratePodPatch under util package

- pkg/runtimeproxy/resexecutor/cri/pod.go
- pkg/runtimeproxy/resexecutor/cri/pod_test.go
- pkg/runtimeproxy/store/manager.go
- pkg/runtimeproxy/store/manager_test.go
- pkg/runtimeproxy/utils/utils_test.go
> koord-runtime-proxy: add more test cases

- codecov.yml
- pkg/scheduler/eventhandlers/reservation_handler.go
- pkg/scheduler/eventhandlers/reservation_handler_test.go
- pkg/scheduler/plugins/reservation/garbage_collection.go
- pkg/scheduler/plugins/reservation/hook_test.go
- pkg/scheduler/plugins/reservation/plugin_test.go
1. fix the handler for succeeded reservations in the scheduler cache
2. fix a potential panic when cleanup a reservation cannot get
3. fix typos
4. update codecov.yaml, set `patch` check optional
> koord-scheduler: fix succeeded reservation in scheduler cache

- apis/extension/scheduling.go
- apis/scheduling/v1alpha1/pod_migration_job_types.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
When scheduler assigned the Reservation on the same node as the Pod, Migration controller should stop the job.
> koord-descheduler: stop migration when reserved on the same node

- pkg/koordlet/resmanager/cpu_suppress.go
- pkg/webhook/util/writer/atomic/atomic_writer.go
Signed-off-by: j4ckstraw <j4ckstraw@foxmail.com>
fix https://github.com/koordinator-sh/koordinator/issues/459
> fix: Walkfunc should check the err

- pkg/scheduler/eventhandlers/reservation_handler.go
- pkg/scheduler/eventhandlers/reservation_handler_test.go
- pkg/scheduler/plugins/reservation/garbage_collection.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/utils.go
- pkg/util/utils.go
koord-scheduler: optimize the process after reservation scheduling fails
- Improve the readability of the Reservation scheduling failure message
- Report FailedScheduling Event
- Add UnschedulableQueue first to avoid frequent retry scheduling
fix #530 #528 #534
> koord-scheduler: optimize the process after reservation scheduling fails

- pkg/scheduler/plugins/nodenumaresource/plugin.go
> koord-scheduler: export getDefaultNUMAAllocateStrategy

- pkg/util/container.go
Signed-off-by: huiwq1990 <huiwq1990@163.com>
> fix container cgroup comment

- pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager.go
- pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/pod_eventhandler_test.go
- pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
koord-scheduler: fix CPUTopologyManager get&update race condition
- T1: goroutineA get CPUTopologyOptions and modify
- T1' goroutineB get CPUTopologyOptions, modify and update. 
- T2 then goroutineA updates the modified CPUTopologyOptions, the data that be updated by goroutineB is overridden by goroutineB.
Thanks @ZiMengSheng  report the issue.
> koord-scheduler: fix CPUTopologyManager get&update race condition

- pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
- pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
- pkg/scheduler/plugins/nodenumaresource/cpu_allocation.go
- pkg/scheduler/plugins/nodenumaresource/cpu_allocation_test.go
- pkg/scheduler/plugins/nodenumaresource/cpu_manager.go
In some over-commitment scenario, a logic cpu can be allocated more than once and less than a upper bound. We call the uppder bound “MaxRefCount” and call the number of allocations of a logic cpu “RefCount” of that cpu.
This PR noticed RefCount logic has been partial supported in NodeNUMAResourcePlugin. This PR supports MaxRefCount and makes RefCount logic complete in CPU allocate algorithm.
> koord-scheduler: CPU allocate algorithm supports maxRefCount 

- apis/scheduling/config/types.go
- apis/scheduling/config/v1beta2/types.go
fix the CoeschedulingArgs name and json name
> koord-scheduler: fix coSchedulingArgs json name

- apis/extension/scheduling.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/controllers/migration/reservation/util.go
- pkg/scheduler/plugins/reservation/hook.go
- pkg/scheduler/plugins/reservation/hook_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/rcache.go
The label `scheduling.koordinator.sh/reservation-order` controls the preference logic for Reservation.
The Reservation with lower order is preferred to be selected before Reservation with higher order.
But if it is 0, Reservation will be selected according to the capacity score.
implements #441 
1. create two Reservations with same owner, add label `scheduling.koordinator.sh/reservation-order` with non-zero value on one of the Reservations.
2. create Pod that can match these Reservations.
3. watch the scheduler result. The Reservation has label `scheduling.koordinator.sh/reservation-order` will be selected.
> support Reservation select order

- cmd/koord-descheduler/app/server.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/controllers/migration/controllerfinder/pods_finder.go
- pkg/descheduler/controllers/migration/filter.go
- pkg/descheduler/fieldindex/register.go
1. When evict StatefulSet pod via PodMigrationJob,  koord-descheduler cannot confirm whether the Pod has been migrated successfully since the newly created Pod has the same name. So koord-descheduler should check if the evicting Pod's UID is different from the previous Pod. 
2. Also in the scene,  the logic of check whether the Reservation reserved on same on with Pod is also invalid.
> koord-descheduler: fix failed evict with StatefulSet Pod

- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/rcache.go
fix Reservation Score divide by zero.
1. create a reservation with empty resources as the following:
```yaml
apiVersion: scheduling.koordinator.sh/v1alpha1
kind: Reservation
metadata:
name: test
spec:
allocateOnce: true
owners:
- labelSelector:
matchLabels:
app: test
template:
metadata:
name: test-55859d896f-8dx9c
spec:
containers:
- resources:
limits:
cpu: "0"
memory: "0"
requests:
cpu: "0"
memory: "0"
priority: 9000
priorityClassName: koord-prod
restartPolicy: Always
schedulerName: koord-scheduler
tolerations:
- effect: NoExecute
key: node.kubernetes.io/not-ready
operator: Exists
tolerationSeconds: 300
- effect: NoExecute
key: node.kubernetes.io/unreachable
operator: Exists
tolerationSeconds: 300
ttl: 30m0s
```
2. wait …
> kood-scheduler: fix Reservation Score divide by zero

- docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Update details about compatible existing GPU Pods.
> docs: Update details about compatible existing GPU Pods

- pkg/util/reservation_test.go
add unit tests for reservation utility functions
> test: add tests for reservation utils

- apis/extension/elastic_quota.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
- pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
- pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res_test.go
> add groupQuotaManager

- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/protocol/pod_context.go
- pkg/koordlet/runtimehooks/protocol/protocol.go
- pkg/koordlet/runtimehooks/protocol/protocol_test.go
> koodlet: fix resource in cri proxy response maybe nil for kubelet 1.18

- pkg/util/reservation.go
If multiple goroutines call NewReservePod to build a Reserve Pod for the same Reservation object at the same time, a concurrent map write error will be encountered.
> koord-scheduler: fix Reserve Pod concurrent map write fatal error

- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
1. add unit test for Reservation with `scheduling.koordinator.sh/reservation-order`
2. fix Reservation normalize score
> koord-scheduler: fix Reservation normalize score

- docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
- pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
The koord-scheduler plugin `NodeNUMAResource` supports kubelet reserved CPUs, and these kubelet reserved CPUs are no longer allocated when allocating to prevent CPU stacking.
the correlative PR #592
> koord-scheduler: support kubelet reserved cpus

- cmd/koord-scheduler/app/options/options.go
- cmd/koord-scheduler/app/server.go
- go.mod
- go.sum
- pkg/scheduler/frameworkext/debug_scores.go
- pkg/scheduler/frameworkext/debug_scores_test.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/util/routes/flags.go
koord-scheduler: support debug scores
Users can enable debug scores via flags -s, --debug-scores or set on demand via the following commands:
curl -X PUT leaderSchedulerIP:port/debug/flags/s --data '100'
Users can enable debug scores via flags -s, --debug-scores or set on demand via the following commands:
```bash
curl -X PUT <leaderSchedulerIP>:<port>/debug/flags/s --data '100'
```
and the scheduler will logging the following content with markdown style:
```
| # | Pod | Node | Score | ImageLocality | InterPodAffinity | LoadAwareScheduling | NodeAffinity | NodeNUMAResource | NodeResourcesBalancedAllocation | NodeResourcesFit | PodTopologySpread | Reservation | TaintToleration |
| --- | --- | --- | ---:| ---:| ---:| ---:| ---:| ---:| ---:| …
```
> koord-scheduler: support debug scores

- hack/update-license-header.sh
> feat(deps): bump github.com/lluissm/license-header-checker from 1.3 to 1.4

- pkg/descheduler/controllers/migration/context.go
- pkg/descheduler/controllers/migration/context_test.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/evictor/interpreter.go
- pkg/descheduler/controllers/names/names.go
koord-descheduler: support plugins customize MigrationJob via context
Some plugins need to customize MigrationJob to add some labels and annotations, such as audit PodMigrationJob.
> koord-descheduler: support plugins customize MigrationJob via context

- pkg/koordlet/resmanager/memory_evict_test.go
- pkg/koordlet/resmanager/resmanager.go
koordlet still needs to use Evictv1beta1 for pod eviction, since only 1.22 supports Evictv1.
https://github.com/kubernetes/kubernetes/pull/100724
> koordlet: change evict to v1beta1 for compatible with 1.21-

- pkg/util/kubelet/kubelet.go
When building `KubeletOptions`, koordlet will fail with `kubelet v1.18` because the feature gate `DynamicKubeletConfig` is different between `kubelet v1.18` and `kubelet v1.22`. Now just skip the internal validating  to compatible with `kubelet v1.18`
> koordlet: fix incompatibility with kubelet v1.18 flags

- apis/scheduling/config/types.go
- apis/scheduling/config/v1beta2/defaults.go
- apis/scheduling/config/v1beta2/types.go
- apis/scheduling/config/v1beta2/zz_generated.conversion.go
- apis/scheduling/config/v1beta2/zz_generated.deepcopy.go
- apis/scheduling/config/validation/validation_pluginargs.go
- apis/scheduling/config/zz_generated.deepcopy.go
- cmd/koord-scheduler/main.go
- go.mod
- pkg/scheduler/plugins/elasticquota/candidate.go
- pkg/scheduler/plugins/elasticquota/controller.go
- pkg/scheduler/plugins/elasticquota/controller_test.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
- pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
- pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res_test.go
- pkg/scheduler/plugins/elasticquota/node_handler.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_helper.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
- pkg/scheduler/plugins/elasticquota/pod_handler.go
- pkg/scheduler/plugins/elasticquota/preempt.go
- pkg/scheduler/plugins/elasticquota/quota_handler.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
> koord-scheduler: add elastic quota plugin

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/plugin_service.go
- pkg/scheduler/plugins/coscheduling/plugin_service_test.go
add restful api for coscheduling
> add restful api for coscheduling

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_summary.go
- pkg/scheduler/plugins/coscheduling/plugin_service.go
- pkg/scheduler/plugins/coscheduling/plugin_service_test.go
> koord-scheduler:refine gang restful api for coscheduling

- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_test.go
SchedulingPhase hook can give us the ability to hook the PreFilter&Filter&Score plugins and hook plugin parameter and return value. In some over-commitment scenario, we can use this to give all plugins unified resource view.
We noticed koodinator have support PreFilter&Filter phase hook, but support only one hook each each phase. This PR supports multiple hook each phase and supplies score hook.
> koord-scheduler: support score schedulingPhase hook and multiple hook

- go.mod
- go.sum
koordlet needs to parse kubelet flags and configuration to enhanced compatibility with kubelet, indirectly dependence cadvisor and  github.com/mindprince/gonvml, but govml is not compatible with github.com/NVIDIA/go-nvml. 
We should remove the dependency on github.com/mindprince/gonvml.
fix #630
> koordlet: fix nvml init error

- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/device_cache_test.go
- pkg/scheduler/plugins/deviceshare/device_handler.go
- pkg/scheduler/plugins/deviceshare/device_handler_test.go
- pkg/scheduler/plugins/deviceshare/device_summary.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_service.go
- pkg/scheduler/plugins/deviceshare/plugin_service_test.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/pod_handler_test.go
add restful api for device scheduling plugin to help diagnose problems
> koord-scheduler: add device scheduling debug api

- pkg/scheduler/frameworkext/framework_extender.go
When schedulingPhase hook is registered, we print the registerd hook type info in one log before. But if hook doesn't implement all type hooks, log will lead to nil pointer err.
This pr fix this bug.
> koord-scheduler: fix schedulingPhaseHook registerd log nil pointer bug

- pkg/koordlet/resmanager/be_reconcile.go
- pkg/koordlet/resmanager/cpu_suppress.go
`ResourceUsedThresholdWithBE.Enable` is a switch for the *CPUSuppress* feature. And we generally expect the *BEReconcile* to be enabled by default, and if needed to disable it, we use the feature-gate `BEReconcile`. However, CPUSuppress may conflict with BEReconcile when we set SuppressPolicy as `CPUCfsQuotaPolicy` (both modify the cgroups `cpu.cfs_quota_us`), so the policy is checked in BEReconcile.  
https://github.com/koordinator-sh/koordinator/pull/572
> koordlet: cpu suppress check whether nodeslo enable

- pkg/runtimeproxy/server/cri/criserver.go
- pkg/slo-controller/noderesource/noderesource.go
- pkg/slo-controller/noderesource/noderesource_controller.go
- pkg/slo-controller/nodeslo/resource_strategy.go
Signed-off-by: lucming <2876757716@qq.com>
> just tidy up some logic

- pkg/features/features.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/plugin_helper.go
- pkg/scheduler/plugins/elasticquota/quota_handler.go
- pkg/webhook/add_quota.go
- pkg/webhook/elasticquota/mutating/mutating_handle_test.go
- pkg/webhook/elasticquota/mutating/mutating_handler.go
- pkg/webhook/elasticquota/mutating/webhooks.go
- pkg/webhook/elasticquota/plugin_check_quota_meta_validate.go
- pkg/webhook/elasticquota/pod_check.go
- pkg/webhook/elasticquota/quota_handler.go
- pkg/webhook/elasticquota/quota_topology.go
- pkg/webhook/elasticquota/quota_topology_check.go
- pkg/webhook/elasticquota/quota_topology_test.go
- pkg/webhook/elasticquota/validating/validating_handler.go
- pkg/webhook/elasticquota/validating/validating_handler_test.go
- pkg/webhook/elasticquota/validating/webhooks.go
> koord-manager: add elastic quota webhook

- pkg/slo-controller/noderesource/noderesource.go
- pkg/slo-controller/noderesource/noderesource_test.go
revise the node resource update when calculated values are not int64 type
1. submit a pod which has memory request like `0.1Gi`
2. check the noderesource-controller's log if the batch resources failed to update since the memory value is not valid int64 type
> koord-manager: revise node batch resource update

- pkg/koordlet/metricsadvisor/collector.go
- pkg/koordlet/resmanager/cgroup_reconcile.go
- pkg/koordlet/resmanager/cpu_burst.go
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/protocol/pod_context.go
- pkg/koordlet/runtimehooks/protocol/protocol.go
- pkg/runtimeproxy/resexecutor/cri/utils.go
- pkg/util/pod.go
- pkg/util/pod_qos_utils.go
- pkg/util/pod_qos_utils_test.go
- pkg/util/pod_test.go
unset pod-level and container-level cgroup `cpu.cfs_quota_us` for cpuset pods (qos=LSR/LSE) to avoid unnecessary throttles
fixes #489
> koordlet: unset cfs_quota for LSR/LSE pods

- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
bugfix for the registration of the cpuset runtime hook
fixes #677 
1. do not fail on unit tests
2. run koordlet successfully without panic
> koordlet: fix cpuset hook for unset cfs

- apis/scheduling/config/v1beta2/defaults.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
- pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Change pod's cpu quantity to MilliQuantity in order to calculate runtimeQuota correctly, change memory's format from DecimalSI to BinarySI, fix UT.
> koord-scheduler: modify cpu and memory quantity formats and scales

- pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
- pkg/util/system/system_file.go
- pkg/util/system/system_file_test.go
- pkg/util/system/util_test_tool.go
In some versions of Anolis OS, the Group Identity (bvt) feature is not enabled by default. When coordinator CPUQOS is enabled, we have to enable the feature via sysctl before we write the cgroup files `cpu.bvt_warp_ns`.
```bash
$ # option 1: write system files
$ echo 1 > /proc/sys/kernel/sched_group_identity_enabled
$ # option 2: use sysctl command
$ sysctl -w kernel.sched_group_identity_enabled=1
$ # option 3: use sysctl command and enable group identity persistently
$ sysctl -w kernel.sched_group_identity_enabled=1 >> /etc/sysctl.conf
```
With this patch, koordlet will initialize Group Identity via sysctl when CPUQOS is set and `kernel.sched_group_identity_enabled` exists.
Without this patch, koordlet cannot successfully update the bvt …
> koordlet: enable group identity by sysctl when cpu qos enabled

- pkg/scheduler/plugins/deviceshare/pod_handler.go
虽然deviceShare plugin里面确实先处理device，但如果device的crd没有提前安装的话，可能会出现pod的事件先触发的情况，这个pr就是为了修复这种情况。
> koord-scheduler: fix deviceshare onPodAdd when its device is not loaded

- pkg/util/system/common.go
- pkg/util/system/system_file.go
Signed-off-by: denverdino <denverdino@gmail.com>
Fix the error for "io/ioutil" is deprecated
Fix #705
make build
- [Y] I have written necessary docs and comments
- [Y] I have added necessary unit tests and integration tests
- [Y ] All checks passed in `make test`
> Fix #705 for the error of "io/ioutil" is deprecated

- pkg/scheduler/plugins/nodenumaresource/plugin.go
this PR fix NodeNUMAResource plugin allowUseCPUSet and make it more general.
> koord-scheduler: fix nodeNUMAResource allowUseCPUSet

- pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
- pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
this pr fixes NodeNUMAResource sortCPUsByRefCount bug and supply UT for it.
A node has 16 CPUs, and the maxRefCount of CPUTopologyOptions is set to 2, there are 32 CPUs to allocate at this time. After allocating 32C according to the SpreadByPCPUs and FullPCPUsOnly strategies, and then following the SpreadByPCPUs allocation, there should be 16 CPUs left to allocate. But at this time koord-scheduler will report insufficient CPU resources.
> koord-scheduler: fix NodeNUMAResource sortCPUsByRefCount

- pkg/koordlet/pleg/pleg.go
- pkg/koordlet/pleg/watcher.go
- pkg/koordlet/pleg/watcher_other.go
fix pleg ut that watcher is not supported on darwin
fix https://github.com/koordinator-sh/koordinator/pull/702/files imports the failure on darwin
> fix pleg ut for darwin

- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
If there are suitable resources in the cluster but some nodes do not have CPUTopology, the Pod cannot be scheduled.
1. Deploy koordlet on a subset of nodes in a cluster
2. Create a LSR Pod 
3. Pod failed scheduling with the message `running "NodeNUMAResource" filter plugin: node(s) CPU Topology not found`
> koord-scheduler: fix failed scheduling since missing CPUTopology

- apis/extension/elastic_quota.go
- apis/extension/scheduling.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache.go
- pkg/scheduler/plugins/coscheduling/util/gang_helper.go
- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/pod_handler.go
- pkg/scheduler/plugins/deviceshare/utils.go
- pkg/scheduler/plugins/deviceshare/utils_test.go
- pkg/scheduler/plugins/elasticquota/plugin_helper.go
- pkg/webhook/elasticquota/pod_check.go
1、make some functions from func xxx() to var xxx = func()
2、deviceResourceNames -> DeviceResourceNames
3、nvidiaGpuExist -> NvidiaGpuExist and etc.
> koord-scheduler: make Coscheduling/ElasticQuota/DeviceShare plugins more flexible

- pkg/scheduler/plugins/elasticquota/controller.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
- pkg/scheduler/plugins/elasticquota/node_handler.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_service.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
- pkg/scheduler/plugins/elasticquota/pod_handler.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Make groupQuotaManager's hierarchyUpdateLock not exposed， then modify the functions call groupQuotaManager's corresponding functions.
> koord-scheduler: optimize the use of GroupQuotaManager's hierarchyLock

- pkg/koordlet/koordlet.go
fix the Koordlet throw "Can't get node" during during initialization, when guessed driver failed from Cgroup name.
fixes https://github.com/koordinator-sh/koordinator/issues/664
> koordlet: fix throw Can't get node error during initialization

- pkg/koordlet/runtimehooks/hooks/gpu/gpu.go
- pkg/koordlet/runtimehooks/hooks/gpu/gpu_test.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/protocol/protocol_test.go
- pkg/koordlet/runtimehooks/proxyserver/service.go
> bugfix: append origin env when inject gpu env

- apis/slo/v1alpha1/nodeslo_types.go
- config/crd/bases/slo.koordinator.sh_nodeslos.yaml
Fixes the kubebuilder tags of Resctrl QoS to suppress BE pods' cache allocation and memory bandwidth by default.
Currently, the parameters of Resctrl QoS have been set kubebuilder tags `+kubebuilder:default=xxx`, which always sets some values (e.g. 100%) for the corresponding fields in NodeSLO if we do not specify these fields explicitly. This troubles the Resctrl settings for BE pods since when we only specify `ResctrlQOS.Enable=true`, the real default values of BE pods (e.g. 30%) are overwrited.
0. Prepare an Intel bare-metal machine that enables Intel RDT (L3 CAT & MBA) in the kernel command line.
1. Edit `slo-controller-config` and enable `ResctrlQOS` for BE pods.
2. Check `/sys/fs/resctrl/BE/schemata` if the L3 cache allocation and …
> apis: fix resctrl qos defaults

- apis/extension/scheduling.go
gang的函数扩展的时候，漏了func  xxx ->var xxx  = func()。
> koord-scheduler: fix the lack of gang function conversion

- pkg/koordlet/statesinformer/kubelet_stub_test.go
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
Fix for CPU Suppress when koordlet disables *NodeTopologyReport*.
With this patch, nodeResourceTopology will be updated internally even if we set `NodeTopologyReport=false` in the feature-gates. It works when we want to enable CPU Suppress but disable NodeTopologyReport.
May also fixes #730 .
1. Deploy koordinator.
2. Set `BECPUSuppress=true,NodeTopologyReport=false` in the koordlet's feature-gates.
3. Check if CPU Suppress works well.
> koordlet: fix for cpu suppress when node topology reporting disabled

- apis/slo/v1alpha1/nodeslo_types.go
- config/crd/bases/slo.koordinator.sh_nodeslos.yaml
rm kubebuilder default tag in NodeSLO
> koordlet: rm kubebuilder default tag for ResourceThresholdStrategy

- cmd/koord-runtime-proxy/main.go
- cmd/koord-runtime-proxy/options/options.go
- pkg/runtimeproxy/resexecutor/cri/container.go
- pkg/runtimeproxy/resexecutor/cri/container_test.go
- pkg/runtimeproxy/resexecutor/cri/pod.go
- pkg/runtimeproxy/resexecutor/cri/utils.go
- pkg/runtimeproxy/resexecutor/resource_executor.go
- pkg/runtimeproxy/server/cri/criserver.go
- pkg/runtimeproxy/utils/utils.go
If hookserver is deployed as k8s pod, there may exist cycled dependency: If hookserver is updated, the new hookserver pod create CRI request would come to kubelet, runtime-proxy and then hookserver, however, at this time, the previous pod may have exited, which results in calling hookserver timeout. If RuntimeHookConfig.FailurePolicy is configed as FailurePolicyType, such pod hookserver would always be rejected by RuntimeProxy to re-create.
To fix this issue, we introduce annotations to tag pod as hook server. For such tagged pods, runtime-proxy would transfer cri request to backend runtime engine transparently to solve the cycled dependency.
> RuntimeProxy: Support hook server deployed by k8s pod

- go.mod
- go.sum
- pkg/features/koordlet_features.go
- pkg/koordlet/metriccache/api.go
- pkg/koordlet/metriccache/metric_cache.go
- pkg/koordlet/metriccache/metric_cache_test.go
- pkg/koordlet/metriccache/mockmetriccache/mock.go
- pkg/koordlet/metriccache/storage.go
- pkg/koordlet/metriccache/storage_tables.go
- pkg/koordlet/metriccache/storage_test.go
- pkg/koordlet/metricsadvisor/collector.go
- pkg/koordlet/metricsadvisor/config.go
- pkg/koordlet/metricsadvisor/config_test.go
- pkg/koordlet/metricsadvisor/performance_collector_linux.go
- pkg/koordlet/metricsadvisor/performance_collector_linux_test.go
- pkg/koordlet/metricsadvisor/performance_collector_unsupported.go
- pkg/util/container.go
- pkg/util/container_test.go
- pkg/util/perf/perf_linux.go
- pkg/util/perf/perf_linux_test.go
- pkg/util/perf/perf_unsupported.go
- pkg/util/stat.go
- pkg/util/stat_test.go
Signed-off-by: songtao98 <songtao2603060@gmail.com>
This PR is the first part of koordinator interference detection support, which implements CPI metric collect and store feature. Koordlet collects CPI once a minute in a 10 second time window and store it in metric cache on per container level for future usage. 
Other codes will be commited continuously with other PRs.
> koordlet: CPI collector for Interference Detection

- pkg/scheduler/plugins/elasticquota/controller.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
fixes https://github.com/koordinator-sh/koordinator/issues/657
> koord-scheduler: optimize ElasticQuota plugin's update logic

- pkg/util/system/config.go
option(SysRootDir) initialization error, but this variable is also useless, should we keep it?
> fix: error to init option(SysRootDir)

- apis/config/v1alpha1/cluster_colocation_profile_types.go
- config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
The user only wants to use ColocationProfile to change the schedulerName of the Pod. The original required field needs to be changed to optional.
fix #739
> apis: change the required fields in ClusterColocationProfile to optional

- pkg/util/system/common_linux.go
Fix when the kubelet uses tcp6 socks stats_noderesourcetopology fails to calculate node topo.
Error msg: `states_noderesourcetopology.go:302] failed to calculate node topology, err: failed to get Kubeletcommand linee with kubeletPort 10250, err: failed to getPIDd, the port is not used`
After #744, when retrieving kubelet's PID via netstat, koordlet always uses tcp4 socks instead of tcp6 socks, since even if there is no kubelet port set in tcp4, `netstat.TCP6Socks()` can return an empty result with non-error. It makes the koordlet ignores the kubelet port in tcp6 unexpectedly.
> koordlet: fix kubelet pid not found in tcp4 socks

- cmd/koord-runtime-proxy/options/options.go
- config/manager/koordlet.yaml
- pkg/runtimeproxy/resexecutor/cri/container.go
- pkg/runtimeproxy/resexecutor/cri/pod.go
- pkg/runtimeproxy/resexecutor/cri/utils.go
- pkg/runtimeproxy/server/docker/handler.go
- pkg/runtimeproxy/server/types/docker_types.go
> feature: support pod skip runtime hook with specified label

- pkg/koordlet/resmanager/cpu_burst.go
- pkg/koordlet/resmanager/cpu_burst_test.go
The pod has successfully exited, and koordlet still keeps trying to modify the pod and container cgroups, which is not necessary
koordlet will keep writing the cgroup file even though the pod has exited successfully.However, as the pod exits successfully, the associated cgroup file is deleted, so the following error log is always reported.
```shell
I1031 17:42:38.810404 3754286 resource_update_executor.go:137] manager: CPUBurstExecutor, currentResource: &{0xc000ecfcc0 0 kubepods/besteffort/podd7f19c1d-c555-476f-a237-ad4bf3154e2a/989ab9f8388c97628682d96662ab0573c319ddcb2743d7e49765ed8d6baa79ce {cpu.cfs_burst_us cpu/ true 0x3965fa0} {0 0 <nil>} 0x1cbe080 <nil> false}, preResource: <nil>, need update
I1031 17:42:38.810432 3754286 cpu_burst.go:518] update container …
```
> no processing for successfully exited pods

- cmd/koord-scheduler/app/server.go
- pkg/scheduler/frameworkext/controllers.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/plugins/coscheduling/controller/podgroup.go
- pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/elasticquota/controller.go
- pkg/scheduler/plugins/elasticquota/controller_test.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
fixes https://github.com/koordinator-sh/koordinator/issues/762
> koord-scheduler: only allow the leader to initialize controllers

- pkg/scheduler/frameworkext/framework_extender.go
typo: fix typo error in framework_extender.go
> koord-scheduler: fix typo error in framework_extender.go

- pkg/webhook/util/configuration/configuration.go
- pkg/webhook/util/controller/webhook_controller.go
- pkg/webhook/util/util.go
this PR make webhookConfigurationName configurable with env
NONE
> koord-manager: make webhookConfigurationName configurable

- pkg/koordlet/metricsadvisor/performance_collector_linux.go
- pkg/koordlet/metricsadvisor/performance_collector_linux_test.go
- pkg/util/perf/perf_linux.go
- pkg/util/perf/perf_linux_test.go
- pkg/util/perf/perf_unsupported.go
- pkg/util/stat.go
- pkg/util/stat_test.go
Signed-off-by: songtao98 <songtao2603060@gmail.com>
This PR fixes the error occurs at koordlet CPI collector when closing container cgroup files after profiling container CPI. Related error information is shown as below:
> E1102 21:10:28.757191  435643 performance_collector_linux.go:99] close CgroupFd 36, err : bad file descriptor
Previously we need to get one container's cgroup directory file descriptor to call `perf_event_open()` as param `pid`, thus we use struct `PerfCollector` to save that fd after open the cgroup path instead of saving a reference to the `*os.File` it self. It turns out that with golang gc mechanism the `*os.File` gets garbage collected, then the fd gets closed. But at `performance_collector_linux.go` we close that file explicitly again and that leads to the above …
> koordlet: fix cpi collector bad fd err

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
fix the panic when failover, because the child is loaded before the parent.
> koord-scheduler: fix ElasticQuota plugin failover panic

- apis/extension/resource.go
- apis/extension/resource_test.go
Add an annotation protocol for passing extended resource spec throughout CRI.
Currently, the CRI server cannot get the original pod spec but a calculated linux resource configuration derived from native resources (i.e. `CPU` and `Memory`). So the koordlet runtime hooks have no way to calculate Batch pods' `cpu.cfs_quota_us`, `cpu.shares` `memory.limit_in_bytes`, since Batch pods only specify extended resources.
With this patch, the extended cpu and memory resource requirements of Batch pods will be passed via the pod annotation, allowing the runtime hooks and other components to calculate correct `cpu.cfs_quota_us`, `cpu.shares` `memory.limit_in_bytes` for Batch pods.
Partially for #717.
> api: pass extended resource spec via annotation

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
SystemQuotaInfo and DefaultQuotaInfo should not appear in runtimeQuotaCalculator.
> koord-scheduler: exclude DefaultQuota and SystemQuota when updating quota tree

- apis/extension/resource.go
- apis/extension/resource_test.go
- pkg/webhook/pod/mutating/cluster_colocation_profile.go
- pkg/webhook/pod/mutating/extended_resource_spec.go
- pkg/webhook/pod/mutating/extended_resource_spec_test.go
- pkg/webhook/pod/mutating/mutating_handler.go
Update pod mutating webhook to add a pod annotation of extended resource spec.
Partially for #717.
> webhook: pod mutating handler add extended resource spec

- cmd/koordlet/main.go
- pkg/features/koordlet_features.go
- pkg/koordlet/common/reason/reason.go
- pkg/koordlet/common/testutil/k8s.go
- pkg/koordlet/common/types/constants.go
- pkg/koordlet/common/utils/containers.go
- pkg/koordlet/common/utils/pod.go
- pkg/koordlet/config/config.go
- pkg/koordlet/koordlet.go
- pkg/koordlet/qosmanager/config/config.go
- pkg/koordlet/qosmanager/config/config_test.go
- pkg/koordlet/qosmanager/k8s/k8s.go
- pkg/koordlet/qosmanager/manager.go
- pkg/koordlet/qosmanager/manager_test.go
- pkg/koordlet/qosmanager/metricsquery/metrics_query.go
- pkg/koordlet/qosmanager/metricsquery/metrics_query_test.go
- pkg/koordlet/qosmanager/plugins/context.go
- pkg/koordlet/qosmanager/plugins/plugin.go
> QoS Manager Framework

- OWNERS_ALIASES
Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Add FillZpp into approvers alias:
- api-machinery-approvers
- descheduler-approvers
- webhook-approvers
> Add FillZpp into approvers alias

- OWNERS_ALIASES
> Add zwzhang0107 into approvers alias

- pkg/koordlet/statesinformer/config.go
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
fix #815 , add flag to support disable querying kubelet configuration.  
This is a short-term workaround. I will remove this flag after thinking of a better solution.
> koordlet: add flag to support disable querying kubelet configuration

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
When deleting QuotaGroup, the pod in the QuotaGroup will be moved to defaultQuota, while the background loop will move the defaultQuota to another quotaGroup. The two processes only have readLock constraints, it will result in some errors. So this PR will change the readLock to writeLock to fix the problem. 
As the migrate operation is low-frequency, the writeLock will not influence the performance.
> koord-scheduler: fix errors caused by incorrect lock in ElasticQuota

- pkg/descheduler/controllers/migration/evictor/evictor_delete.go
- pkg/descheduler/controllers/migration/evictor/evictor_native.go
- pkg/descheduler/controllers/migration/evictor/interpreter.go
- pkg/descheduler/evictions/evictions.go
- pkg/descheduler/evictions/evictions_test.go
- pkg/descheduler/evictions/utils/utils.go
- pkg/descheduler/framework/plugins/defaultevictor/evictor.go
Find out the server if support eviction subresource and use preferred groupversion.
NONE
- [✅] I have written necessary docs and comments
- [✅] I have added necessary unit tests and integration tests
- [✅] All checks passed in `make test`
> koord-descheduler: evict pod by perferred groupverison

- pkg/scheduler/plugins/elasticquota/plugin.go
查看了抢占UT失败的原因，SystemQuota或者DefaultQuota在测试的两个Quota组Add之后才触发了OnQuotaAdd事件。在重建树的时候，测试的两个quota组的runtimeQuota会被erase，但又没有触发refreshRuntimeQuota的时间，所以runtimeQuota为0。对于UT的解法，先加载SystemQuota以及DefaultQuota，再开始测试。
> koord-scheduler: fix elasticQuota ut fail

- cmd/koord-scheduler/main.go
Maintain plugin list separately for easy expansion.
> koord-scheduler: make initialization scalable

- pkg/scheduler/frameworkext/helper/synced_eventhandler.go
- pkg/scheduler/frameworkext/helper/synced_eventhandler_test.go
- pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/device_handler.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/pod_handler.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/node_handler.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/nodenumaresource/pod_eventhandler.go
- pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
- pkg/scheduler/plugins/reservation/plugin.go
Currently, the existing scheduling plugins of koord-scheduler will construct the internal state data of the plugin based on the data in the Informer, such as which Pods are maintained in NodeNUMAResource and which CPUs are allocated, which Pods are maintained in DeviceShare and which GPU instances are allocated, and so on. These data must be correct, otherwise it may cause problems with the resources allocated during Pod scheduling, or the orchestration results may not meet expectations, which will seriously affect the runtime problems or availability of workloads.
In the current existing code, the EventHandler is registered with the Informer, and the internal state can be constructed after WaitForCacheSync returns, but WaitForCacheSync …
> koord-scheduler: support force sync data from informer

- cmd/koord-manager/main.go
- pkg/slo-controller/nodemetric/nodemetric_controller.go
- pkg/slo-controller/noderesource/noderesource_controller.go
- pkg/slo-controller/nodeslo/nodeslo_controller.go
Simplify the initialization logic of the koord-manager main function to make it more scalable.
> koord-manager: make initialization scalable

- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
- pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource_test.go
- pkg/koordlet/runtimehooks/hooks/batchresource/rule.go
- pkg/koordlet/runtimehooks/hooks/batchresource/rule_test.go
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/protocol/pod_context.go
- pkg/koordlet/runtimehooks/protocol/protocol.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
- pkg/koordlet/runtimehooks/rule/rule.go
- pkg/koordlet/runtimehooks/runtimehooks_test.go
- pkg/util/container.go
- pkg/util/pod.go
- pkg/util/pod_resources_utils.go
- pkg/util/system/cgroup_resource.go
Add a runtime hook plugin named *BatchResource* to apply cpu/memory limitations for batch pods.
It will replace the old BEReconcile reconciler via runtime hook workflow.
fixes #717
> koordlet: add runtime hook plugin batch resource

- pkg/koordlet/executor/resource_update_executor_test.go
- pkg/koordlet/executor/types.go
- pkg/koordlet/executor/types_test.go
- pkg/koordlet/metricsadvisor/be_collector_test.go
- pkg/koordlet/resmanager/cgroup_reconcile.go
- pkg/koordlet/resmanager/cgroup_reconcile_test.go
- pkg/koordlet/resmanager/cpu_burst.go
- pkg/koordlet/resmanager/resctrl_reconcile_test.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
- pkg/util/container.go
- pkg/util/container_test.go
- pkg/util/meminfo_test.go
- pkg/util/pod.go
- pkg/util/pod_test.go
- pkg/util/stat.go
- pkg/util/stat_test.go
- pkg/util/system/cgroup.go
- pkg/util/system/cgroup_resource.go
- pkg/util/system/cgroup_resource_test.go
- pkg/util/system/cgroup_test.go
- pkg/util/system/config.go
- pkg/util/system/config_test.go
- pkg/util/system/resource.go
- pkg/util/system/system_file.go
- pkg/util/system/util_test_tool.go
- pkg/util/system/validator.go
- pkg/util/system/validator_test.go
- pkg/util/system/version.go
- pkg/util/system/version_test.go
Refactor the CgroupResource module. Implement `system.Resource` interface (proposed in #720 ) to support file operations on cgroups-v2.
part of #407
> koordlet: refactor cgroup resource

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_service_test.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Use pod.Namesapce/Name as the key of the QuotaInfo's PodCache instead of pod.Name.
fix #839
> koord-scheduler: ElasticQuota uses Pod Namespace/Name as cache key

- cmd/koord-scheduler/app/server.go
- pkg/scheduler/frameworkext/debug.go
- pkg/scheduler/frameworkext/debug_test.go
- pkg/scheduler/frameworkext/framework_extender.go
this PR solves issue #846
- [] I have written necessary docs and comments
> koord-scheduler: support log filtering failure reasons as needed

- pkg/scheduler/plugins/elasticquota/core/decorator.go
- pkg/scheduler/plugins/elasticquota/node_handler.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/pod_handler.go
- pkg/scheduler/plugins/elasticquota/preempt.go
- pkg/scheduler/plugins/elasticquota/quota_handler.go
ElasticQuota scheduling plugin supports `Decorator` interface to decorate Node, Pod and ElasticQuota as needed. 
For example, if you want to append some additional resources into Node, Pod and ElasticQuota such as GPU Resources or modify Spec by GPU model, you can implement the Decorator interface.
> koord-scheduler: ElasticQuota supports Decorator to decorate Node, Pod and ElasticQuota

- pkg/scheduler/plugins/elasticquota/plugin_test.go
> koord-scheduler: fix quota ut error

- README.md
> docs: add star history into README

- .github/workflows/ci.yaml
- apis/slo/v1alpha1/nodemetric_types.go
- pkg/scheduler/plugins/coscheduling/controller/podgroup.go
- pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/coscheduling/plugin_controller.go
- pkg/scheduler/plugins/coscheduling/plugin_service.go
The PodGroupController could not find the target PodGroup because the PodGroup Informer was not started.
> koord-scheduler: fix PodGroupController init error

- apis/slo/v1alpha1/nodeslo_types.go
- apis/slo/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/slo.koordinator.sh_nodeslos.yaml
- pkg/koordlet/resmanager/cpu_evict.go
- pkg/koordlet/resmanager/cpu_evict_test.go
cpu_evict: make UsageHighEnough configurable
NONE
> koordlet: make UsageHighEnough configurable for cpu_evict

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
1. Coscheduling Plugin checks whether the number of Pods meetes minMember first in Prefilter stage.
2. If  Prefilter failed, return `framework.Error` to force avoid any preemption attempts even `Coscheduling.PostFilter`
fix #874
> koord-scheduler: check whether the number of Pods meets minMember first in Coscheduling

- apis/extension/node.go
- docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Currently `node.koordinator.sh/cpu-bind-policy` only supports `FullPCPUsOnly`, but in some scenarios users want to configure `SpreadByPCPUs` for nodes. PR to implement it.
> koord-scheduler: NodeCPUBindPolicy supports SpreadByPCPUs

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta2/types.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/loadaware/load_aware_test.go
Add `ScoreAccordingProdUsage` in LoadAware scheduling plugin args to control whether to score according to the utilization of Prod Pod and keep the original default score according to node utilization
> koord-scheduler: LoadAware scheduling adds ScoreAccordingProdUsage parameter

- pkg/koordlet/resmanager/cpu_suppress.go
- pkg/koordlet/util/node.go
- pkg/koordlet/util/pod.go
- pkg/koordlet/util/resourceexecutor/executor.go
As the title said, fix print info log when batch update cgroup's values and update some missing comments in util. 
None
> koordlet: fix updateBatch method of executor and update some comments in util

- pkg/koordlet/metricsadvisor/collector.go
- pkg/koordlet/resmanager/cgroup_reconcile.go
- pkg/koordlet/resmanager/cgroup_reconcile_test.go
- pkg/koordlet/resmanager/cpu_burst.go
- pkg/koordlet/resmanager/cpu_burst_test.go
- pkg/koordlet/resmanager/cpu_suppress.go
- pkg/koordlet/resmanager/cpu_suppress_test.go
- pkg/koordlet/resmanager/metrics_query.go
- pkg/koordlet/resmanager/resctrl_reconcile.go
- pkg/koordlet/resmanager/resctrl_reconcile_test.go
- pkg/koordlet/resmanager/resmanager.go
- pkg/koordlet/resourceexecutor/config.go
- pkg/koordlet/resourceexecutor/executor.go
- pkg/koordlet/resourceexecutor/reader.go
- pkg/koordlet/resourceexecutor/resctrl_updater.go
- pkg/koordlet/resourceexecutor/resctrl_updater_test.go
- pkg/koordlet/resourceexecutor/updater.go
- pkg/koordlet/resourceexecutor/updater_test.go
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/koordlet/util/container.go
- pkg/koordlet/util/system/cgroup.go
- pkg/koordlet/util/system/cgroup_resource.go
- pkg/koordlet/util/system/resctrl.go
- pkg/koordlet/util/system/resctrl_test.go
- pkg/koordlet/util/system/resource.go
- pkg/util/cpuset/cpuset.go
CgroupReconcile & RdtResctrl features support cgroups-v2.
The functions `system.NewCommonCgroupResource()` and `resourceexecutor.NewDetailCgroupUpdater()` are added for developing custom cgroup operations.
The logs related to cgroups operations are revised. e.g. the logs for reading non-running pods' cgroups should be more verbose, and logs for writing unsupported cgroup resources should be more verbose.
After #885, #892 and this PR, most of the QoS features in koordlet will be compatible with Linux cgroups-v2. (The remaining features CPUEvict and PerformanceCollector are also assigned.)
part of #407.
> koordlet: Other qos features support cgroups v2

- pkg/features/koordlet_features.go
- pkg/koordlet/metricsadvisor/collector.go
Signed-off-by: songtao98 <songtao2603060@gmail.com>
Feature gate `PerformanceCollector` is deprecated now and is already noticed to the community that we will delete it in version v1.1.0. This PR delete it in source code. 
In the charts file of v1.1.0 I already replace it with `CPICollector`.
> koordlet: delete deprecated featuregate performance collector

- pkg/koordlet/resmanager/cpu_burst.go
1. encapsulating reused logics 
eg:  update CFSQuota of pod, update CFSQuota of Container
this part of logic is used in many places,maybe better to encapsulated as a function
2.  reducing some logic nesting
> koordlet:encapsulating reused logics(updatePodCFSQuota,updateContainerCFSQuota)

- pkg/scheduler/plugins/reservation/hook.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/rcache.go
fix: prefilter hook get stale reservation from indexer
currently prefilter hook of resource reservation will list reservations from informer cache and construct reservationInfo to judge whether the pod match the reservation(https://github.com/koordinator-sh/koordinator/blob/main/pkg/scheduler/plugins/reservation/hook.go#L147):
```
rOnNode, err := indexer.ByIndex(NodeNameIndex, node.Name)
if err != nil {
klog.V(3).InfoS("PreFilterHook failed to list reservations",
"node", node.Name, "index", NodeNameIndex, "err", err)
return
}
klog.V(6).InfoS("PreFilterHook indexer list reservation on node",
"node", node.Name, "count", len(rOnNode))
count := 0
for _, obj := range rOnNode {
r, ok := obj.(*schedulingv1alpha1.Reservation)
if !ok {
klog.V(5).Infof("unable to convert to …
```
> koord-scheduler: retrieve reservationInfo from cache first in preFilter hook

- pkg/koordlet/util/perf/perf_linux.go
Signed-off-by: songtao98 <songtao2603060@gmail.com>
Previously the cpi collector utils has a return value sequence bug, which reverses the sequence of `cycles` and `instructions` , leading that when compute CPI we actually get the reciprocal of it.
> koordlet: fix cpi collector return value sequence

- pkg/scheduler/plugins/reservation/utils.go
- pkg/scheduler/plugins/reservation/utils_test.go
Signed-off-by: KunWuLuan <kunwuluan@gmail.com>
Increase the judgment on port when judging whether the pod matches the reservation.
Now koordinator only judge on resource and owners when judging whether the pod matches the reservation. And remove the ports according to the pods' requirement. (https://github.com/koordinator-sh/koordinator/blob/main/pkg/scheduler/plugins/reservation/hook.go#L240)
By the implementation, reserve ports are created by all reservations on node, so the pod may remove the ports which are reserved by more than one reservation.
If a pod requires ports which are reserved by more than one reservation and its resource requirement can be satisfied by one of the reservations, the pod can be bind to the node. Then this pod will use the ports that are reserved by other …
> koord-scheduler: check if reservation port match the pod

- pkg/webhook/pod/mutating/cluster_colocation_profile.go
- pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
- pkg/webhook/pod/validating/cluster_colocation_profile.go
- pkg/webhook/pod/validating/cluster_colocation_profile_test.go
- pkg/webhook/pod/validating/request_limit_validator.go
fix the validating and mutating logic of webhook for Pod resources
There are some unreasonable constraints on Pod resource descriptions:
1. must set batch-cpu/batch-memory limits
2. must set batch-cpu/batch-memory requests
3. the memory limits and requests must be equal for LS Pods
This PR will fix these unreasonable restrictions and make Koordinator's resource description fit the kubernetes resource semantics. And fix a panic when limits are set but requests are not set.
none
You could create pod like this:
```
apiVersion: v1
kind: Pod
metadata:
name: test
labels:
koordinator.sh/qosClass: LS
spec:
priorityClassName: koord-prod
containers:
- name: test
resources:
limits:
memory: 1Gi
requests:
memory: 256Mi
```
```
apiVersion: v1
kind: Pod …
```
> koord-manager: fix the validating and mutating logic of Pod resources

- pkg/slo-controller/config/constants.go
- pkg/slo-controller/noderesource/noderesource.go
> koord-manager: Fix log print fmt and add an example for slo-controller-config

- pkg/koordlet/audit/config.go
- pkg/koordlet/audit/event_logger.go
1.  add more cli flags for audit log
2. ensure the audit log directory exist
NONE
> koordlet: add more cli flags for audit log and ensure the audit log directory exist

- pkg/koordlet/metricsadvisor/be_collector.go
- pkg/koordlet/resmanager/cpu_suppress.go
- pkg/koordlet/resmanager/cpu_suppress_test.go
- pkg/koordlet/util/node.go
Cpu eviction does not work for cpuset suppress mode with cpu manager static policy, this pr fix it.
fix #871
- Configure kubelet with cpuManagerPolicy: static
- Configure koordinator's resource-threshold-config with:
```
resource-threshold-config: |
{
"clusterStrategy": {
"enable": true,
"cpuSuppressThresholdPercent": 40,
"memoryEvictThresholdPercent": 70,
"cpuEvictBESatisfactionUpperPercent": 80,
"cpuEvictBESatisfactionLowerPercent": 60,
"cpuEvictBEUsageThresholdPercent": 40,
"cpuEvictTimeWindowSeconds": 1
},
}
```
- Create a be pod: pod1 on a K8s node: node1
- Increase the node1's cpu usage until pod1 is evicted
> koordlet: support cpu eviction in cpuset supress mode with cpu static policy

- pkg/koordlet/koordlet.go
- pkg/koordlet/metrics/common.go
- pkg/koordlet/metrics/metrics.go
- pkg/koordlet/metrics/metrics_test.go
- pkg/koordlet/metrics/resource_summary.go
- pkg/koordlet/metricsadvisor/collector.go
- pkg/koordlet/metricsadvisor/collector_test.go
- pkg/koordlet/metricsadvisor/performance_collector_linux_test.go
- pkg/koordlet/resmanager/cpu_suppress.go
- pkg/koordlet/resmanager/resmanager.go
- pkg/koordlet/resmanager/resmanager_test.go
- pkg/koordlet/statesinformer/config_test.go
- pkg/koordlet/statesinformer/states_node.go
- pkg/koordlet/statesinformer/states_node_test.go
- pkg/koordlet/statesinformer/states_pods.go
- pkg/koordlet/statesinformer/states_pods_test.go
- pkg/util/resource.go
- pkg/util/resource_test.go
Add Prometheus metrics for node's and pod's batch resources, including metrics below:
```bash
koordlet_node_resource_allocatable{resource="kubernetes.io/batch-cpu|kubernetes.io/batch-memory", node=}
koordlet_pod_resource_request{resource="kubernetes.io/batch-cpu|kubernetes.io/batch-memory", node=, pod=, namespace=, container=}
koordlet_pod_resource_limit{resource="kubernetes.io/batch-cpu|kubernetes.io/batch-memory", node=, pod=, namespace=, container=}
```
Fix some spelling errors.
Fix metrics `koordlet_node_used_cpu_cores` and `koordlet_be_suppress_ls_used_cpu_cores`, and use *cores* instead of *milli-cores* as the unit.
> koordlet: add metrics for batch resources

- pkg/scheduler/plugins/elasticquota/pod_handler.go
OnPodDelete need to DecoratePod, otherwise the additional resources will not decrease.
> koord-scheduler: ElasticQuota Plugin need DecoratePod OnPodDelete

- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/quota_info_test.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
Signed-off-by: kingeasternsun <kingeasternsun@gmail.com>
when we get pods that is assigned from quota, we could just return them directly with lock once , instead of lock twice that with first lock we get all pods, with second lock we judge each pod and collect assigned pods.
no
> koord-scheduler:  add new method GetPodIsAssigned to QuotaInfo

- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/evictor/evictor_delete.go
- pkg/descheduler/controllers/migration/evictor/evictor_native.go
- pkg/descheduler/controllers/migration/evictor/interpreter.go
- pkg/descheduler/evictions/evictions.go
- pkg/descheduler/evictions/evictions_test.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
- pkg/descheduler/framework/runtime/framework.go
- pkg/descheduler/framework/types.go
1. Add eviction event with reason/pluginName for Pod during migration.
2. Update eviction metric after eviction
> koord-descheduler: add evict event/metric for Pod during migration

- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
Now reserve pod can be preempt by real pods, but these reserve pods won't be deleted by preemptor because they don't exist on apiserver. It will cause problem when a real pod try to preempt a reserve pod, the real pod will never find the reserve pod being terminated.
> koord-scheduler: protect reserve pod from being preempted

- apis/extension/descheduling.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/util/util.go
- pkg/descheduler/controllers/migration/util/util_test.go
- pkg/descheduler/utils/sorter/pod.go
- pkg/descheduler/utils/sorter/pod_test.go
1. Migration Controller supports filtered Pod that has max eviction cost.
2. PodSorter supports pod deletion cost and eviction cost.
fix #938
> koord-descheduler: support pod deletion cost and eviction cost

- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
some error logs exist, which should be omit.
> koordlet: check key exist first before comparing node topo annotations

- pkg/scheduler/plugins/reservation/hook.go
- pkg/scheduler/plugins/reservation/hook_test.go
- pkg/scheduler/plugins/reservation/rcache.go
Currently, the resource reservation plugin doesn't subtract allocated resources from the reservepod after allocating resources to the pod, which will lead to fewer available resources on the nodes.
For example, a reservation reserved 2c on node and the reservation allocated 1c to pod. In this case available resource on node is `allocated-2c` instead of `allocated-3c`.
> koord-scheduler: remove allocated in filter hook

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta2/defaults.go
- pkg/scheduler/apis/config/v1beta2/types.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
- pkg/scheduler/apis/config/zz_generated.deepcopy.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_helper.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
ElasticQuotaPlugin
1、PreFilter will addtionally check the parent's usedQuota + pod's Request >  parent's runtimeQuota if configured
2、The output of the PreFilter Result just print the map, which is unfriendly for users to read.
> koord-scheduler: additionally check parent's Quota if configured

- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/controllers/migration/controllerfinder/controller_finder.go
- pkg/descheduler/controllers/migration/filter.go
- pkg/descheduler/controllers/migration/util/util.go
1. Support k8s descheduler Pod annotation `descheduler.alpha.kubernetes.io/evict` to skip migration defense strategies.
2. Fix MigrationJob cannot execute when `maxMigratingPerNode=1` and `maxMigratingPerNamespace=1`.
3. Fix not checking `maxUnavailablePerWorkload` when a workload has many unavailable Pods but no migrating Pods
4. Fix did not correctly determine whether the Pod is available, e.g. the Pod is in the Pending state or not Ready
5. Limit some special configuration scenarios for `maxMigratingPerWorkload` and `maxUnavailablePerWorkload`. Reject eviction when `maxMigratingPerWorkload` or `maxUnavailablePerWorkload` equals the expected number of replicas of the workload.
6. When calculating the number of unavailable replicas, round …
> koord-descheduler: optimize the migration defense strategies

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/coscheduling/coscheduling_test.go
- pkg/scheduler/plugins/coscheduling/plugin_service_test.go
- pkg/scheduler/plugins/coscheduling/util/gang_helper.go
fix: deadlock when schedule multi-gang-group
fixes #872
> koord-scheduler: fix Coscheduling resource deadlock with groups

- pkg/scheduler/plugins/elasticquota/core/quota_info.go
Signed-off-by: kingeasternsun <kingeasternsun@gmail.com>
- From the name of function `addPodIfNotPresent`, this function should return early if pod present.
- From the name of function `removePodIfPresent`, this function should return early if pod not present.
> koord-scheduler: optimize ElasticQuota QuotaInfo present methods

- pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
- pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource_test.go
- pkg/koordlet/runtimehooks/protocol/pod_context.go
Fix the batch resource plugin when the BE pod has no label or annotation.
Also, fix some log format errors.
Currently, the batch resource plugin aborts set cgroup resources when a BE pod has no label or annotation since it checks if both of them are non-nil.
> koordlet: fix batch resource plugin for empty label pods

- pkg/slo-controller/config/colocation_cm_event_handler.go
- pkg/slo-controller/config/config.go
- pkg/slo-controller/nodemetric/nodemetric_controller.go
- pkg/slo-controller/noderesource/nodemetric_event_handler.go
- pkg/slo-controller/noderesource/noderesource.go
- pkg/slo-controller/noderesource/noderesource_controller.go
- pkg/slo-controller/noderesource/noderesource_test.go
- pkg/slo-controller/nodeslo/nodeslo_controller.go
revise the slo-controller and fix some bugs:
1. fix the case when a node is deleted but nodeSLO or nodeMetric exists
2. use a copy of the node when updating the node resources to avoid cache pollution
> koord-manager: revise slo-controllers, fix for deleted node

- pkg/koordlet/statesinformer/states_pods.go
Signed-off-by: Wang Xiaoqiang <wangxiaoqiang@qiyi.com>
Clean up one invalid log format:
```
I0118 10:17:58.329530  111031 states_pods.go:274] record pod prometheus metrics successfully, pod koordinator-system%!(EXTRA string=koord-manager-6f579679ff-4m7nj)
```
NONE
> koordlet: clean up log format

- pkg/koordlet/util/cpuinfo_test.go
- pkg/koordlet/util/system/lscpu.go
Fix `lscpu`  get cache info failed  when the cpu has no L3 cache.
> koordlet: fix not support cpu without L3 cache

- pkg/runtimeproxy/server/docker/utils.go
- pkg/runtimeproxy/server/docker/utils_test.go
fix bug: env lost when container's env contains = in its value.
kubectl apply -f nginx.yaml, like this
```yaml
apiVersion: v1
kind: Pod
metadata:
name: nginx
spec:
containers:
- name: nginx
image: nginx
env:
- name: JAVA_OPT_EXT
value: '-Ddubbo.consumer.check=false -Dmtd.account.cache.switch=off'
```
However, this env is not written in the container
> runtimeproxy: fix env lost

- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/pod_handler.go
> koord-scheduler: optimize DeviceShare plugins pod event handler

- pkg/scheduler/plugins/reservation/hook.go
- pkg/scheduler/plugins/reservation/hook_test.go
- pkg/scheduler/plugins/reservation/plugin_test.go
> koord-scheduler: Reservation resolves ReadWriteOncePodAccessMode volume conflict

- pkg/descheduler/apis/config/v1alpha2/defaults.go
koord-descheduler needs to use DefaultInsecureDeschedulerPort(10251)  as the default port of healthz/metrics, but the current implementation uses DefaultDeschedulerPort(10258) , which causes koord-descheduler to fail to start when the bind address of healthz/metrics is not configured.
> koord-descheduler: use DefaultInsecureDeschedulerPort(10251) as healthz/metrics default port

- pkg/runtimeproxy/dispatcher/dispatcher.go
- pkg/runtimeproxy/dispatcher/dispatcher_test.go
Signed-off-by: yuexian <694547990@qq.com>
ref  https://cloud.tencent.com/developer/article/1911289
No
1. stop koordlet,before fix the  bug,it will be panic. because the hookResp which return from Dispatch is not nil,although the real value is nil
2. the return type is interface{}   https://github.com/koordinator-sh/koordinator/blob/ced52523f941978835950bf47b00062434b417d8/pkg/runtimeproxy/dispatcher/dispatcher.go#L68-L69
3. while rsp is nil, but if it return as interface{}, it will not be equal with nil  https://github.com/koordinator-sh/koordinator/blob/ced52523f941978835950bf47b00062434b417d8/pkg/runtimeproxy/dispatcher/dispatcher.go#L88-L89
4. after fix,it will be work fine
#978
> runtimeproxy: fix trap of nil interface{}

- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
- pkg/scheduler/plugins/coscheduling/util/gang_helper.go
Signed-off-by: Syulin7 <735122171@qq.com>
fix a bug in spec.scheduleTimeoutSeconds nil pointer dereference.
Creating a podgroup without setting a spec.scheduleTimeoutSeconds value.
```
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: PodGroup
metadata:
name: gang-example
spec:
minMember: 2
```
and then koord-scheduler will panic.
```
I0129 09:56:43.432556       1 gang_cache.go:69] getGangFromCache create new gang, gang: kubeflow/tfjob-simple
I0129 09:56:43.432563       1 gang_cache.go:202] Create gang by podGroup on add, gangName: kubeflow/tfjob-simple
E0129 09:56:43.432579       1 gang.go:176] podGroup's annotation totalNumber illegal, gangName: kubeflow/tfjob-simple, value:
E0129 09:56:43.432584       1 gang.go:188] podGroup's annotation GangModeAnnotation illegal, …
```
> koord-scheduler:  fix a bug in spec.scheduleTimeoutSeconds nil pointer dereference

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta2/defaults.go
- pkg/scheduler/apis/config/v1beta2/types.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
- pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
- pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
- pkg/scheduler/plugins/loadaware/estimator/types.go
- pkg/scheduler/plugins/loadaware/load_aware.go
LoadAware scheduling plugin is based on the factor estimation algorithm to resolve the problem of scheduling a large number of Pods in cold node scenarios. This algorithm is relatively simple, and needs to be able to customize the estimator to achieve a more accurate estimation mechanism.
Now move the factor estimation algorithm to estimator package as default estimator.
> koord-scheduler: LoadAware supports custom estimator

- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/config_test.go
- pkg/koordlet/runtimehooks/hooks/hooks.go
- pkg/koordlet/runtimehooks/proxyserver/server.go
- pkg/koordlet/runtimehooks/proxyserver/service.go
- pkg/koordlet/runtimehooks/runtimehooks.go
- pkg/koordlet/runtimehooks/runtimehooks_test.go
> koordlet: runtime hook support failpolicy

- cmd/koord-scheduler/app/server.go
- pkg/scheduler/eventhandlers/reservation_handler_test.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- pkg/scheduler/frameworkext/indexer/add_indexer.go
- pkg/scheduler/frameworkext/indexer/reservation.go
- pkg/scheduler/frameworkext/indexer/reservation_test.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/loadaware/load_aware_test.go
- pkg/scheduler/plugins/reservation/garbage_collection.go
- pkg/scheduler/plugins/reservation/hook.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/utils.go
- pkg/scheduler/plugins/reservation/utils_test.go
If there is a new plugin that also starts the reservation informer during initialization, it will cause the reservation plugin to fail to register the indexer internally. The reason is that the k8s scheduling framework does not guarantee that the plugins are initialized in the order of configuration, even if the reservation plugin is configured first.
> koord-scheduler: set Reservation indexer before informer start to avoid error

- pkg/koordlet/statesinformer/states_nodemetric.go
- pkg/koordlet/statesinformer/states_nodemetric_test.go
> style: correct import alias in states_nodemetric

- pkg/koordlet/resmanager/cgroup_reconcile.go
- pkg/util/cache/expiration_cache.go
> koordlet: optimize if-else logics in cgroup reconcile

- apis/extension/scheduling.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
- pkg/scheduler/plugins/coscheduling/util/gang_helper.go
Some users are still using [lightweight-coscheduling](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/kep/2-lightweight-coscheduling/README.md), so require the coscheduling plugin to be compatible with lightweight-coscheduling. PodGroups are not created when the Pod uses the lightweight-coscheduling API.
> koord-scheduler: compatible with lightweight-coscheduling

- apis/extension/scheduling.go
Add extension field in DeviceAllocation to support the DeviceShare plugin in koord-scheduler to custom allocator append custom protocol via DeviceAllocation
> apis: add extension field in DeviceAllocation

- pkg/koordlet/metrics/metrics_test.go
- pkg/koordlet/metrics/psi.go
- pkg/koordlet/metrics/psi_test.go
- pkg/koordlet/metricsadvisor/collector.go
- pkg/koordlet/metricsadvisor/performance_collector_linux.go
- pkg/koordlet/metricsadvisor/performance_collector_linux_test.go
- pkg/koordlet/metricsadvisor/performance_collector_unsupported.go
- pkg/koordlet/resmanager/cpu_burst.go
- pkg/koordlet/resourceexecutor/executor.go
- pkg/koordlet/resourceexecutor/reader.go
- pkg/koordlet/resourceexecutor/reader_test.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/util/container.go
- pkg/koordlet/util/container_test.go
- pkg/koordlet/util/pod.go
- pkg/koordlet/util/stat.go
- pkg/koordlet/util/stat_test.go
- pkg/koordlet/util/system/cgroup.go
- pkg/koordlet/util/system/cgroup_resource.go
- pkg/koordlet/util/system/cgroup_test.go
- pkg/koordlet/util/system/psi.go
- pkg/koordlet/util/system/psi_test.go
PSI,CPI supports cgroups-v2
part of https://github.com/koordinator-sh/koordinator/issues/407
fix:#972
> koordlet: PerformanceCollector supports cgroups-v2

- test/e2e/e2e_test.go
- test/e2e/framework/manifest/manifest.go
- test/e2e/scheduling/nodenumaresource.go
- test/e2e/slocontroller/OWNERS
- test/e2e/slocontroller/batchresource.go
- test/e2e/slocontroller/framework.go
- test/e2e/testing-manifests/embed.go
- test/e2e/testing-manifests/slocontroller/slo-controller-config.yaml
1. Add an e2e case BatchResource for checking the extended resources is correctly updated when colocation is enabled in the slo-controller-config.
2. Fix the typos of package names.
Just run E2E tests.
e.g.
```bash
ginkgo ./test/e2e -- --allowed-not-ready-nodes=5 --system-pods-startup-timeout=10s --e2e-verify-service-account=false
```
> e2e: add an e2e case BatchResource

- apis/extension/deprecated.go
- apis/extension/resource.go
- apis/extension/scheduling_test.go
- docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
- pkg/koordlet/statesinformer/states_device_linux.go
- pkg/koordlet/statesinformer/states_device_linux_test.go
- pkg/koordlet/statesinformer/states_nodemetric.go
- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/device_handler_test.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_service_test.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/pod_handler.go
- pkg/scheduler/plugins/deviceshare/pod_handler_test.go
- pkg/scheduler/plugins/deviceshare/utils.go
- pkg/scheduler/plugins/deviceshare/utils_test.go
- pkg/slo-controller/noderesource/noderesource.go
- pkg/slo-controller/noderesource/noderesource_test.go
The resource names starting with the prefix `kubernetes.io` in k8s are native resource types, and device plugins cannot use these resource names, otherwise the kubelet will reject them.
> apis: deprecated device resource names with prefix kuberenetes.io

- Makefile
- go.mod
- pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
- pkg/koordlet/resmanager/cgroup_reconcile_test.go
- pkg/koordlet/util/container_test.go
- pkg/koordlet/util/pod_test.go
- pkg/koordlet/util/system/cgroup2.go
- pkg/koordlet/util/system/cgroup_driver_linux.go
- pkg/koordlet/util/system/cgroup_driver_unsupported.go
- pkg/koordlet/util/system/cgroup_resource.go
- pkg/koordlet/util/system/util_test_tool.go
Use libcontainer check if the os support cgroupfsv2, and the default value for `system.UseCgroupsV2` maybe change to 
true.
- [] I have added necessary unit tests and integration tests
> koordlet: use libcontainer check cgroupfsv2

- apis/extension/priority.go
- apis/extension/qos.go
- apis/extension/qos_utils.go
- apis/extension/qos_utils_test.go
1. Move QoS utility functions into another file for extensions. (e.g. customize the annotation of pod QoS)
2. Revise some comments in the API package.
> apis: move qos utils for extensions

- apis/extension/resource.go
> apis: correct LabelGPUModel & LabelGPUDriverVersion

- test/e2e/framework/test_context.go
- test/e2e/slocontroller/batchresource.go
Fix the e2e case BatchResource when the namespace and name of the slo-controller-config is customized.
> e2e: fix e2e BatchResource for custom namespace

- pkg/scheduler/plugins/deviceshare/utils.go
Currently, the error message of PreFiltre in DeviceShare plugin cannot be understood intuitively.
This PR will improve the readability.
fix #840
> koord-scheduler: improve the readability of the PreFilter error message of the DeviceShare plugin

- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/evictions/evictions.go
Sometimes I create a PodMigrationJob to migrate one Pod but cannot pass the internal filters, but I known the risk about the migration.
K8s descheduler supports passing filters with Pod which has annotation descheduler.alpha.kubernetes.io/evict,
and koord-descheduler also supports this annotation but unsupports the job. So we should support it.
fixes #1084
> koord-descheduler: allow annotated migrationJob pass filter

- pkg/koordlet/resmanager/cgroup_reconcile.go
- pkg/koordlet/resmanager/cpu_suppress_test.go
- pkg/koordlet/resmanager/system_config_test.go
- pkg/koordlet/resourceexecutor/executor.go
- pkg/koordlet/resourceexecutor/executor_test.go
To avoid memory leaks, require the cache GC to be started when the executor invokes cache updating.
> koordlet: require gc started for cacheable update

- pkg/koordlet/resourceexecutor/reader.go
- pkg/koordlet/resourceexecutor/reader_test.go
- pkg/koordlet/statesinformer/states_nodeslo.go
- pkg/koordlet/statesinformer/states_nodeslo_test.go
- pkg/koordlet/util/system/cgroup.go
- pkg/koordlet/util/system/cgroup2.go
- pkg/koordlet/util/system/cgroup_resource.go
- pkg/util/config.go
- pkg/util/config_test.go
- merge NodeSLOSpec.Extensions when updating nodeSLO
- add general method in koordlet/util, which allows to read NumaStat info in cgroup
> koordlet: merge extensions in nodeslo and add general util methods

- pkg/descheduler/apis/config/types_loadaware.go
- pkg/descheduler/apis/config/v1alpha2/defaults.go
- pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
- pkg/descheduler/utils/anomaly/basic_detector.go
- pkg/descheduler/utils/anomaly/basic_detector_test.go
- pkg/descheduler/utils/anomaly/types.go
LowNodeLoad improves the anomaly condition mechanism and supports the elimination of abnormal states based on consecutiveNormalities. The original mechanism for eliminating abnormal states based on timeout parameters remains unchanged.
fix #1002 
```yaml
apiVersion: descheduler/v1alpha2
kind: DeschedulerConfiguration
deschedulingInterval: 10s
dryRun: true
profiles:
- name: koord-descheduler
plugins:
evict:
enabled:
- name: MigrationController
balance:
enabled:
- name: LowNodeLoad
pluginConfig:
- name: LowNodeLoad
args:
apiVersion: descheduler/v1alpha2
kind: LowNodeLoadArgs
lowThresholds:
cpu: 20
memory: 30
highThresholds:
cpu: 50
memory: 60
evictableNamespaces:
include:
- default
anomalyCondition:
consecutiveAbnormalities: 5
consecutiveNormalities: 3
```
> koord-descheduler: LowNodeLoad eliminates abnormal states based on consecutiveNormalities

- docs/proposals/scheduling/20220701-simple-descheduler-framework.md
- pkg/descheduler/apis/config/types.go
- pkg/descheduler/apis/config/types_pluginargs.go
- pkg/descheduler/apis/config/v1alpha2/default_plugins.go
- pkg/descheduler/apis/config/v1alpha2/defaults.go
- pkg/descheduler/apis/config/v1alpha2/types.go
- pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
- pkg/descheduler/apis/config/zz_generated.deepcopy.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/evict.go
- pkg/descheduler/controllers/migration/filter.go
- pkg/descheduler/framework/plugins/kubernetes/defaultevictor/evictor.go
- pkg/descheduler/framework/plugins/kubernetes/plugin_test.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
- pkg/descheduler/framework/runtime/evictor_proxy.go
- pkg/descheduler/framework/runtime/framework.go
- pkg/descheduler/framework/runtime/framework_test.go
- pkg/descheduler/framework/testing/framework_helpers.go
- pkg/descheduler/framework/types.go
- pkg/descheduler/profile/profile_test.go
In the original implementation of koor-descheduler, the `Evict` extension point is responsible for evicting Pods and providing the `Evicition Filter` function. But in fact, `Evict` and `Filter` are an **orthogonal relationship**. There can only be one evictor in a descheduler (to be precise, there can only be one evictor in a descheduler profile), but there can be multiple eviction filters. The evictor can use these eviction filters. The evictor plugin itself can also implement eviction filters, such as the current PodMigrationJob controller. The PodMigrationJob controller can also continue splitting, using the configured eviction filters.
The original configuration as following:
```yaml
apiVersion: descheduler/v1alpha2
kind: DeschedulerConfiguration
deschedulingInterval: 10s
profiles:
- …
```
> koord-descheduler: support to configure eviction filter separately

- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/controllers/migration/controllerfinder/controller_finder.go
- pkg/descheduler/controllers/migration/filter.go
this PR refactor GetExpectedScaleForPods and variablize controllerfinder.New.
> koord-descheduler: refactor GetExpectedScaleForPod

- .github/workflows/ci.yaml
> ci: fix invalid image tag

- pkg/scheduler/plugins/elasticquota/controller_test.go
- pkg/scheduler/plugins/elasticquota/plugin_helper.go
- pkg/scheduler/plugins/elasticquota/plugin_helper_test.go
- pkg/webhook/elasticquota/pod_check.go
- pkg/webhook/elasticquota/quota_topology_test.go
When users create parent ElasticQuota in namespace and the pod in the namespace cannot be created.
As mentioned in the original [design proposal](https://github.com/koordinator-sh/koordinator/blob/main/docs/proposals/scheduling/20220722-multi-hierarchy-elastic-quota-management.md#compatibility) , if the Pod does not specify a QuotaName, use the Namespace as the QuotaName to find the ElasticQuota, and if there is none, use the default ElasticQuota.
fix #1100 
According to the reproduction method of issue #1100, the correct result expected by users can be achieved.
> koord-manager: fix not compatible with ElasticQuota associated by namespace

- pkg/koordlet/resmanager/cgroup_reconcile.go
- pkg/koordlet/resmanager/cgroup_reconcile_test.go
- pkg/koordlet/resmanager/cpu_burst.go
- pkg/koordlet/resmanager/cpu_suppress.go
- pkg/koordlet/resmanager/system_config.go
- pkg/koordlet/resourceexecutor/cgroup.go
- pkg/koordlet/resourceexecutor/cgroup_test.go
- pkg/koordlet/resourceexecutor/executor_test.go
- pkg/koordlet/resourceexecutor/resctrl_updater.go
- pkg/koordlet/resourceexecutor/updater.go
- pkg/koordlet/resourceexecutor/updater_test.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/protocol/kubeqos_context.go
- pkg/koordlet/runtimehooks/protocol/pod_context.go
- pkg/koordlet/runtimehooks/protocol/protocol.go
- pkg/koordlet/util/system/common.go
- pkg/util/cpuset/cpuset.go
- pkg/util/cpuset/cpuset_test.go
to solve the problem of duplicate audit logs by moving it to the executor module after resource update
fixes #1018
The audit log redundancy issue has been addressed by leveraging the executor's built-in cache, which has changed the recording frequency from 10 seconds to 60 seconds. Meanwhile, the adjustbecpuset policy execution shows frequent CPU rebinding , both klog and audit log will print.
and klog shows here
and i will start a new issue since it looks like we need to modify the function applyCPUSetWithNonePolicy(beCPUSet, oldCPUSet) to improve the stability of CPUs for the BE Group's calculation policy.
> koordlet:move audit log to resource executor after resource update

- apis/extension/elastic_quota.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/plugin_service_test.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
- pkg/webhook/elasticquota/quota_topology_test.go
Fix cannot create ElasticQuota named default in default namespace. 
fix #1108
> koord-scheduler: rename built-in ElasticQuota name

- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_helper.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
In existing implementations, the Pod's Runtime Quota cannot be refreshed in time, resulting in scheduling failure, even if there are a large number of idle Quota. This makes users feel confused.
Now refresh the runtime quota of the Pod's associated Elastic Quota before the PreFilter stage check.
fix #1079 
1. Create an ElasticQuota with min < max
2. Create Pod with the ElasticQuota
3. koord-scheduler immediately schedules Pod successfully
> koord-scheduler: refresh runtime quota before check

- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
- pkg/scheduler/plugins/coscheduling/util/gang_helper.go
1.  Remove the verification of the Gang name defined in the pod.
2. PodGroups are no longer created if pods use Gang annotations.
fix #1099
> koord-scheduler: PodGroups are no longer created if pods use Gang annotations

- pkg/scheduler/plugins/reservation/garbage_collection.go
- pkg/scheduler/plugins/reservation/utils.go
- pkg/scheduler/plugins/reservation/utils_test.go
Allows users to use Reservation to reserve a subset of resources requested by a Pod.
For example, Reservation only reserves 4000m CPU for Pod A, but Pod A applies for 4C and 4Gi memory. Currently, we do not support scenes. This opportunity will cause inconvenience to users and waste reserved resources.
With this PR, users can easily use Reservations to reserve a subset of resources requested by Pods, and Reservations can be used to inject other resources into Pods through webhooks, resources that would otherwise be wasted.
fix #1111 
```bash
$ cat << EOF | kubectl create -f -
apiVersion: scheduling.koordinator.sh/v1alpha1
kind: Reservation
metadata:
generateName: test-
spec:
allocateOnce: true
owners:
- labelSelector:
matchLabels:
app: curlimage
template:
metadata:
name: …
```
> koord-scheduler: allow Reservation to reserve a subset of resources requested by Pod

- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/controllers/migration/controllerfinder/controller_finder.go
- pkg/descheduler/controllers/migration/controllerfinder/pods_finder.go
- pkg/descheduler/controllers/migration/controllerfinder/pods_finder_test.go
- pkg/descheduler/controllers/migration/filter.go
Currently, koord-descheduler only consider replicaset's directly owned pods when filterMaxUnavailableByWorkload. However, replicaset owns to deployment. Koord-descheduler should consider in Deployment Level.
> koord-descheduler: enhanced support for Deployment

- apis/scheduling/v1alpha1/reservation_types.go
- config/crd/bases/scheduling.koordinator.sh_reservations.yaml
Scenarios where the Reservation is released immediately after being used are more common. And using AllocateOnce can also avoid many resource allocation problems. So the default value of AllocateOnce is changed to true
fix #934
> apis: Reservation enables AllocateOnce by default

- apis/slo/v1alpha1/nodeslo_types.go
- config/crd/bases/slo.koordinator.sh_nodeslos.yaml
Modified some code comments to make it easier to understand.
> apis: update some comment

- pkg/scheduler/plugins/elasticquota/plugin.go
ElasticQuota should skip reserve pod in PostFilter phase.  If we don't do this, some resource return logic of the subsequent Reservation will be affected.
> koord-scheduler: ElasticQuota skips reserve pod in PostFilter phase

- apis/extension/node_reservation.go
- apis/extension/node_reservation_test.go
- pkg/koordlet/resmanager/cpu_suppress.go
- pkg/koordlet/resmanager/cpu_suppress_test.go
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/states_noderesourcetopology_test.go
- pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer.go
- pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer_test.go
- pkg/scheduler/plugins/elasticquota/node_handler.go
- pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
- pkg/util/node.go
- pkg/util/node_test.go
support resource reservation from node.annotation.
see this proposal for details: https://github.com/koordinator-sh/koordinator/pull/922
> support node resource reservation

- pkg/scheduler/plugins/deviceshare/allocator.go
- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/device_cache_test.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/utils.go
Enhanced DeviceShare scheduling plugins
- support preempting Devices
1. Create a Pod and apply for all GPUs on a specified node. In the scenario I tested, a node has two GPU instances
```bash
$ cat << EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app: test-reserve-gpu
name: test-gpu-deploy
spec:
progressDeadlineSeconds: 600
replicas: 1
revisionHistoryLimit: 10
selector:
matchLabels:
app: test-reserve-gpu
strategy:
rollingUpdate:
maxSurge: 25%
maxUnavailable: 25%
type: RollingUpdate
template:
metadata:
creationTimestamp: null
labels:
app: test-reserve-gpu
koordinator.sh/qosClass: LS
spec:
containers:
- args:
- "3600"
command:
- sleep
image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
name: test
resources:
limits:
cpu: "1"
memory: …
```
> koord-scheduler: DeviceShare supports preempting devices

- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/evictions/evictions.go
The migrationController in koord-descheduler does not support external created MigrationJob using default mod if the job does not set the spec.Mode. This PR fixes the issue.
> koord-descheduler: fix externally created MigrationJob not using default mode

- apis/extension/descheduling.go
- pkg/descheduler/apis/config/types_pluginargs.go
- pkg/descheduler/controllers/migration/evictor/evictor_soft.go
- pkg/descheduler/controllers/migration/evictor/evictor_soft_test.go
By tagging, the user takes over the eviction.
fixes  https://github.com/koordinator-sh/koordinator/issues/1102
1. Enable this feature in koord-descheduler-config
```yaml
pluginConfig:
- name: MigrationController
args:
apiVersion: descheduler/v1alpha2
kind: MigrationControllerArgs
evictionPolicy: SoftEviction
evictLocalStoragePods: true
ignorePvcPods: true
namespaces:
include:
- qa
evictQPS: "10"
evictBurst: 1
```
2. A annotation will be written on Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
annotations:
scheduling.koordinator.sh/soft-eviction: |-
{
"timestamp": 1679970640,
"deleteOptions": {},
"initiator": "xxx",
"reason": "xxx"
}
```
> koord-descheduler: support soft eviction takeover eviction behavior

- pkg/koordlet/resmanager/resctrl_reconcile.go
- pkg/koordlet/resmanager/resctrl_reconcile_test.go
- pkg/koordlet/resourceexecutor/resctrl_updater.go
- pkg/koordlet/util/cpuinfo.go
- pkg/koordlet/util/system/resctrl.go
- pkg/koordlet/util/system/resctrl_linux.go
- pkg/koordlet/util/system/resctrl_linux_test.go
- pkg/koordlet/util/system/resctrl_test.go
- pkg/koordlet/util/system/resctrl_unsupported.go
The memory bandwidth schema format of resctrl on AMD is different with Intel.
L3 isolation formats are same.
Intel use percentage for MB configuration, however AMD use absolutely value for MB configuration.
We measure the MB extreme limit offline, and convert to absolute value for AMD.
fix #216
> koordlet: support resctrl on AMD

- pkg/koordlet/runtimehooks/hooks/groupidentity/bvt.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
Fix the sysctl initialization of the cgroup identity since the `/proc/sys/kernel/sched_group_identity_enabled` may be not allowed to reset in some versions of the Anolis os.
> koordlet: revise sysctl initialization of the group identity

- pkg/descheduler/controllers/migration/reservation/util.go
- pkg/descheduler/controllers/migration/reservation/util_test.go
The Reservation created by the migrationController of koord-descheduler may be scheduled to the node where the migrated Pod is located. Although this is the most suitable node from the perspective of the scheduler, it is not suitable from the perspective of descheduling. Therefore, when migrating The created Reservation should skip the original node.
When creating a Reservation, skipped terms will be added to each required term in the original Pod.Spec.Affinity.NodeAffinity to ensure that any condition will not be dispatched to the original node.
fix #1114
> koord-descheduler: the reservation created during migration skips the original node

- pkg/scheduler/plugins/reservation/controller/garbage_collection.go
- test/e2e/framework/manifest/manifest.go
- test/e2e/framework/replicaset/rest.go
- test/e2e/framework/replicaset/wait.go
- test/e2e/scheduling/helper.go
- test/e2e/scheduling/reservation.go
- test/e2e/testing-manifests/scheduling/simple-pod-with-reservation.yaml
- test/e2e/testing-manifests/scheduling/simple-reservation.yaml
Add Reservation Scheduling e2e tests, include:
- Basic reservation functionality
- PodTopologySpread with reservation
- PodAntiAffinity with reservation
> e2e: add reservation scheduling e2e tests

- apis/extension/scheduling.go
- pkg/descheduler/controllers/migration/evictor/evictor_soft.go
- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/device_cache_test.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/pod_handler.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/util/utils.go
- pkg/util/utils_test.go
Enhanced DeviceShare scheduling plugin:
- Support reserving device via Reservation.
There are some differences between Device Resource Reservation and other resource processing methods. Other resources, such as CPU/Memory or CPU Core, are continuous, single-dimensional resources. During Pod scheduling, resources reserved by Reservation and the remaining resources on the node can be allocated together. However, Devices such as GPUs are device instances. They are continuous within a single instance, and it is impossible to combine the Device resources reserved by Reservation with the remaining Device resources of the same type on the node. This may lead to fragmentation. However, the current device resource abstraction and resource protocol can only handle this for the time being.
For …
> koord-scheduler: support Reservation reserve devices

- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/pod_handler.go
> koord-scheduler: fix device cache potential concurrency issue

- apis/extension/resource.go
- pkg/scheduler/plugins/nodenumaresource/cpu_accumulator.go
- pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
- pkg/scheduler/plugins/nodenumaresource/cpu_allocation.go
- pkg/scheduler/plugins/nodenumaresource/cpu_allocation_test.go
- pkg/scheduler/plugins/nodenumaresource/cpu_manager.go
- pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager_test.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/pod_eventhandler.go
Enhanced NodeNUMAResource scheduling plugin:
- Support reserving CPUSets through Reservation.  If there are reserved CPUSets through Reservation, the schedule Pod will allocate the reserved CPU Cores first, and then allocate from the remaining available CPU Cores on node.
fix #566
1. Create a Reservation to reserve some CPU cores on a given node with 16 cores
```bash
$ cat << EOF | kubectl create -f -
apiVersion: scheduling.koordinator.sh/v1alpha1
kind: Reservation
metadata:
generateName: test-
spec:
allocateOnce: false
owners:
- labelSelector:
matchLabels:
app: test-app
template:
metadata:
name: curlimage-55859d896f-8dx9c
labels:
koordinator.sh/qosClass: LSR
spec:
containers:
- resources:
limits:
cpu: "4"
requests:
cpu: "4"
priority: 9000
priorityClassName: koord-prod …
```
>     koord-scheduler: support Reservation reserved CPU Cores

- cmd/koordlet/main.go
- cmd/koordlet/options/options.go
- pkg/koordlet/config/config.go
koordlet: improve koordlet profiling and logs.
```
NONE
```
@eahydra @jasonliu747
> koordlet: improve koordlet profiling and logs

- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/device_cache_test.go
- test/e2e/scheduling/helper.go
- test/e2e/scheduling/preemption.go
- test/e2e/scheduling/reservation.go
The pods outside the Reservation cannot preempt pods in Reservation.
fix #1187
> koord-scheduler: fix pods outside the Reservation preempt pods in the Reservation

- .github/workflows/license.yml
> ci: include test folder in license check

- pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
- pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource_test.go
- test/e2e/slocontroller/batchresource.go
1. Fix the koordlet's BatchResource runtime hook which sets the pod-level cfs quota and memory limit as the minimal instead of the unlimited value (i.e. `-1`, `max`) when the batch pod does not set the limits of batch resources.
2. Increase the timeout of the BatchResource e2e test.
fixes #1218.
1. Create a batch pod that does not set the limits of the batch-cpu and batch-memory.
2. Check the pod-level cgroups of the batch pod.
3. Verify if the cpu limit (`cpu.cfs_quota_us` for cgroup v1, while `cpu.max` for cgroup v2) and memory limit (`memory.limit_in_bytes` for v1, while `memory.max` for v2) are set as unlimited values.
> koordlet: fix koordlet batchresource when batch resource limit is not set

- pkg/koordlet/statesinformer/states_noderesourcetopology.go
…notations
Fix https://github.com/koordinator-sh/koordinator/issues/1219
https://github.com/koordinator-sh/koordinator/issues/1219
Just see the koordlet's log, expect that "topology is changed, need sync" is obviously reduced.
> koordlet: reduce the frequency of updating NodeResourceTopology

- pkg/scheduler/plugins/nodenumaresource/cpu_topology_manager_test.go
- pkg/scheduler/plugins/nodenumaresource/topology_eventhandler.go
Users can set annotation `node.koordinator.sh/system-qos-resource` in node to reserve some cpu cores for Pods configured with `System` QoS. koord-scheduler should exclude these reserved CPUs for LSE/LSR Pods when allocating CPU cores.
> koord-scheduler: support System QOS reserved cpus

- apis/extension/node_reservation.go
- docs/proposals/scheduling/20221227-node-resource-reservation.md
- pkg/koordlet/statesinformer/states_noderesourcetopology.go
- pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer.go
- pkg/scheduler/frameworkext/sharedlisterext/node_reservation_transformer_test.go
- pkg/scheduler/plugins/elasticquota/node_handler.go
- pkg/util/node.go
- pkg/util/node_test.go
Add `applyPolicy` to enhance compatibility of Node Resource Reservation with kubelet reservation mechanism.
fix #1216
> apis: Node Resource Reservation supports apply policy

- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
We restore unmatched reusable reservation when allocated > 0 before. In podTopologySpread/interpodaffinity scenario, pod may be allocated zero resource, but it position on node should be honored. We restore unmatched reusable reservation when pods > 0. 
fix #1238
> koord-scheduler: optimize the criteria for whether the Reservation is allocated

- pkg/descheduler/apis/config/types_loadaware.go
- pkg/descheduler/apis/config/v1alpha2/defaults.go
- pkg/descheduler/apis/config/v1alpha2/defaults_test.go
- pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
- pkg/descheduler/apis/config/zz_generated.deepcopy.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
- pkg/descheduler/utils/sorter/pod.go
- pkg/descheduler/utils/sorter/pod_test.go
- pkg/descheduler/utils/sorter/scorer.go
The LowNodeLoad plugin in koord-descheduler supports users to configure different resource weights when calculating the utilization score ranking of Nodes/Pods.
fix #1175
> koord-descheduler: LowNodeLoad supports configuring resourceWeights

- apis/extension/slo_controller_config.go
- apis/slo/v1alpha1/nodeslo_types.go
- go.mod
- pkg/util/sloconfig/config.go
- pkg/util/sloconfig/validator.go
- pkg/util/sloconfig/validator_test.go
- pkg/webhook/cm/plugins/sloconfig/checker.go
- pkg/webhook/cm/plugins/sloconfig/checker_test.go
- pkg/webhook/cm/plugins/sloconfig/colocation_checker.go
- pkg/webhook/cm/plugins/sloconfig/colocation_checker_test.go
- pkg/webhook/cm/plugins/sloconfig/cpu_burst_checker.go
- pkg/webhook/cm/plugins/sloconfig/cpu_burst_checker_test.go
- pkg/webhook/cm/plugins/sloconfig/resource_qos_checker.go
- pkg/webhook/cm/plugins/sloconfig/resource_qos_checker_test.go
- pkg/webhook/cm/plugins/sloconfig/resource_threshold_checker.go
- pkg/webhook/cm/plugins/sloconfig/system_config_checker.go
see https://github.com/koordinator-sh/koordinator/issues/1232
> koord-manager: refactor config validation by github.com/go-playground

- pkg/scheduler/plugins/loadaware/helper.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/loadaware/load_aware_test.go
DaemonSet Pod should be scheduled even if the node's usage exceeds the thresholds
fixes #1229
> koord-scheduler: skip daemonset usageThreshold check

- pkg/koordlet/runtimehooks/hooks/batchresource/rule.go
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/protocol/protocol.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/util/cgroup_parent_utils.go
- pkg/koordlet/util/pod.go
- pkg/koordlet/util/pod_test.go
- pkg/koordlet/util/system/cgroup_driver.go
> koordlet: support sandbox cpuset for rund

- pkg/koordlet/statesinformer/states_nodemetric.go
Compare the `nodeMetric` `metadata.Generation` to improve the nodemetric informer `updateFunc` performance.
```
NONE
```
> koordlet: compare the nodeMetric generation to improve the nodemetric informer updateFunc performance

- cmd/koord-manager/main.go
- pkg/slo-controller/nodemetric/nodemetric_controller.go
- pkg/slo-controller/noderesource/noderesource_controller.go
- pkg/slo-controller/nodeslo/nodeslo_controller.go
Add command options for the common controllers. We can enable/disable the known controllers via the arg `--controllers`.
> koord-manager: add args for common controllers

- pkg/koordlet/util/system/cgroup_driver_linux.go
- pkg/koordlet/util/system/config.go
- pkg/koordlet/util/system/util_test_tool.go
…ault
Fix the koordlet panic when the host path configs are changed.
After #1021, the koordlet panics when the host cgroup path is not correctly configured. However, the check is invoked in `init()` in which the value of the `CgroupRoot` has not been parsed from the command line arguments. So the koordlet always panics when the host cgroup is not mounted at the default path `/host-cgroup`.
> koordlet: fix host cgroup check failed when the config is not the default

- apis/extension/reservation.go
- docs/proposals/scheduling/20220609-resource-reservation.md
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
- pkg/util/reservation/reservation.go
- test/e2e/scheduling/reservation.go
If a pod has an affinity annotation, the pod must be allocated from the reservation, otherwise it stops scheduling.
fix #1256
> koord-scheduler: support select reservation via reservation affinity

- pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
- pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
- pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector_test.go
- pkg/koordlet/pleg/watcher_linux_test.go
> koordlet: fix some unstable ut

- docs/proposals/scheduling/20220513-enhanced-scheduler-extension.md
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
Optimize the signature of the transformer interface.
> koord-scheduler: optimize the signature of the transformer interface

- pkg/runtimeproxy/server/docker/server.go
runtime-proxy: extract annotations from labels for docker
In dockershim，annotations and labels are merged because docker supports only labels.
We should extract annotations from labels for docker in failOver as we do in HandleCreateContainer of RuntimeManagerDockerServer.
None
> runtime-proxy: extract annotations from labels for docker

- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/reservation/plugin.go
Implement EnqueueExtensions to efficiently move unschedulable Pods in internal scheduling queues.
> koord-scheduler: implement EnqueueExtensions

- pkg/scheduler/plugins/deviceshare/pod_handler.go
- pkg/scheduler/plugins/deviceshare/pod_handler_test.go
The master and slave instances of koord-scheduler  both sync pods from api-server via informer and both build nodeDeviceCache with add events. But the slave instance ignore the update event that missed the bound pod by master instance that leaky the pod's deviceAllocations. So if the leader election changed, the slave instance will serve with old states that allocates GPUs that already be allocated for the new Pod.
> koord-scheduler: fix duplicate allocate GPU after leader selection changed

- .licenseignore
- docs/proposals/scheduling/20220513-enhanced-scheduler-extension.md
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/reservation.go
- pkg/scheduler/plugins/reservation/error_channel.go
- pkg/scheduler/plugins/reservation/nominator.go
- pkg/scheduler/plugins/reservation/nominator_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/scoring.go
- pkg/scheduler/plugins/reservation/scoring_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
- pkg/util/reservation/reservation.go
Optimize the flow of restore Reservation from NodeInfo in BeforePreFilter instead of AfterPreFilter.
In the previous implementation, it was necessary to cooperate to modify the scheduling state before and after the PreFilter to ensure the consistency of the data view. The overall performance is relatively poor, and some of the original interfaces cannot help to process data correctly. For example, unmatched reservations are not passed to each plugin, resulting in some data not being corrected, resulting in scheduling results in some scenarios that do not meet expectations.
Now it is optimized to process data concurrently in BeforePreFilter, and removes a lock, which improves the overall performance, and can better coordinate each plugin to process their own internal state.
> koord-scheduler: optimize the flow of restore Reservation

- cmd/koord-manager/main.go
- cmd/koord-manager/options/scheme.go
- config/manager/koordlet.yaml
- pkg/koordlet/util/system/config.go
- pkg/koordlet/util/system/config_test.go
Move the scheme of the koord-manager into options.
Add a host path mount of /run.
> chore: move koord-manager scheme under options, add host run mount

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
PodGroup Spec may changed while scheduler is scheduling gang membe. Scheduler cache should be aware these changes and adjust its scheduling behavior
NONE
> koord-scheduler: coscheduling supports sensing PodGroup changes

- pkg/scheduler/plugins/coscheduling/controller/podgroup.go
- pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
If PodGroup MinMember ==0, scheduler will panic. We fix this bug as a supplement to #1299 
NONE
> koord-scheduler: podgroup support minMember = 0

- cmd/koord-scheduler/app/server.go
- pkg/scheduler/frameworkext/errorhandler_dispatcher.go
- pkg/scheduler/frameworkext/errorhandler_dispatcher_test.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_factory.go
- pkg/scheduler/frameworkext/interface.go
koord-scheduler supports dispatching scheduling error that can give the chance to plugins to process scheduling errors.
> koord-scheduler: support dispatching scheduling error

- apis/extension/operating_pod.go
- apis/extension/reservation.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/deviceshare/reservation_test.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/reservation.go
- pkg/scheduler/plugins/reservation/cache.go
- pkg/scheduler/plugins/reservation/cache_test.go
- pkg/scheduler/plugins/reservation/nominator.go
- pkg/scheduler/plugins/reservation/nominator_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/pod_eventhandler.go
- pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
- pkg/scheduler/plugins/reservation/scoring.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
- pkg/util/reservation/reservation.go
- pkg/util/reservation/reservation_test.go
Supports using real Pods to reserve resources.
- If the Pod has the special label `scheduling.koordinator.sh/operating-mode` and the value is `Reservation`, it means that the purpose of the Pod is to reserve resources.
- Such Pods are collectively called Operating Pods. It can also be allocated from a Reservation CRD, or it can be preempted like a normal Pod.
- Pod whose Operating Mode is `Reservation`, its Reservation allocation policy defaults to `Aligned`, and it is assigned only once.
- Users can set annotation `scheduling.koordinator.sh/reservation-owners` such as `Reservation.Spec.Owners` to indicate which Pods can use resources reserved by real Pods.
- Once the Operating Pod is bound by other Pods, the Operating Pod will be annotated with …
> koord-scheduler: support reserve by pod

- apis/extension/cluster_colocation_profile.go
- pkg/features/features.go
- pkg/webhook/pod/mutating/cluster_colocation_profile.go
- pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
ClusterColocationProfile always modify the resources's request and limits if the Pod matched and is BE QoSClass, but should support skipping modify resources.
fixes #1308
> koord-manager: allow skip update resource 

- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/transformer.go
If the Pod declares the `Reservation Affinity`, it is expected to force allocation from the Reservation. In #1265 , only the PreFilter stage is supported to check whether there are matching Reservations, but it is also necessary to check whether the current node has matching Reservations in the Filter stage, otherwise it may cause the Pod to allocate resources from the node.
> koord-scheduler: fix reservation affinity in filter stage

- pkg/koordlet/resourceexecutor/cgroup.go
- pkg/koordlet/resourceexecutor/config_test.go
- pkg/koordlet/resourceexecutor/executor.go
- pkg/koordlet/resourceexecutor/executor_test.go
- pkg/koordlet/resourceexecutor/updater.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/bvt_test.go
- pkg/koordlet/util/system/system_resource.go
- pkg/koordlet/util/system/system_resource_test.go
- pkg/koordlet/util/system/util_test_tool.go
- Revise the error handling when the cgroup resource update fails because the cgroup is unsupported or the file does not exist.
> koordlet: revise cgroup update err when unsupported or path not exist

- pkg/scheduler/plugins/reservation/pod_eventhandler.go
- pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
The operating pod does not have reservation allocated information, which will lead to failure to release ReservationInfo correctly.
> koord-scheduler: fix leaky operating pod in reservation

- pkg/scheduler/plugins/reservation/service.go
- pkg/scheduler/plugins/reservation/service_test.go
Add new service endpoint `/plugins/Reservation/nodeReservations/:nodeName` to export internal ReservationInfos to help diagnose problems.
For example:
```bash
curl schedulerIP:10251/apis/v1/plugins/Reservation/nodeReservations/test-node-1 | python -m json.tool
{
"items": [
{
"name": "test-d856b5ccd-klg9l",
"namespace": "default",
"uid": "0ef0e287-eb75-4a12-aed6-73ba31ad7851",
"kind": "Reservation",
"available": true,
"allocateOnce": true,
"allocatable": {
"cpu": "4",
"memory": "100Mi"
},
"allocated": {
"cpu": "4",
"memory": "100Mi"
},
"owners": [
{
"labelSelector": {
"matchLabels": {
"app": "test-app"
}
}
}
],
"allocatePolicy": "Aligned",
"assignedPods": [
{
"Namespace": "default",
"Name": "find-cache-pod-5e8255d5-6421-48ff-a7ff-d40f7e97cb87-0",
"UID": …
```
> koord-scheduler: export ReservationInfos via service endpoint

- pkg/koordlet/koordlet.go
- pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
- pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
- pkg/koordlet/metricsadvisor/collectors/podthrottled/pod_throttled_collector_test.go
- pkg/koordlet/util/node.go
- pkg/koordlet/util/pod.go
- pkg/koordlet/util/system/cgroup.go
- pkg/koordlet/util/system/cgroup_driver.go
- pkg/koordlet/util/system/cgroup_driver_linux.go
- pkg/koordlet/util/system/cgroup_driver_linux_test.go
- pkg/koordlet/util/system/config.go
- pkg/koordlet/util/system/version.go
1. Fix the cgroup driver detection when the koordlet pod runs on cgroups-v2.
2. Revise UTs of the metrics advisor where the TSDB might be failed to create because of the local path.
fixes #1346.
> koordlet: fix cgroup driver detection on cgroups-v2, revise UTs

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta2/types.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
The plugin `coscheduling` in koord-scheduler supports skip check schedule cycle to enable more aggressive retry scheduling.
> koord-scheduler: coscheduling supports skipping check schedule cycle

- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/frameworkext/reservation_info_test.go
- pkg/scheduler/plugins/reservation/cache.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/service_test.go
- pkg/scheduler/plugins/reservation/transformer.go
Users create reused Reservation with finalizer, when need to delete Reservation, users first mark Reservation deleting, and clean other resources, then finally remove the finalizer to release Reservation. 
- If the ReservationInfo (both Reservation CRD object and operating Pod)  is terminating, the ReservationInfo cannot be used.
- In assume stage, if the ReservationInfo in cache is terminating, the assume operation will be rejected.
> koord-scheduler: strictly check whether ReservationInfo is available or terminating

- .licenseignore
- pkg/util/histogram/decaying_histogram.go
- pkg/util/histogram/decaying_histogram_test.go
- pkg/util/histogram/histogram.go
- pkg/util/histogram/histogram_checkpoint.go
- pkg/util/histogram/histogram_mock.go
- pkg/util/histogram/histogram_options.go
- pkg/util/histogram/histogram_options_test.go
- pkg/util/histogram/histogram_test.go
Ref to #1361 
This tool comes from [kubernetes/autoscaler](https://github.com/kubernetes/autoscaler), thanks to the open source predecessors.
> add a histogram util

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
- pkg/scheduler/frameworkext/scheduler_adapter.go
- pkg/scheduler/plugins/reservation/cache.go
- pkg/scheduler/plugins/reservation/cache_test.go
- pkg/scheduler/plugins/reservation/eventhandler.go
- pkg/scheduler/plugins/reservation/eventhandler_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/service.go
- pkg/scheduler/plugins/reservation/transformer.go
Part of #1247.
In general scenarios such as reserving CPU/Memory, the existing Reservation allocation information including the concurrent cleaning process of Reserve Pod in NodeInfo is not a problem. However, the port reservation scenario will make this problem more complicated. It is possible that due to concurrency and timing, the port allocated by the Pod may be released incorrectly.
> koord-scheduler: optimize the Reservation deletion process

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/plugins/reservation/service.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/util/hostport.go
- pkg/util/hostport_test.go
- test/e2e/scheduling/hostport.go
fix #1247 : Reservation reserved ports that has been allocated by Pod but incorrectly removed from NdoeInfo if Reservation is deleted.   Now, just remove the unallocated ports in Reservation.
> koord-scheduler: only remove unallocated ports if Reservation released

- pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
- pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector_test.go
- pkg/koordlet/statesinformer/states_nodemetric.go
- pkg/koordlet/statesinformer/states_pods.go
- Fix a bug of the metrics advisor in which the node memory usage in NodeMetric shows as kilo-bytes while the other fields use bytes.
- Add UTs for node resource collector to avoid regression.
- Revise logs and error handling in the states informer.
Fixed the bug in koordlet's node resource collector (introduced in #1316).
> koordlet: fix node memory collection

- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
- test/e2e/scheduling/preemption.go
After the introduction of Reservation, Pods outside the Reservation cannot preempt Pods in the Reservation. In the previous PR, this problem was solved for the Device Share scenario, but for common resources, such as CPU/Memory, this PR can be used to solve it.
fix #1187
1. Create a Reservation reserving all remained CPUs of one Node . 
2. Create a Pod using the Reservation to allocate 4000m CPU.
3. Create a high-priority Pod but does not use the Reservation and try to allocate the node that Reservation reserved.
4. If not using the PR, the high-priority Pod will preempt the Pod that using Reservation, but both of the Pods cannot be scheduled.
5. If using the PR, the high-priority Pod will not preempt the Pod that using Reservation.
More cases see the E2E tests.
> koord-scheduler: enhance the preemption when common resources are reserved

- apis/extension/node_reservation.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/plugins/deviceshare/utils.go
- pkg/scheduler/plugins/reservation/cache.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/util/node.go
Conduct a performance test on the scheduler and find some unnecessary memory overhead and lock conflicts.
> koord-scheduler: eliminate unnecessary memory overhead and lock conflicts

- pkg/slo-controller/nodemetric/nodemetric_controller.go
- pkg/slo-controller/nodeslo/nodeslo_controller.go
This predicate will skip update events that have no change in the object's metadata.generation field. The metadata.generation field of an object is incremented by the API server when writes are made to the spec field of an object. This allows a controller to ignore update events where the spec is unchanged, and only the metadata and/or status fields are changed.
> koord-manager: use GenerationChangedPredicate to prevent unnessary repeated reconcile calls

- pkg/koordlet/prediction/checkpoint.go
- pkg/koordlet/prediction/checkpoint_test.go
- pkg/koordlet/prediction/predict_server.go
- pkg/koordlet/prediction/predict_server_test.go
- pkg/koordlet/prediction/prediction.go
- pkg/koordlet/prediction/prediction_test.go
- pkg/util/histogram/decaying_histogram.go
- pkg/util/histogram/decaying_histogram_test.go
- pkg/util/histogram/histogram.go
- pkg/util/histogram/histogram_test.go
Ref #1361
This PR contains:
Capture Pod/Node utilization data and update it into the model, and provide the ability to query results.
> koordlet: add a resource usage predictserver to estimate long-term reclaimed resource

- pkg/koordlet/config/config.go
- pkg/koordlet/koordlet.go
- pkg/koordlet/prediction/predict_server_test.go
- pkg/koordlet/statesinformer/api.go
- pkg/koordlet/statesinformer/impl/callback_runner.go
- pkg/koordlet/statesinformer/impl/callback_runner_test.go
- pkg/koordlet/statesinformer/impl/config.go
- pkg/koordlet/statesinformer/impl/config_test.go
- pkg/koordlet/statesinformer/impl/extension_utils.go
- pkg/koordlet/statesinformer/impl/kubelet_stub.go
- pkg/koordlet/statesinformer/impl/kubelet_stub_test.go
- pkg/koordlet/statesinformer/impl/registry.go
- pkg/koordlet/statesinformer/impl/states_device_linux.go
- pkg/koordlet/statesinformer/impl/states_device_linux_test.go
- pkg/koordlet/statesinformer/impl/states_device_unsupported.go
- pkg/koordlet/statesinformer/impl/states_informer.go
- pkg/koordlet/statesinformer/impl/states_informer_test.go
- pkg/koordlet/statesinformer/impl/states_node.go
- pkg/koordlet/statesinformer/impl/states_node_test.go
- pkg/koordlet/statesinformer/impl/states_nodemetric.go
- pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
- pkg/koordlet/statesinformer/impl/states_nodeslo.go
- pkg/koordlet/statesinformer/impl/states_nodeslo_test.go
- pkg/koordlet/statesinformer/impl/states_pods.go
- pkg/koordlet/statesinformer/impl/states_pods_test.go
- pkg/koordlet/statesinformer/impl/states_pvc.go
- pkg/koordlet/statesinformer/mockstatesinformer/mock.go
Part of #1361 
Separate the interface and implementation of stateinformer to solve the problem of circular dependency. The current abstraction of stateinformer still has some problems, which will not be resolved for the time being.
> koordlet: refactor statesinformer to solve the circular dependency problem

- apis/extension/resource.go
- apis/extension/slo_controller_config.go
- apis/extension/zz_generated.deepcopy.go
- apis/slo/v1alpha1/nodemetric_types.go
- config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Add apis for node recommendation and Mid tier.
Proposed in #1385.
Part of #1361.
> apis: add Mid tier api

- pkg/koordlet/koordlet.go
- pkg/koordlet/util/system/cgroup_driver.go
- pkg/koordlet/util/system/cgroup_driver_linux.go
- pkg/koordlet/util/system/cgroup_driver_linux_test.go
- pkg/koordlet/util/system/cgroup_driver_unsupported.go
koordlet can not collect psi metrics.
1. kernel with psi feature on
```bash
sudo grubby --update-kernel="/boot/vmlinuz-4.19.91-24.8.an8.x86_64" --args="psi=1 psi_v1=1"
```
`update-kernel` need to be replaced with the actual kernel version
2. open koordlet's feature for collecting psi metrics.
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
name: koordlet
spec:
template:
spec:
containers:
- name: koordlet
image: registry.cn-beijing.aliyuncs.com/koordinator-sh/koordlet:v1.2.0
command:
- /koordlet
args:
- '-cgroup-root-dir=/host-cgroup/'
- >-
-feature-gates=BECPUEvict=true,BEMemoryEvict=true,CgroupReconcile=true,Accelerators=true,CPICollector=true,PSICollector=true
- '-runtime-hooks-host-endpoint=/var/run/koordlet/koordlet.sock'
- '--logtostderr=true'
- '--v=4'
```
3. then we can see …
> koordlet: fix can not collect psi metrics

- pkg/slo-controller/config/colocation_cm_event_handler_test.go
- pkg/slo-controller/noderesource/plugins/midresource/plugin.go
- pkg/slo-controller/noderesource/plugins/midresource/plugin_test.go
- pkg/slo-controller/noderesource/plugins_profile.go
- pkg/slo-controller/noderesource/resource_calculator.go
- pkg/slo-controller/noderesource/resource_calculator_test.go
Add a noderesource plugin in slo-controller for Mid-tier allocatable calculation.
Proposed in #1385.
Part of #1361.
> koord-manager: add noderesource plugin for Mid

- pkg/koordlet/koordlet.go
- pkg/koordlet/prediction/config.go
- pkg/koordlet/prediction/config_test.go
- pkg/koordlet/prediction/peak_predictor.go
- pkg/koordlet/prediction/peak_predictor_test.go
- pkg/koordlet/prediction/predict_server.go
- pkg/koordlet/prediction/predict_server_test.go
- pkg/koordlet/prediction/prediction.go
Part of #1361 
Fill in the configurations that were missing before.
> koordlet: add various configurations to the prediction package

- apis/extension/priority.go
- apis/extension/resource.go
- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta2/defaults.go
- pkg/scheduler/apis/config/v1beta2/types.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/pod_eventhandler.go
Now because there is a better compatibility mechanism compatible with internal already existing Pods, the adaptation code implemented by the NodeNUMAResource plugin can be removed.
And in order to support internal compatible implementations, it is allowed to disable `NodeNUMAResourceArgs.DefaultCPUBindPolicy`.
> koord-scheduler: clean up the adaptation code in NodeNUMAResource

- apis/extension/scheduling.go
- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/utils.go
- pkg/scheduler/plugins/deviceshare/utils_test.go
In order to make it easier to expand and support new resource types, and to better express the supported resource combinations, the Validate and Convert implementations of Request in DeviceShare are refactored.
> koord-scheduler: refactor the implementation of Validate/Convert of request in DeviceShare

- cmd/koord-manager/options/controllers.go
- cmd/koord-manager/options/options.go
- pkg/slo-controller/noderesource/framework/extender_plugin.go
- pkg/slo-controller/noderesource/framework/extender_plugin_test.go
- pkg/slo-controller/noderesource/noderesource_controller.go
- pkg/slo-controller/noderesource/plugins/midresource/plugin.go
- pkg/slo-controller/noderesource/plugins_profile.go
- pkg/slo-controller/noderesource/resource_calculator_test.go
Part of #1361 
Support for user-configurable plugins that controllers need to enable
> koord-controller-manager: noderesource supports configuration plugins

- pkg/koordlet/resmanager/cpu_burst.go
we have definition of share cpu pool which should exclude LSE; while calculate share pool cpu usage, we should exclude LSR. see https://koordinator.sh/zh-Hans/docs/architecture/qos
#1403
> koordlet: exclude LSE from share cpu pool

- pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
- pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
- pkg/scheduler/plugins/loadaware/estimator/types.go
- pkg/scheduler/plugins/loadaware/load_aware.go
Some special oversold mechanisms will adjust Node.Status.Allocatable, and zoom in or out according to the actual situation. The enlarged situation will be special and needs to be evaluated according to the actual total amount of physical resources.
So extend the Estimator in the LoadAware plugin to support custom node.status.allocatable.
> koord-scheduler: load-aware supports estimate node allocatable

- pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
- pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
Pod can only set the requests that caused estimator of load-aware plugin got error results.
fix #1310
> koord-scheduler: load-aware estimates pod that only has requests

- pkg/koordlet/koordlet.go
- pkg/koordlet/koordlet_test.go
- pkg/koordlet/util/system/cgroup_driver.go
- pkg/koordlet/util/system/cgroup_driver_linux.go
- pkg/koordlet/util/system/cgroup_driver_linux_test.go
- pkg/koordlet/util/system/cgroup_resource.go
- pkg/koordlet/util/system/resctrl.go
- pkg/koordlet/util/system/resource.go
- pkg/koordlet/util/system/system_resource.go
- Refactor the cgroup driver setup:
a. Initialize the cgroup driver with the kubepods cgroup names, which is invoked in many pkgs' UTs and takes less than 1s.
b. Move back the cgroup driver detection on kubelet at the daemon's starting, which runs once and can cost at most 60s.
- Delay the check of cgroup support status. Do the check when the method `IsSupported()` is called at the first time.
Fixes the issue in which UTs of each koordlet pkg run for more than 60 seconds.
linked: #1402.
> koordlet: refactor cgroup driver setup and delay resource check

- cmd/koord-scheduler/app/server.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_factory.go
- pkg/scheduler/frameworkext/scheduler_adapter.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/transformer.go
When there is a Reservation on the node, the NodeInfo in the Snapshot will be modified, which requires that the modified NodeInfo in the snapshot be refreshed from the Cache during the next scheduling. The existing implementation is to take over the generation in the snapshot and force it to be set to 0. Although this solves the problem, it will refresh all node data, which leads to serious performance regression.
Because now we can operate the Scheduler.Cache, we can mark the NodeInfo in the Cache as changing by forging the Pod update and delete actions, thereby triggering the update of the Snapshot. In this way, when there is no Reservation, there will be no impact. When there is a Reservation, only update the corresponding node.
In addition, Reservation.PostFilter will modify the …
> koord-scheduler: refresh specific NodeInfos on demand instead of all

- apis/extension/scheduling.go
- docs/proposals/scheduling/20220901-gang-scheduling.md
- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
- pkg/scheduler/plugins/coscheduling/core/gang_summary.go
- pkg/scheduler/plugins/coscheduling/coscheduling_test.go
- pkg/scheduler/plugins/coscheduling/plugin_service_test.go
- pkg/scheduler/plugins/coscheduling/util/gang_helper.go
Expand the logic of determining whether gang is satisfied by "match-policy".
In some specific scenarios, the completed task Pod may not exist. At this time, it is impossible to count the number of completed tasks. In this case, once Gang has been satisfied, all subsequent resource allocations are no longer constrained by Gang rules, which is called once-satisfied, the default gang 'match-policy'.
For GPU topology, all the tasks need to be scheduled at the same time to ensure the best performance, so the gang only consider the number of pods waiting on permit is larger than the min-available, which is called only-waiting. What's more, if the workload support failover, but workload controller can't persist the new gangName or support reconstruct all pods at one-time, only-waiting can help. …
> koord-scheduler: coscheduling support multiple gang match policy

- pkg/descheduler/apis/config/types.go
- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta2/types.go
The component config of koord-scheduler does not need to define json tag, only set in special version.
fix #1431
> chore: remove the tag in internal config as usual

- pkg/descheduler/controllers/migration/util/util.go
- pkg/descheduler/controllers/migration/util/util_test.go
bug fixed
in MigrationControllerArgs maxMigratingPerWorkload percentage parameter does not take effect
run TestGetMaxUnavailable
> koord-descheduler: fix GetMaxUnavailable not properly handling percentage type param

- pkg/descheduler/apis/config/types_pluginargs.go
- pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
- pkg/descheduler/apis/config/zz_generated.deepcopy.go
- pkg/descheduler/controllers/migration/filter.go
When the replicas is 1, I still want to be evicted.
This argument can be used with the SoftEviction policy.
> koord-descheduler: support ignore expected replicas argument

- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/utils.go
- pkg/scheduler/plugins/deviceshare/utils_test.go
The current version requires that `koordinator.sh/gpu-core` must be declared when applying for GPU resources, but `koordinator.sh/gpu-memory`/`koordinator.sh/gpu-memory-ratio` is not mandatory. This method is likely to introduce stability risks and OOM to AI/ML training scenarios.
In this PR, pod must declare `koordinator.sh/gpu-memory`/`koordinator.sh/gpu-memory-ratio`  when applying for GPU
part of #1189
> koord-scheduler: pod must declare gpu-memory or gpu-memory-ratio when applying for GPU

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
- pkg/scheduler/plugins/reservation/cache.go
- pkg/scheduler/plugins/reservation/eventhandler.go
- pkg/scheduler/plugins/reservation/transformer.go
Fix deletion of Reservation in concurrent scenarios. 
When deleting one Reservation, maybe the event handler of plugin `Reservation` got event after the `deleteReservationFromSchedulerCache` in `pkg/scheduler/frameworkext/eventhandlers`, so the deleted ReservationInfo re-added into the ReservationCache.
And optimize the log about reservation to help diagnose.
fix #1436
> koord-scheduler: fix deletion of Reservation in concurrent scenarios

- pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
- pkg/scheduler/plugins/elasticquota/plugin.go
RunDecoratePod should be called in Reserve/Unreserve.
Add more debug logs in getScaleMinQuota.
> koord-scheduler: ElasticQuotaPlugin add RunDecoratePod in Reserve/Unreserve

- cmd/koord-scheduler/app/server.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_factory.go
- pkg/scheduler/frameworkext/framework_extender_factory_test.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- pkg/scheduler/frameworkext/interface.go
Executing plugin transformers in the order of configuration can better handle some special scenarios, such as checking certain conditions before Reservation.BeforePreFilter to end scheduling early.
> koord-scheduler: run plugin transformers in configured order

- apis/extension/priority.go
- apis/extension/priority_utils.go
- apis/extension/qos_utils.go
- pkg/koordlet/resmanager/cgroup_reconcile.go
- pkg/slo-controller/noderesource/noderesource_controller.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
- pkg/slo-controller/noderesource/resource_calculator_test.go
- pkg/util/pod_qos_utils.go
…yclass and qosclass
- koord-manager: revise batch resource calculation, identifying the pods' priorityclasses.
- koord-manager: fix a bug where the `noderesource-plugin` arg allows no plugin by default.
- util: add default PriorityClass and QoSClass when any of them is missing.
Fixes #1441.
> apis: add default PriorityClass and QoSClass, revise batch resource calculation

- apis/scheduling/v1alpha1/device_types.go
- apis/scheduling/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/scheduling.koordinator.sh_devices.yaml
- config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
Some advanced GPUs require allocation according to the combination relationship of ModuleID to obtain the best communication efficiency.
> apis: add moduleID in Device CRD

- pkg/koordlet/prediction/peak_predictor.go
- pkg/koordlet/prediction/peak_predictor_test.go
Ref #1361 
Reclaimable resources come from the prod type.
> koordlet: fix scope of prodReclaimablePredictor resource reclaim

- apis/extension/constants.go
- apis/extension/priority.go
- apis/extension/priority_utils.go
- apis/extension/priority_utils_test.go
- docs/proposals/api-machinery/20230707-add-compatibility-interface-for-priority-class.md
Provide a solution using Koordinator PriorityClass for already running a large number of Pods clusters by adding a label `koordinator.sh/priority-class`.
> apis: add priority-class compatible label

- cmd/koord-manager/main.go
koord-manager: add a leader election resource lock argument.
It is helpful when we want to migrate the leader election lock mode of the deployed koord-manager from the old `configmaps` into new `leases`.
> koord-manager: add leader elect resource lock arg

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
Optimize the error message and logs of Coscheduling plugin.
For example, there are four pods declared PodGroup, and Pod A named `test-6c558d767b-29jbl` failed to scheduling, scheduler will output the following event:
```
Warning  FailedScheduling  2m28s    koord-scheduler  0/4 nodes are available: 4 node(s) didn't match pod anti-affinity rules.  Gang "default/test-gang" gets rejected due to pod is unschedulable. 
```
And the sibling Pod B got the following error while waiting on permit:
```
Warning  FailedScheduling  2m28s (x1 over 2m28s)  koord-scheduler  Gang "default/test-gang" gets rejected due to member Pod "test-6c558d767b-29jbl" is unschedulable with reason "0/4 nodes are available: 4 node(s) didn't match pod anti-affinity rules."  
```
fix #1474
> koord-scheduler: optimize Coscheduling error message and logs

- apis/extension/priority.go
- apis/extension/priority_utils.go
- apis/extension/priority_utils_test.go
- apis/extension/qos_utils.go
- apis/extension/qos_utils_test.go
- pkg/descheduler/utils/sorter/pod.go
- pkg/descheduler/utils/sorter/pod_test.go
- pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector.go
- pkg/koordlet/resmanager/blkio_reconcile.go
- pkg/koordlet/resmanager/cgroup_reconcile.go
- pkg/koordlet/resmanager/cpu_burst.go
- pkg/koordlet/resmanager/cpu_evict.go
- pkg/koordlet/resmanager/cpu_suppress.go
- pkg/koordlet/resmanager/memory_evict.go
- pkg/koordlet/resmanager/resctrl_reconcile.go
- pkg/koordlet/runtimehooks/hooks/batchresource/rule.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
- pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
- pkg/scheduler/plugins/loadaware/helper.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/util/pod_qos_utils.go
- pkg/webhook/pod/mutating/cluster_colocation_profile.go
- pkg/webhook/pod/validating/cluster_colocation_profile.go
- pkg/webhook/pod/validating/cluster_colocation_profile_test.go
1. Koordinator is using PriorityClass to make a lot of logical judgments, which need to consider compatible scenarios (default value)
2. Renamed GetPriorityClass and GetQoSClass at the same time to avoid misuse
> all: fix GetPriorityClass with default

- apis/scheduling/v1alpha1/reservation_types.go
- config/crd/bases/scheduling.koordinator.sh_reservations.yaml
- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/frameworkext/reservation_info_test.go
- pkg/scheduler/plugins/reservation/transformer.go
Add unschedulable field to Reservation.
fixes #1377
> koord-scheduler: Add unschedulable field to Reservation

- pkg/koordlet/config/config_test.go
- pkg/koordlet/metricsadvisor/collectors/beresource/be_resource_collector_test.go
- pkg/koordlet/qosmanager/config/config_test.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
koordlet: Fix flaky tests in `be_resource_collector_test.go`. Fix flag parsing UTs which cannot run with `go test -race`.
> koordlet: fix flaky tests

- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
> koord-descheduler: PodMigrationJob supports skipping all filters

- pkg/koordlet/resourceexecutor/reader_test.go
- pkg/koordlet/util/system/cgroup2.go
- pkg/koordlet/util/system/cgroup2_test.go
- pkg/koordlet/util/system/cgroup_resource.go
koordlet: fix the value conversion between `cpu.shares` and `cpu.weights` (cgroups-v2), use the same conversion as the kubelet.
link: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2254-cgroup-v2#phase-1-convert-from-cgroups-v1-settings-to-v2
> koordlet: fix the cpu.shares conversion on cgroups-v2

- pkg/koordlet/metriccache/metric_types.go
- pkg/koordlet/metrics/common.go
- pkg/koordlet/metrics/metrics_test.go
- pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector.go
- pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector_test.go
- pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
- pkg/koordlet/metricsadvisor/plugins_profile.go
- pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
- pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile_test.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
- pkg/koordlet/util/cpuinfo.go
- pkg/koordlet/util/cpuinfo_test.go
- pkg/koordlet/util/kubelet/kubelet.go
- pkg/koordlet/util/meminfo.go
- pkg/koordlet/util/meminfo_test.go
- pkg/koordlet/util/system/system_file.go
- pkg/koordlet/util/testutil/mock_utils.go
- Add the node NUMA info collection in the NodeInfoCollector.
- Add the NUMA topology reporting in the NRT state informer.
- Fix a bug where a prom metric is not registered.
- Refactor the internal LocalCPUInfo to save the cpu maps instead of the cpu counts.
Fixes #1503.
> koordlet: support numa topology reporting

- pkg/util/reservation/reservation.go
- pkg/util/reservation/reservation_test.go
Support set default priority 0 in reserve pod.
fix #1523
> koord-scheduler: set default priority in reserve pod

- docs/proposals/scheduling/20230802-device-share-supports-scoring.md
This proposal adds a scoring mechanism to DeviceShare plugins, which supports different strategies for spreading or bin-packing device resources.
part of #1457
> proposal: DeviceShare supports scoring

- apis/extension/coscheduling.go
- apis/extension/scheduling.go
1. Move the Gang scheduling extension APIs to file `apis/extension/coscheduling.go`.
2. Add  gang match policy  alias `pod-group.scheduling.sigs.k8s.io/match-policy` to compatible with special scenarios.
> apis: add gang match policy alias annotation

- go.mod
- go.sum
- pkg/descheduler/apis/config/types_pluginargs.go
- pkg/descheduler/apis/config/v1alpha2/defaults.go
- pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/controllers/migration/evict.go
- pkg/descheduler/controllers/migration/filter.go
this pr fixed tow problems.
1. `koord-descheduler` should reject create pmj when pmj.mode is `ReservationFirst` and  pod.schedulerName is not koord-scheduler  detail in  https://github.com/koordinator-sh/koordinator/issues/1527 this issue.
2.  update `deschuler` in go.mod, because some bug have been fixed.  eg: https://github.com/kubernetes-sigs/descheduler/pull/1104/files
> koord-descheduler: ignore create pmj when pod.schedulerName is not koord-scheduler

- pkg/koordlet/metriccache/metric_resources.go
- pkg/koordlet/metriccache/metric_types.go
- pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector.go
- pkg/koordlet/metricsadvisor/collectors/noderesource/node_resource_collector_test.go
- pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector.go
- pkg/koordlet/metricsadvisor/collectors/podresource/pod_resource_collector_test.go
- pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector.go
- pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector_test.go
- pkg/koordlet/metricsadvisor/framework/context.go
- pkg/koordlet/metricsadvisor/framework/context_test.go
- pkg/koordlet/metricsadvisor/metrics_advisor.go
- pkg/koordlet/metricsadvisor/metrics_advisor_test.go
- pkg/koordlet/metricsadvisor/plugins_profile.go
- pkg/koordlet/statesinformer/impl/states_nodemetric.go
- pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
- pkg/util/utils.go
- pkg/util/utils_test.go
Update system usage in node metric crd.
Add system usage collector in metric advisor. Read latest usage of node and pods from share state in context and calculate system usage, then saves in metric cache.
Although this can be calculate by node-sum(pod) from metric cache, but the time series are unaligned across different type of metric, which makes it hard to aggregate.
#991
> koordlet: report system resource usage in node metric

- pkg/descheduler/controllers/migration/filter.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
The `nodeMetric.Status.NodeMetric.NodeUsage` does not change immediately after some pods are evicted by the plugin, because by default nodeUsage is an average over 5 minutes.  So change to the sum of Pod utilization plus sysUsage as Node Usage.
fix #990
> koord-descheduler: accumulates the sum of system and Pod usage as node usage

- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/device_cache_test.go
- pkg/scheduler/plugins/deviceshare/device_handler.go
- pkg/scheduler/plugins/deviceshare/device_handler_test.go
- pkg/scheduler/plugins/deviceshare/plugin.go
The user may accidentally delete the Device CRD object, and then the Device CRD object will be recreated by koordlet/DevicePlugin. During this period, the internal state can only be marked as invalid, otherwise the GPU may be repeatedly allocated to different Pods.
And the DeviceShare plugin will start a GC thread to GC the remaining NodeDevice objects that are no longer present.
fix #1186
> koord-scheduler: invalidate nodeDevice when deleting Device CRD object

- .goreleaser.yaml
Fix the runtime-proxy release error since the latest version of the goreleaser does not support `archieve.replacement` field anymore.
https://goreleaser.com/deprecations/#archivesreplacements
> CI: fix goreleaser.yaml for the deprecated replacement field

- pkg/koordlet/qosmanager/helpers/property.go
- pkg/koordlet/qosmanager/helpers/property_test.go
- pkg/koordlet/qosmanager/plugins/cgreconcile/cgroup_reconcile.go
- pkg/koordlet/qosmanager/plugins/cgreconcile/cgroup_reconcile_test.go
- pkg/util/sloconfig/nodeslo_config.go
- pkg/util/sloconfig/nodeslo_config_test.go
koordlet: Add the ResourceQOS configurations for qos=SYSTEM pods.
When a pod reclaims its QoSClass as SYSTEM, the current ResourceQOS strategy can fail to parse the config for the pod since there is no SYSTEM class config defined. Especially, it can cause panic when CgroupReconcile is enabled and a SYSTEM pod is running on the node.
> koordlet: resource qos config supports SYSTEM qos

- pkg/slo-controller/noderesource/resource_calculator_test.go
> koord-manager: only enable necessary plugin in the ut of resource calculator

- docs/proposals/scheduling/20220722-multi-hierarchy-elastic-quota-management.md
- pkg/util/fieldindex/register.go
- pkg/webhook/elasticquota/pod_check.go
- pkg/webhook/elasticquota/quota_topology.go
- pkg/webhook/elasticquota/quota_topology_check.go
- pkg/webhook/elasticquota/quota_topology_test.go
Relax the limit of IsParent change. 
If quota is not bound to pods, it can become parent node. 
If quota doesn't have children, it can become child node.
> koord-manager: allow quotas that are not bound to pods to become parent nodes

- pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
we can see some log from koordlet, like this
```bash
I0822 18:35:46.671722 1276199 cpu_suppress.go:160] nodeSuppressBE[CPU(Core)]:14 = node.Total:38 * SLOPercent:70% - systemUsage:8 - podLSUsed:5
I0822 18:35:47.697638 1276199 cpu_suppress.go:160] nodeSuppressBE[CPU(Core)]:14 = node.Total:38 * SLOPercent:70% - systemUsage:11 - podLSUsed:4
I0822 18:35:48.719048 1276199 cpu_suppress.go:160] nodeSuppressBE[CPU(Core)]:14 = node.Total:38 * SLOPercent:70% - systemUsage:13 - podLSUsed:1
```
the values on both sides of the equation are not equal,  may lose precision when use `quantity.values()`, and causing some misunderstanding.
> koordlet: fix lose precision when show result of cpuspress

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
Fix IsParent in the quota tree rebuild
some parent quotas has no is-parent label. we should fix it in the rebuild phase
> koord-scheduler: fix missing IsParent when rebuild tree

- .github/workflows/e2e-k8s-1.22.yaml
- .github/workflows/e2e-k8s-1.24.yaml
- .github/workflows/e2e-k8s-latest.yaml
- config/manager/descheduler-config.yaml
- config/manager/koordlet.yaml
- config/manager/manager.yaml
- config/manager/scheduler-config.yaml
- config/manager/scheduler.yaml
- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- hack/deploy_kind.sh
- test/kind-conf.yaml
- ci: initialize the e2e workflow.
- config: fix the template YAMLs.
> ci: initialize e2e workflow

- pkg/koordlet/runtimehooks/nri/server.go
- pkg/koordlet/runtimehooks/nri/server_test.go
- pkg/koordlet/runtimehooks/runtimehooks.go
- pkg/koordlet/util/system/util_test_tool.go
koordlet: revise nri server starting, check if nri.sock exists before new the server.
> koordlet: revise nri server start

- pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
koordlet: Fix the NUMA ZoneList reporting in NRT, and revise the NRT updating check.
fixes #1585.
Expect the NRT is like:
```yaml
apiVersion: topology.node.k8s.io/v1alpha1
kind: NodeResourceTopology
metadata:
annotations:
kubelet.koordinator.sh/cpu-manager-policy: '{"policy":"none"}'
node.koordinator.sh/cpu-shared-pools: '[{"socket":0,"node":0,"cpuset":"0-15"}]'
node.koordinator.sh/cpu-topology: '{"detail":[{"id":0,"core":0,"socket":0,"node":0},{"id":1,"core":0,"socket":0,"node":0},{"id":2,"core":1,"socket":0,"node":0},{"id":3,"core":1,"socket":0,"node":0},{"id":4,"core":2,"socket":0,"node":0},{"id":5,"core":2,"socket":0,"node":0},{"id":6,"core":3,"socket":0,"node":0},{"id":7,"core":3,"socket":0,"node":0},{"id":8,"core":4,"socket":0,"node":0},{"id":9,"core":4,"socket":0,"node":0},{"id":10, …
```
> koordlet: fix NUMA info reporting

- apis/extension/numa_aware.go
- docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
- pkg/scheduler/plugins/nodenumaresource/cpu_accumulator_test.go
- pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
The `ResourceStatus` constrains that the Pod should run on the specified NUMA node, but the original definition cannot support this feature. The definition that records the allocated resources of each NUMA node has therefore been modified.
This change requires that the NUMA Node ID reported by koordlet **MUST BE** unique on that node.
> apis: update ResourceStatus to support NUMA-aware scheduling

- pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
- pkg/slo-controller/noderesource/resource_calculator.go
- pkg/slo-controller/noderesource/resource_calculator_test.go
koord-manager: Improve the calculation of the batch resource allocatable with the newly-added system metrics.
Fixes #1427.
Please note that the calculated allocatable can be lower than the real result at the nodeMetric reported time. It becomes accurate when there are no more pods terminated or newly-scheduled between the nodeMetric reported time and the controller calculating time.
> koord-manager: improve batch resource calculation with system metrics

- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
background:
Initially, gpu scheduling was implemented through the gpu device plugin, and after switching to koord-scheduler scheduling, the pod could not be scheduled, prompts that no device resources.
reason:
The gpu node doesn't have a koordlet, but it does report gpu info to node.status via the device plugin, so it can be scheduled by default-scheduler. But koord-scheduler's deviceshare plugin intercepts scheduling pod because there are no device resources.
resolve:
deviceshare skips handling nodes without device
> koord-scheduler: deviceshare plugin skips handling nodes without device cr

- apis/scheduling/v1alpha1/device_types.go
- config/crd/bases/scheduling.koordinator.sh_devices.yaml
- config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
> apis: remove omitempty tag of Device's field health

- pkg/features/scheduler_features.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_factory.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/reservation/nominator_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/scoring_test.go
- pkg/scheduler/plugins/reservation/service_test.go
- pkg/scheduler/plugins/reservation/transformer_test.go
- pkg/util/reservation/reservation.go
- pkg/util/reservation/reservation_test.go
- test/e2e/scheduling/deviceshare.go
Plugins like DeviceShare will add additional normalized resources after the scheduling is successful, and there may be more resources than Pod expects to apply for. In the Reservation scenario, these need to be backfilled to the Reservation and be perceived by subsequent links, so as to complete similar scenarios. resource reuse. This PR is to solve this problem.
> koord-scheduler: supports plugins to adjust reservation reusable resources

- pkg/scheduler/frameworkext/topologymanager/manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
At present, koordlet only reports cpu/memory in NodeResourceTopology. If a Pod requests resources from other resources, the Pod will not be able to be scheduled. So we should skip these non-existing resources.
> koord-scheduler: ignore non-existing resources in NUMA Node

- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/frameworkext/topologymanager/manager.go
- pkg/scheduler/frameworkext/topologymanager/policy_test.go
- pkg/scheduler/frameworkext/topologymanager/store.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint_test.go
- pkg/scheduler/plugins/nodenumaresource/topology_options_test.go
Convert the Allocate method to Admit, which is only used to calculate the optimal topology Hint, and store the Best Hint of each node in the Store. In the subsequent Score, Reserve and other stages, the Hint of the node can be queried through the Store. Once a Hint is determined, it cannot be changed, otherwise it will conflict with future functions that support Reservation/Preemption on NUMA-Aware.
> koord-scheduler: optimize NUMA Topology Manager interface

- .licenseignore
- pkg/scheduler/frameworkext/topologymanager/policy.go
- pkg/scheduler/plugins/nodenumaresource/least_allocated.go
- pkg/scheduler/plugins/nodenumaresource/most_allocated.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
- pkg/scheduler/plugins/nodenumaresource/scoring_test.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint.go
- pkg/scheduler/plugins/nodenumaresource/util.go
Rewrite the scoring algorithm of the plugin `NodeNUMAResource` to support NUMA-aware scheduling scenarios.
The original scoring algorithm only considered CPUSet, but now we need to consider resources in more dimensions and resource allocation in the NUMA Node dimension.
The new scoring algorithm is as compatible as possible with the original scoring algorithm:
- If the Pod is allocated on a node whose NUMATopologyPolicy is not none, the scoring algorithm will sum the requests of all pods and sum the available allocations of the used NUMA nodes. If the current Pod also requests a CPUSet, the sum of the requests in the CPU resource dimension is equal to the already allocated CPUSet on the node plus the currently requested CPUSet, and finally uses the LeastAllocated/MostAllocated strategy …
> koord-scheduler: numa-aware scheduling supports scoring

- apis/extension/elastic_quota.go
- docs/proposals/scheduling/20220722-multi-hierarchy-elastic-quota-management.md
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_helper.go
- pkg/scheduler/plugins/elasticquota/plugin_helper_test.go
- pkg/util/fieldindex/register.go
- pkg/webhook/elasticquota/pod_check.go
- pkg/webhook/elasticquota/quota_topology.go
- pkg/webhook/elasticquota/quota_topology_check.go
- pkg/webhook/elasticquota/quota_topology_test.go
Add an annotation to expand the bound relationship of ElasticQuota and Pod.
> koord-scheduler: add annotation about namespaces that limit quota usage

- apis/extension/numa_aware.go
- docs/proposals/scheduling/20220530-fine-grained-cpu-orchestration.md
- pkg/scheduler/apis/config/validation/validation_pluginargs.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
Add `RequiredCPUBindPolicy` in `ResourceSpec`. `RequiredCPUBindPolicy` indicates that the CPU is allocated strictly according to the specified CPUBindPolicy, otherwise the scheduling fails.
`RequiredCPUBindPolicy` supports `FullPCPus` and `SpreadByPCPUs` policies.
> koord-scheduler: support required CPU bind policy

- .github/workflows/e2e-k8s-1.22.yaml
- .github/workflows/e2e-k8s-1.24.yaml
- .github/workflows/e2e-k8s-latest.yaml
- config/rbac/role.yaml
- hack/deploy_kind.sh
- pkg/slo-controller/noderesource/plugins/cpunormalization/plugin.go
1. CI: Mark the E2E status check as optional, postponed to be required when it is complete and optimized.
2. config: fix the koord-manager role on NodeResourceTopology.
> ci: fix koord-manager role and ignore errors in e2e job 

- config/rbac/scheduler_role.yaml
remove quota profile rbac role for koord-scheduler
> ci: remove quota profile rbac role for koord-scheduler

- apis/extension/numa_aware.go
- pkg/features/koordlet_features.go
- pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
- pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress_test.go
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
Report be cpu share pool in annotation of NodeResourceTopo
Set cpuset according to specified numa node id for BE pod is scheduler specified.
BECPUSuppress should not work together with BECPUManager.
If both enabled, CPUSuppress will recover cpuset on all level for be pod does not specified numa node, and let be cpu set hook handle the others
> koordlet: report be cpu share pool and set cpuset if specified

- cmd/koord-scheduler/app/server.go
- pkg/scheduler/frameworkext/errorhandler_dispatcher.go
- pkg/scheduler/frameworkext/errorhandler_dispatcher_test.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/frameworkext/scheduler_adapter.go
The framework extension executes handlers after handling scheduling errors to gain the opportunity to affect the scheduling queue.
> koord-scheduler: framework extension executes handler after handling scheduling errors

- pkg/scheduler/plugins/nodenumaresource/node_allocation.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_service.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/pod_eventhandler_test.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint.go
- test/e2e/scheduling/nodenumaresource.go
The original implementation of GetPodTopologyHints of NodeNUMAResource provides special processing for CPU-binding scenarios, but this is actually problematic. For example, if a node has two NUMA Nodes, the most CPUs on each NUMA Node are allocated by CPUShare Pods. If we create a LSR Pod at this time, TopologyHint will still be generated, although the allocation will fail in the end. So we need to correct this implementation from the beginning.
> koord-scheduler: NodeNUMAResource only consider allocatable when generating hints

- apis/slo/v1alpha1/nodeslo_types.go
- config/crd/bases/slo.koordinator.sh_nodeslos.yaml
- pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector.go
- pkg/koordlet/metricsadvisor/collectors/sysresource/system_resource_collector_test.go
- pkg/koordlet/metricsadvisor/framework/config.go
- pkg/koordlet/metricsadvisor/framework/config_test.go
- pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
- pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict_test.go
- pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
- pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile_test.go
- pkg/koordlet/qosmanager/qosmanager.go
- pkg/koordlet/resourceexecutor/cgroup.go
- pkg/koordlet/resourceexecutor/reader.go
- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
- pkg/koordlet/statesinformer/impl/states_nodeslo_test.go
- pkg/koordlet/util/cpuinfo.go
- pkg/koordlet/util/system/resctrl.go
- pkg/koordlet/util/system/resctrl_linux.go
- pkg/koordlet/util/system/resctrl_test.go
- pkg/koordlet/util/system/util_test_tool.go
- pkg/util/resource.go
- pkg/util/resource_test.go
- pkg/util/sloconfig/nodeslo_config.go
1. BECPUEvict: Support `evictByAllocatable` policy to calculate cpu satisfaction.
2. RdtResctrl: Support retrieve sandbox container's task IDs.
3. CPUSetAllocator: Fix the filters for qos=LS and qos=None pods.
4. SystemResourceCollector: Support a custom metric outdated interval.
> koordlet: revise BECPUEvict, RdtResctrl, CPUSetAllocator and system collector

- apis/extension/numa_aware.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
1. Remove unused field of preFilterState.
2. Enhance the verification of Required FullPCPUs to reject non-multiple CPU requests under the SMT architecture.
3. The logic of updating ResourceSpec during PreBind supports the Required field.
> koord-scheduler: revise NodeNUMAResource

- pkg/koordlet/qosmanager/helpers/property.go
- pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
- pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile_test.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/rule_test.go
1. koordlet: fix the ResourceQOS configs missing rules for LSE pods.
> koordlet: fix resource qos rules missing LSE

- pkg/slo-controller/noderesource/framework/extender_plugin.go
- pkg/slo-controller/noderesource/framework/noderesource.go
- pkg/slo-controller/noderesource/noderesource_controller_test.go
- pkg/slo-controller/noderesource/plugins/batchresource/noderesourcetopology_event_handler.go
- pkg/slo-controller/noderesource/plugins/batchresource/noderesourcetopology_event_handler_test.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
- pkg/slo-controller/noderesource/plugins/batchresource/util.go
- pkg/slo-controller/noderesource/plugins/batchresource/util_test.go
- pkg/slo-controller/noderesource/plugins/cpunormalization/plugin.go
- pkg/slo-controller/noderesource/plugins/cpunormalization/plugin_test.go
- pkg/slo-controller/noderesource/plugins/midresource/plugin.go
- pkg/slo-controller/noderesource/plugins_profile.go
1. koord-manager:
- batch resources support zone-level overcommitment.
- Move the amplification according to the cpu normalization ratio inside the BatchResource plugin.
NUMA-level batch resources should be updated on the NRT like:
```yaml
apiVersion: topology.node.k8s.io/v1alpha1
kind: NodeResourceTopology
metadata:
annotations:
kubelet.koordinator.sh/cpu-manager-policy: '{"policy":"none"}'
node.koordinator.sh/be-cpu-shared-pools: '[{"socket":0,"node":0,"cpuset":"0-15"}]'
node.koordinator.sh/cpu-basic-info: '{"cpuModel":"Intel(R) Xeon(R) Platinum XXX CPU @2.50GHz","hyperThreadEnabled":true, "turboEnabled":true, "vendorID":"GenuineIntel"}'
node.koordinator.sh/cpu-shared-pools: '[{"socket":0,"node":0,"cpuset":"0-15"}]'
node.koordinator.sh/cpu-topology: …
```
> koord-manager: add NUMA-level batch resources

- hack/libpfm.sh
Skip `libpfm4` installation in macOS.
fixes #1654 
`libpfm4` is not installed in macOS.
> Makefile: exit for macOS

- pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
- pkg/slo-controller/noderesource/plugins/batchresource/util.go
- pkg/slo-controller/noderesource/resource_calculator_test.go
- pkg/util/node.go
- pkg/util/node_test.go
consider resource reservation on kubelet during batch resource calculation.
for CalculateByPodRequest
Node(Batch).Alloc = Node.Capacity * thresholdRatio - System.Reserved - Pod(Prod/Mid).Request
where System.Reserved = max(Node.Anno.Reserved, Node.Kubelet.Reserved)
for CalculateByPodUsage
Node(Batch).Alloc = Node.Capacity * thresholdRatio - System.Used - Pod(Prod/Mid).Used
where System.Used = max(Node.Used - Pod(All).Used, Node.Anno.Reserved, Node.Kubelet.Reserved)
Node.Anno.Reserve and Node.Kubelet.Reserved are defined for the same purpose.
currently, only Node.Anno.Reserve is considered during batch resource calculation
> koord-manager: calculate batch resource with kubelet reserved

- apis/extension/node_resource_amplification.go
- apis/extension/node_resource_amplification_test.go
- pkg/scheduler/plugins/nodenumaresource/node_allocation.go
- pkg/scheduler/plugins/nodenumaresource/node_allocation_test.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_service.go
- pkg/scheduler/plugins/nodenumaresource/plugin_service_test.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
- pkg/scheduler/plugins/nodenumaresource/topology_options.go
- pkg/scheduler/plugins/nodenumaresource/util.go
The NodeNUMAResource plugin amplifies the resource per NUMA Node of NRT(BTW: later NodeResource controller supports amplification rations, we should remove the operation.), and amplify requests and allocated of CPU Bind Pod such as LSE/LSR, but once the pod scheduled, the resource-status just records the original requests. For example, One LSR Pod requests 4000m CPU,  and Node-A has amplification ratios such as { "cpu": 1.5 }, so the plugin amplified the requests to 6000m, but in the NUMA Node still allocated 4000m.  This is done because the amplification ratios change dynamically.
> koord-scheduler: NodeNUMAResource supports amplification ratios

- apis/extension/elastic_quota.go
- pkg/webhook/elasticquota/quota_topology.go
- test/e2e/e2e_test.go
- test/e2e/quota/framework.go
- test/e2e/quota/multi_tree.go
> koord-scheduler: add e2e case for multi quota tree

- pkg/scheduler/plugins/elasticquota/quota_handler.go
- pkg/scheduler/plugins/elasticquota/quota_handler_test.go
> koord-scheduler: fix root quota when deleted

- pkg/quota-controller/profile/profile_controller.go
- pkg/quota-controller/profile/profile_controller_test.go
> koord-manager: fix quota profile resource ratio

- apis/extension/node_resource_amplification.go
- apis/extension/node_resource_amplification_test.go
- pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
This is the following-up PR of #1677 fixing its dangling comments. It also does some unification to the node resource amplification apis.
part of #1539
> koord-scheduler: NodeNUMAResource scoring fix and tweak with node-level amplification ratios

- pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
- pkg/koordlet/runtimehooks/hooks/batchresource/batch_resource.go
koordlet: revise logs in BECPUSuppress and BatchResource.
> koordlet: revise logs in be suppress and batch resource

- pkg/scheduler/plugins/elasticquota/controller.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
- pkg/scheduler/plugins/elasticquota/core/scale_minquota_when_over_root_res.go
- pkg/scheduler/plugins/elasticquota/pod_handler.go
- pkg/scheduler/plugins/elasticquota/quota_handler.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
> koord-scheduler: optimize elastic quota log

- apis/extension/reservation.go
- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/plugins/reservation/cache.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_benchmark_test.go
- pkg/scheduler/plugins/reservation/transformer_test.go
- pkg/util/reservation/reservation.go
- pkg/util/reservation/reservation_test.go
Optimize plugin Reservation's BeforePreFilter performance.
```
goos: darwin
goarch: amd64
pkg: github.com/koordinator-sh/koordinator/pkg/scheduler/plugins/reservation
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
benchmark                                       old ns/op     new ns/op     delta
BenchmarkBeforePrefilterWithMatchedPod-12       7191996       3728866       -48.15%
BenchmarkBeforePrefilterWithMatchedPod-12       6965735       4111975       -40.97%
BenchmarkBeforePrefilterWithMatchedPod-12       7242072       3918338       -45.89%
BenchmarkBeforePrefilterWithMatchedPod-12       7099550       3754856       -47.11%
BenchmarkBeforePrefilterWithMatchedPod-12       7360839       3836024       -47.89%
BenchmarkBeforePrefilterWithMatchedPod-12       7233161       4295326       -40.62% …
```
> scheduler: optimize reservation BeforePreFilter performance

- .github/workflows/ci.yaml
- .github/workflows/release.yml
- Makefile
- docker/koord-descheduler.dockerfile
- docker/koord-manager.dockerfile
- docker/koord-runtimeproxy.dockerfile
- docker/koord-scheduler.dockerfile
- docker/koordlet.dockerfile
- go.mod
- go.sum
- hack/tools.go
dockerfile: support mutli-arch image build.
1. The arm64 image will be built for each component in each PR.
2. Skip pushing images for unmerged PRs.
3. Module the pkg `sigs.k8s.io/controller-runtime/tools/setup-envtest` to resolve the Golang version issues in the latest version.
fixes #1245.
> dockerfile: support multiarch image build

- .github/workflows/e2e-k8s-1.22.yaml
- .github/workflows/e2e-k8s-1.24.yaml
- .github/workflows/e2e-k8s-latest.yaml
- config/manager/manager.yaml
- config/webhook/manifests.yaml
- hack/deploy_kind.sh
- pkg/webhook/node/validating/webhooks.go
- test/e2e/framework/test_context.go
- test/e2e/scheduling/nodenumaresource.go
- test/e2e/scheduling/preemption.go
- test/e2e/slocontroller/batchresource.go
- test/e2e/slocontroller/cpunormalization.go
- test/e2e/testing-manifests/slocontroller/be-demo.yaml
Add more E2E tests for slo-controller:
1. verify a batch pod can schedule the batch resources
2. check the cpu normalization ratio updating
Revise the deploy scripts for koord-manager and koord-scheduler.
> ci: add more slo controllers e2e test

- docs/proposals/scheduling/20230811-node-resource-amplification.md
This PR updates the proposal of node resource amplification to reflect the change we have made that we included scheduler level support in this feature. (In previous design, the scheduler level support is only included in the CPU normalization feature.)
part of #1539
> proposal: change node resource amplification from api to scheduling level

- apis/extension/elastic_quota.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/quota_summary.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_helper.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
- pkg/scheduler/plugins/elasticquota/preempt.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
- pkg/webhook/elasticquota/pod_check.go
Add non-preemptible feature in Elastic Quota Management
fixes #1473
> koord-scheduler: Add non-preemptible feature in Elastic Quota Management

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/quota_summary.go
- pkg/scheduler/plugins/elasticquota/plugin_service.go
- pkg/scheduler/plugins/elasticquota/plugin_service_test.go
- pkg/scheduler/plugins/elasticquota/quota_handler.go
> scheduler: quota debug api support multi tree

- .github/workflows/e2e-k8s-1.22.yaml
- .github/workflows/e2e-k8s-1.24.yaml
- .github/workflows/e2e-k8s-latest.yaml
- hack/deploy_kind.sh
CI: Apart from the koord-manager, load other components' images in the E2E tests.
fixes #1494.
> ci: support loading all components image in E2E

- pkg/scheduler/frameworkext/helper/forcesync_eventhandler.go
- pkg/scheduler/frameworkext/reservation_info.go
When the scheduler starts, some Pods may be updated multiple times in a short period of time, causing the ReservationInfo to add the same Pod multiple times, and ultimately cannot be reused because the reservation's allocated is greater than or equal to the reservation's allocable.  
The root cause is that the forceSyncEventHandler of the frameworkext helper module requires that all EventHandlers must be idempotent.
So the PR fix the issue. Make the ReservationInfo method `AddAssignedPod` idempotent.
> scheduler: make ReservationInfo.AddAssignedPod idempotent

- apis/extension/elastic_quota.go
- pkg/webhook/elasticquota/quota_info.go
- pkg/webhook/elasticquota/quota_topology_check.go
> webhook: add force update label for elastic quota

- pkg/quota-controller/profile/profile_controller.go
- pkg/quota-controller/profile/util.go
> manager: add GetNodeAllocatable in quota-controller

- pkg/koordlet/metrics/resource_summary.go
koordlet: fix the typo of the prom metric `koordlet_node_priority_resource_reclaimable`.
> koordlet: fix metric name typo

- cmd/koord-scheduler/app/server.go
- pkg/util/asynclog/async_log.go
By default, klog outputs logs synchronously to stderr, which will affect performance when there are too many logs.
Therefore, we can reduce the delay caused by syscall and IO by outputting logs asynchronously, thus improving performance.
When enable `--async-log`,  also need to enable `-logtostderr` and disable `-alsologtostderr`. And also can set `--async-log-queue-length` to fine-tune performance.
> scheduler: use asynclog to reduce klog performance overhead

- pkg/scheduler/frameworkext/controllers.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
Reservation plugin senses NodeAffinity and reduces the amount of calculation. For example, DaemonSet Pod is only scheduled to one node, so we only need to process the Reservation of one node.
> scheduler: reservation senses node affinity

- apis/extension/elastic_quota.go
- pkg/scheduler/plugins/elasticquota/controller.go
- pkg/scheduler/plugins/elasticquota/metrics.go
> scheduler: add elastic quota metric

- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
The Pod declares a ReservationAffinity, which means that the Pod must reuse the Reservation resources, but there are no matching Reservations, which means that the node itself does not need to be processed. We can end early to avoid meaningless operations.
> scheduler: reservation transformer ends early with reservation affinity

- apis/scheduling/v1alpha1/device_types.go
- config/crd/bases/scheduling.koordinator.sh_devices.yaml
- config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
- docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
Currently, DeviceInfo in Device CRD is insufficient for AI/Data Computing Scenarios. Some device such as NICs support SR-IOV virtualization. The DeviceInfo lack of such information. In addition, every pcie device has its own topology such as cpu socket, NUNANode, bdf and the pcie switch to which the device is connected.
NONE
> apis: make PCIEID of DeviceTopology as string type

- pkg/koordlet/metriccache/metric_resources.go
- pkg/koordlet/metriccache/metric_types.go
- pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_collector.go
- pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_collector_test.go
- pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled.go
- pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled_test.go
- pkg/koordlet/metricsadvisor/collectors/pagecache/page_cache_collector.go
- pkg/koordlet/metricsadvisor/framework/config.go
- pkg/koordlet/metricsadvisor/framework/config_test.go
- pkg/koordlet/metricsadvisor/plugins_profile.go
- pkg/koordlet/resourceexecutor/reader_test.go
- pkg/koordlet/statesinformer/impl/states_nodemetric.go
- pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
- pkg/koordlet/util/cold_page.go
- pkg/koordlet/util/cold_page_test.go
- pkg/koordlet/util/meminfo.go
- pkg/koordlet/util/meminfo_test.go
- pkg/koordlet/util/system/cgroup.go
- pkg/koordlet/util/system/kidled_util.go
- pkg/koordlet/util/system/kidled_util_test.go
> koordlet: cold memory fix usageWithHotPage and add usageWithPageCache

- pkg/descheduler/apis/config/types_loadaware.go
- pkg/descheduler/apis/config/v1alpha2/defaults.go
- pkg/descheduler/apis/config/v1alpha2/defaults_test.go
- pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
- pkg/descheduler/apis/config/validation/validation_loadaware.go
- pkg/descheduler/apis/config/zz_generated.deepcopy.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
case:
The nodemetric cr has not been updated for a long time, e.g. the koordlet was deleted, but the load information written last time is particularly high, causing pods on this node being evicted all the time, even though the actual load was low. 
check nodemetrics cr is expired or not when descheduling
> descheduler: check nodemetrics cr is expired or not when descheduling

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta2/defaults.go
- pkg/scheduler/apis/config/v1beta2/types.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
- pkg/scheduler/apis/config/zz_generated.deepcopy.go
- pkg/scheduler/frameworkext/topologymanager/policy.go
- pkg/scheduler/frameworkext/topologymanager/policy_best_effort_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_none_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_restricted_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node.go
- pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node_test.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
- pkg/scheduler/plugins/nodenumaresource/scoring_test.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint.go
- pkg/scheduler/plugins/nodenumaresource/util.go
Currently the NodeNUMAResource plugin uses TopologyManager to generate the best hint, but the hint is the narrowest, e.g. if the node's topology strategy is SingleNUMANode, the best hint is always the one with the smallest NUMA Node ID, it works like a bin-packing strategy. However, some scenarios require selecting the least allocated NUMA node to ensure runtime QoS.
Add a new scoring strategy to NodeNUMAResourceArgs to support NUMA-Node level scoring, so that we can select the numa node with the highest score, and then in score-phase, we can select the node with the highest score at the node level.
User can configure the NodeNUMAResourceArgs as the following:
```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
- pluginConfig:
- name: …
```
> scheduler: numa-aware scheduling supports selecting numa node by score

- pkg/scheduler/plugins/reservation/pod_eventhandler.go
- pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
scheduler: leaky resources in ReservationInfo when pod failed to bind
fix #1741
> scheduler: leaky resources in ReservationInfo when pod failed to bind

- pkg/koordlet/prediction/predict_server.go
- pkg/koordlet/prediction/predict_server_test.go
- pkg/koordlet/prediction/prediction.go
koordlet: fix the failures of prediction restore for node priorities' checkpoints.
> koordlet: fix prediction restore for node priorities

- apis/extension/elastic_quota.go
- pkg/scheduler/plugins/elasticquota/controller.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/quota_summary.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
Add NonPreemptibleRequest in quotaInfo's QuotaCalculateInfo. 
With Min and NonPreemptibleRequest, for each quotaInfo, we can calculate the upper limit of the preemptible pod used. If the used of preemptible pod exceeds the upper limit, we will revoke the preemptible pods until preemptible pods used not exceeds the upper limit. It's the supplementary method of preemption in postFilter.
> scheduler: Add non-preemptible Request in quotaInfo's QuotaCalculateInfo

- apis/slo/v1alpha1/nodemetric_types.go
- config/crd/bases/slo.koordinator.sh_nodemetrics.yaml
- pkg/koordlet/prediction/peak_predictor.go
- pkg/koordlet/qosmanager/helpers/calculator.go
- pkg/koordlet/qosmanager/helpers/calculator_test.go
- pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
- pkg/koordlet/statesinformer/impl/states_nodemetric.go
- pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
- pkg/koordlet/statesinformer/impl/states_pods.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
- apis: Add new fields Priority and QoS onto the PodMetricInfo.
- koord-manager: Improve the calculation of BatchResource.
- koordlet: Revise the calculation of the non-BE allocatable cpu.
> koord-manager: improve batch resource calculation

- docs/proposals/scheduling/20230803-device-allocate-hint-apis.md
This proposal introduces new APIs to define anticipated device allocation strategies. One API set supports joint allocation scenarios for devices like GPUs and NICs according to the hardware topology. The other set offers device allocation hints, detailing specific allocation rules to guide scheduler decisions.
> proposal: add device allocation apis

- pkg/features/koordlet_features.go
- pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector.go
- pkg/koordlet/metricsadvisor/collectors/nodeinfo/node_info_collector_test.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
- pkg/koordlet/util/meminfo.go
- pkg/koordlet/util/meminfo_test.go
- pkg/koordlet/util/system/system_file.go
支持了大页上报的功能，包括2M和1G大页
无
可通过k8s `kubectl get noderesourcetopologies` 查看
支持了大页内存的上报，其中原本的内存memory上送的数目也进行了修改，将上报内存 设置为 总内存大小 减去 大页内存的数量。
func (s *nodeTopoInformer) calTopologyZoneList(nodeCPUInfo *metriccache.NodeCPUInfo) 需重点看下。
-  I have written necessary docs and comments
-  I have added necessary unit tests and integration tests
-  All checks passed in `make test`
> koordlet: support hugepage reporting

- pkg/scheduler/plugins/coscheduling/core/core.go
Passing an empty string when creating a status could lead to `Status.reasons` has an element which is a empty string. It  causes a redundant `, ` in `Event.message` when there are more than two PostFilter plugins.
> scheduler: fix redundant argument when create a unschedulable status.

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
For a gang job, for example, there are four pods, three pods have been assumed, but the fourth cannot be scheduled. The fourth obtains resources through preemption. But in the next round of allocation, the gang's preFilter will be calibrated checking scheduleCycle, which makes makes pod fail to schedule, so we hope to modify the verification logic of gang's preFilter.
> scheduler: Coscheduling skips check schedule cycle if pod has nominated node

- pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
- koordlet: revise the cpuset runtime hook for two cases below:
1. If a pod allocates NUMA-aware resources excluding CPU, it should follow the non-NUMA cpuset.
2. If a SYSTEM pod allocates NUMA-aware resources including CPU, it just follows the cpuset rule of NUMA resource since the NUMA-aware system-qos-resource is undefined.
Generally, a pod use NUMA-level cpuset should be:
1. QoS is not SYSTEM.
2. Pod annotations["scheduling.koordinator.sh/resource-status"].numaNodeResources[*]["cpu"] should be non-zero.
> koordlet: revise system qos and numa aware cpuset

- pkg/koordlet/util/cpuinfo_test.go
fix the ut since it is legal for arm if lscpu returns:
```
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE
0   0    0      0    -             yes
```
> koordlet: fix lscpu for arm ut

- apis/config/v1alpha1/cluster_colocation_profile_types.go
- apis/config/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml
- pkg/webhook/pod/mutating/cluster_colocation_profile.go
- pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
- Colocation Profile: support mutating pod labels or annotations according to the mapping rules.
It can be used to set the core scheduling group IDs (#1728) of the pods according to a given pod label.
e.g.
```
apiVersion: config.koordinator.sh/v1alpha1
kind: ClusterColocationProfile
metadata:
name: colocation-profile-example
spec:
namespaceSelector:
matchLabels:
koordinator.sh/enable-colocation: "true"
selector:
matchLabels:
koordinator.sh/enable-colocation: "true"
qosClass: BE
priorityClassName: koord-batch
koordinatorPriority: 1000
schedulerName: koord-scheduler
labels:
koordinator.sh/mutated: "true"
annotations: 
koordinator.sh/intercepted: "true"
labelsToLabels:
app-user-id: koordinator.sh/core-sched-group-id
patch:
spec:
terminationGracePeriodSeconds: 30
```
> colocationprofile: support mutating pod labels and annotations with mapping

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_factory.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/frameworkext/testing/fake_reservation_nominator.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/deviceshare/scoring.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/reservation/nominator.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/pod_eventhandler.go
- pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
- pkg/scheduler/plugins/reservation/scoring.go
- pkg/scheduler/plugins/reservation/scoring_test.go
The `ReservationNominator` interface and its implementation have been enhanced to support preemption scenarios. 
When performing preemption at the job granularity level, many Pods will initiate preemption in the PostFilter stage. As each Pod secures resources, the `ReservationNominator.NominateReservation` method is called to elect a Reservation. The `ReservationNominator.AddNominatedReservation` and PreFilterExtension.AddPod methods are then used to record the Request quantity. This ensures that the preemption results of one Pod can be perceived by the next Pod during its preemption process. 
When a new scheduling cycle begins, there is a possibility that a Pod awaiting scheduling may trigger the PreFilterExtension.AddPod again. Since the `AddNominatedReservation` method has already …
> scheduler: enhance ReservationNominator to support preemption

- pkg/scheduler/plugins/deviceshare/device_resources.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
1. The scheduler will panic during preemption since some maps are nil.
2. DeviceShare's AddPod method gets unexpected result that must be negative but got empty.
> scheduler: fix preemption panic

- pkg/scheduler/plugins/deviceshare/device_allocator.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/deviceshare/reservation_test.go
- pkg/scheduler/plugins/deviceshare/utils.go
- pkg/scheduler/plugins/reservation/nominator_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/scoring_test.go
In the past, for the Default policy, the remaining resources of the Reservation were returned to NodeInfo to ensure that the filter could pass the resource verification. However, in the FilterReservation, it only checked whether the remaining resources of the Reservation were sufficient. This actually led to the logical inconsistency between the Filter and the FilterReservation. For example, if a Reservation A has no remaining resources, it can pass the verification in the Filter, but fails in the FilterReservation. This is very strange. If we try to unify the logic of Filter and FilterReservation, we will find that the Default and Aligned strategies are consistent.
In addition, if a Pod declares a ReservationAffinity but the matching Reservation cannot meet the requirements, the node …
> scheduler: change reservation default allocate policy to aligned

- README.md
Currently, it seems koordinator use dingtalk doc for Notes and Agenda
Can't access shimo doc now, but I can access dingtalk doc.
> chores: replace shimo doc to dingtalk

- cmd/koord-scheduler/app/server.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_factory.go
- pkg/scheduler/frameworkext/scheduler_monitor.go
- pkg/scheduler/frameworkext/scheduler_monitor_test.go
- pkg/scheduler/metrics/metrics.go
feat: Add SchedulerMonitor for tracking pod scheduling timeouts
A new SchedulerMonitor component has been introduced to track the time taken to schedule pods and log warnings if the scheduling time exceeds a predefined threshold. This enhancement includes a mechanism to update metrics upon timeout, improving observability and aiding in debugging scheduling delays.
> scheduler: add monitor to detect scheduling deadlock

- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
koordlet: fix sharepool cpuset when the numaResource is allocated by a BE pod.
> koordlet: fix be cpuset for numaResource

- README-zh_CN.md
> chores: update bi-weekly meeting notes link

- pkg/slo-controller/noderesource/plugins/resourceamplification/plugin.go
- pkg/slo-controller/noderesource/plugins/resourceamplification/plugin_test.go
- pkg/slo-controller/noderesource/plugins_profile.go
This PR introduces node resource amplification plugin to koord-manager.
Currently, it is meant to implement below logic with bold text described in the [CPU normalization proposal](https://github.com/koordinator-sh/koordinator/blob/main/docs/proposals/scheduling/20230831-cpu-normalization.md):
> On koord-manager side, the Node resource controller runs a reconcile loop to do following things for Nodes with CPU normalization enabled:
>
> 1. Get CPU normalization ratio of the Node from CPU normalization model according to the Node's CPU basic info from its NodeResourceTopology.
> 2. **Calculate the final CPU amplification ratio (this is covered in the Node Resource Amplification proposal) by following formula: CPU_Amplification_Ratio = CPU_Amplification_Ratio_Original * …
> slo-controller: Introduce node resource amplification plugin

- pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
> koordlet: fix typo in function isBECPUUsageHighEnough

- pkg/koordlet/statesinformer/impl/states_pods.go
add write lock during podmap update, otherwise there is potential race condition
> koordlet: fix by adding lock during podmap update

- pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
- pkg/koordlet/util/node.go
- pkg/koordlet/util/node_test.go
koordlet: fix the group identity disabling for the special cases when some pod cgroups are not under the kube qos
> koordlet: fix recursively disabling bvt

- apis/configuration/slo_controller_config.go
- pkg/koordlet/statesinformer/impl/states_nodeslo.go
- pkg/koordlet/statesinformer/impl/states_nodeslo_test.go
- fix lost json annotation in NodeStrategy struct
- fix the type lost in merging with default value in mergeSLOSpecExtensions
> koordlet: fix struct type lost of node slo extension

- pkg/scheduler/plugins/elasticquota/plugin_helper.go
This change addresses the issue where the ElasticQuota creation was failing during the initialization phase, which was leading to startup failures. 
fix #1844.
> scheduler: fix ElasticQuota creation failure on startup

- pkg/koordlet/koordlet.go
- pkg/koordlet/resourceexecutor/executor.go
koordlet: eliminate the error "cache GC is not started" when the koordlet starts.
It fixes the cgroups updating failure of the runtime hooks' rule callbacks since they can be invoked just after the states informer's running and before the runtime hook runs.
> koordlet: eliminate cache GC is not started

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta2/defaults.go
- pkg/scheduler/apis/config/v1beta2/types.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.deepcopy.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_helper.go
- pkg/scheduler/plugins/elasticquota/plugin_helper_test.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
- pkg/scheduler/plugins/elasticquota/preempt.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
Runtime quota can solve the fairness problem at the Quota layer, but in some scenarios, such as AI model training scenarios, the job may not be able to run due to runtime quota. It is necessary to provide a switch to turn off this ability to deal with this scenario.
to https://github.com/koordinator-sh/koordinator/issues/1780
> scheduler : supports disable runtime quota

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
> scheduler: fix missing tree id in GetQuotaSummary()

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_service_test.go
Changes have been made in PR #1839. When `runtime` is not needed, `max` will be used as the upper limit of ElasticQuota. But it hasn't been done thoroughly yet. Since there is no need to use `runtime`, there is no need to calculate runtime in the PreFilter stage. In addition, `GetQuotaSummary` is an externally exposed interface. It only needs to read the most recent `runtime`, and there is no need to recalculate `runtime`. If we need to compute `runtime` more aggressively in the future, we should consider implementing a more efficient, cohesive method to support it.
> scheduler: ElasticQuota runtime is no longer calculated when not needed

- pkg/descheduler/framework/plugins/loadaware/low_node_load.go
fix https://github.com/koordinator-sh/koordinator/issues/1854
We should not try to mark all source nodes as normal because only abnormal nodes have been evicted. This PR changes it so that only abnormal nodes will be marked as normal.
> descheduler: fix bug of nodeAnomalyDetector in LowNodeLoad plugin

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta2/types.go
- pkg/scheduler/apis/config/v1beta2/zz_generated.conversion.go
- pkg/scheduler/apis/config/validation/validation_pluginargs.go
- pkg/scheduler/apis/config/zz_generated.deepcopy.go
- pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
- pkg/scheduler/plugins/coscheduling/plugin_controller.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin_test.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go
- pkg/scheduler/plugins/elasticquota/quota_overuse_revoke_test.go
Improve plugin args by fixing JSON tags and removing unnecessary pointers
- Added missing JSON tags to the plugin arguments to ensure proper serialization.
- Removed pointers from struct fields where direct values are more appropriate, reducing the potential for nil pointer dereferences and simplifying the codebase.
> scheduler: improve plugin args

- pkg/scheduler/plugins/coscheduling/coscheduling.go
If some Pods with the same PodGroup CRD object are created and scheduling fails, the coscheduling PreFilter returns framework.Error to stop preemption, but this is not the best option. It should return framework.UnschedulableAndUnresolvable.
framework.Error is special in the scheduler. It represents an internal service exception. We can determine whether the scheduler is healthy by identifying whether there are Errors, but a plugin that frequently returns Errors will prevent us from identifying exceptions.
fix #1860
> scheduler: improve Coscheduling PreFilter status

- cmd/koord-manager/main.go
- cmd/koordlet/main.go
- pkg/koordlet/metrics/external_metrics.go
- pkg/koordlet/metrics/internal_metrics.go
- pkg/koordlet/metrics/metrics.go
- pkg/slo-controller/metrics/common.go
- pkg/slo-controller/metrics/metrics.go
- pkg/slo-controller/metrics/metrics_test.go
- pkg/slo-controller/metrics/node_resource.go
- pkg/util/metrics/merged_gather.go
- pkg/util/metrics/merged_gather_test.go
seperate koordlet/slo-controller metrics as internal and external
ExternalHTTPPath: for end users, such as batch resource util (also compatible with old URL /metircs for koordlet）
InternalHTTPPath: for cluster admin, such as performance of components.
DefaultHTTPPath: merge all internal, external and controller runtime metrics.
> metrics: seperater metrics as internal and external for slo-controller and koordlet

- pkg/scheduler/plugins/deviceshare/device_allocator.go
- pkg/scheduler/plugins/deviceshare/devicehandler_default.go
- pkg/scheduler/plugins/deviceshare/devicehandler_default_test.go
- pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
1. Add unit testing for DefaultDeviceHandler of DeviceShare plugin.
2. Fix the method of calculating desiredCount in DeviceShare ApplyForAll strategy. The `ApplyForAll` strategy will select devices that match the selector of hint, if no devices can match, will return the error to stop scheduling.
fix #1869
> scheduler: fix the method of calculating desiredCount in DeviceShare ApplyForAll strategy

- pkg/webhook/cm/plugins/sloconfig/resource_qos_checker.go
- pkg/webhook/cm/plugins/sloconfig/resource_qos_checker_test.go
add some logic to verify netqos config is valid
> webhook: validate network qos config in webhook

- pkg/koordlet/metricsadvisor/metrics_advisor.go
- pkg/koordlet/util/cpuinfo.go
> koordlet: decouple CUDA dependency Accelerators feature disabled

- pkg/koordlet/resourceexecutor/updater.go
- pkg/koordlet/resourceexecutor/updater_test.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/proxyserver/service.go
- pkg/koordlet/runtimehooks/proxyserver/service_test.go
koordlet
- Fix a nil reference bug when the runtime proxy server is invoked for the container-related methods.
- Revise the cgroup updater for the `cpu.max` where the old cgroup content is not a single integer.
- Add UTs to avoid regression problems.
Fixes #1882.
> koordlet: fix proxy container service and revise cpu.max updater

- pkg/webhook/elasticquota/plugin_check_quota_meta_validate.go
- pkg/webhook/elasticquota/plugin_check_quota_meta_validate_test.go
- pkg/webhook/elasticquota/quota_handler.go
- pkg/webhook/elasticquota/quota_handler_test.go
- pkg/webhook/elasticquota/quota_topology.go
- pkg/webhook/pod/mutating/multi_quota_tree_affinity.go
- pkg/webhook/pod/mutating/multi_quota_tree_affinity_test.go
- pkg/webhook/pod/mutating/mutating_handler_test.go
webhook: improve node affinity performance for MultiQuotaTree
> webhook: improve node affinity performance for MultiQuotaTree

- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
Bug caused when requiredCPUBindPolicy was introduced.
fix #1890
> scheduler: correct NodeNUMAResource handling with NodeFullPCPUsOnly and preferredCPUBindPolicy

- pkg/koordlet/qosmanager/helpers/metrics_query.go
- pkg/koordlet/qosmanager/plugins/cpuburst/cpu_burst.go
- pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
- koordlet: fix the misleading query helper where someone uses time.Second while others use time.Duration.
> koordlet: fix misleading query helper

- pkg/webhook/cm/plugins/sloconfig/resource_qos_checker.go
- pkg/webhook/cm/plugins/sloconfig/resource_qos_checker_test.go
ralated issue:  https://github.com/koordinator-sh/koordinator/issues/1866
The absolute value scenario is not handled, because it requires the actual network bandwidth of the `node`,  which is not yet available here
> webhook: more checks for netqos

- pkg/koordlet/statesinformer/impl/kubelet_stub.go
- pkg/koordlet/statesinformer/impl/kubelet_stub_test.go
remove logging field from the kubelet configz for forward compatibility to 1.28
#1801
> koorldet: remove logging field from the kubelet configz

- docs/proposals/scheduling/20240115-support-job-level-preemption.md
> proposal: support Job-level preemption

- docs/proposals/scheduling/20240201-enbale-reservation-preempt.md
> proposal: support Reservation preemption

- pkg/scheduler/plugins/elasticquota/plugin_helper.go
> scheduler: fix initializing built-in quota objects

- pkg/webhook/pod/validating/validating_handler.go
- pkg/webhook/pod/validating/verify_annotations.go
- pkg/webhook/pod/validating/verify_annotations_test.go
> webhook: forbid use internal protocols

- apis/extension/reservation.go
- pkg/scheduler/frameworkext/reservation_info.go
- pkg/util/reservation/reservation.go
- pkg/util/reservation/reservation_test.go
When a Pod uses a Reservation with an allocation policy of Restricted, the maximum amount of resources that can be used by intersecting resource requests cannot exceed the amount of resources in the Reservation. But in fact, some scenarios require that even intersecting resource requests should be allowed to break this limit. This PR introduces annotation `scheduling.koordinator.sh/reservation-restricted-options` to solve this problem.
1. Create Reservation with the annotation `scheduling.koordinator.sh/reservation-restricted-options`.
```yaml
apiVersion: scheduling.koordinator.sh/v1alpha1
kind: Reservation
metadata:
annotations:
scheduling.koordinator.sh/reservation-restricted-options: |- 
{"resources": ["cpu", "memory"]}
name: test-reservation
spec:
allocateOnce: false
allocatePolicy: …
```
> scheduler: add Reservation restricted options to control allocatable resources

- pkg/koordlet/metrics/internal_metrics.go
- pkg/koordlet/metrics/kubelet.go
- pkg/koordlet/metrics/metrics_test.go
- pkg/koordlet/metrics/psi.go
- pkg/koordlet/metrics/psi_test.go
- pkg/koordlet/metrics/resource_executor.go
- pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux_test.go
- pkg/koordlet/resourceexecutor/executor.go
- pkg/koordlet/resourceexecutor/reader.go
- pkg/koordlet/resourceexecutor/resctrl_updater.go
- pkg/koordlet/resourceexecutor/updater.go
- pkg/koordlet/statesinformer/impl/kubelet_stub.go
- pkg/koordlet/util/system/psi.go
- pkg/koordlet/util/system/psi_test.go
#1867
curl http://localhost:9316/metrics
```
koordlet_kubelet_request_duration_seconds_bucket{code="200",path="/configz",verb="get",le="0.001"} 64
koordlet_kubelet_request_duration_seconds_bucket{code="200",path="/configz",verb="get",le="0.004"} 65
koordlet_kubelet_request_duration_seconds_bucket{code="200",path="/configz",verb="get",le="0.016"} 65
koordlet_kubelet_request_duration_seconds_bucket{code="200",path="/configz",verb="get",le="0.064"} 65
koordlet_kubelet_request_duration_seconds_bucket{code="200",path="/configz",verb="get",le="0.256"} 65
koordlet_kubelet_request_duration_seconds_bucket{code="200",path="/configz",verb="get",le="1.024"} 65
koordlet_kubelet_request_duration_seconds_bucket{code="200",path="/configz",verb="get",le="4.096"} 65 …
```
> koordlet: add metrics for kubelet and resource executor

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/util/reservation/reservation.go
- pkg/util/reservation/reservation_test.go
Remove the restriction that reservation cannot be preempted. If users create reservation with priority, and mark the reservation is preemptible, the reservation can be preempted, otherwise, the reservation cannot be preempt since the priority is the highest by default.
fix #1856   implement #1887
> scheduler: remove the restriction that reservation cannot be preempted

- apis/extension/elastic_quota.go
- pkg/quota-controller/profile/profile_controller.go
- pkg/quota-controller/profile/profile_controller_test.go
- pkg/scheduler/plugins/elasticquota/controller.go
- pkg/scheduler/plugins/elasticquota/controller_test.go
export unschedulable resource for root quota
> scheduler: add unschedulable resource for root quota

- pkg/scheduler/plugins/nodenumaresource/cpu_topology.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
- pkg/scheduler/plugins/nodenumaresource/scoring_test.go
- pkg/scheduler/plugins/nodenumaresource/service.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint.go
- pkg/scheduler/plugins/nodenumaresource/util.go
- pkg/scheduler/plugins/nodenumaresource/util_test.go
If the node enables label `node.koordinator.sh/cpu-bind-policy` and configures the corresponding value to `FullPCPUsOnly` or `SpreadByPCPUs`, then the scheduler should ensure that the allocation result corresponding to `ResourceSpec.RequiredCPUBindPolicy` is consistent.
And the node policy may conflict with the `ResourceSpec.RequiredCPUBindPolicy` defined in the Pod.  For example: the node defined the policy with `FullPCPUsOnly`, and the Pod required `SpreadByPCPUs`,  this creates a conflict that should be filtered.
If the Pod does not declare the ResourceSpec with CPUBindPolicy(either required or preferred), and the node declares the CPUBindPolicy, the scheduler should allocate CPUs by node's CPUBindPolicy, even though the Pod's QoSClass is LS. Although the previous implementation could …
> scheduler: improve NodeNUMAResource handling node cpu bind policy

- .licenseignore
- go.mod
- go.sum
- pkg/util/metricserver/metrics_client.go
- pkg/util/metricserver/metrics_client_test.go
- pkg/util/metricserver/metrics_client_test_util.go
> utils: add metric server client

- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/frameworkext/reservation_info_test.go
Update the resourceNames of ReservationInfo when Reservation is updated.
> scheduler: update resourceNames of ReservationInfo

- pkg/koordlet/statesinformer/impl/states_pods.go
- pkg/koordlet/statesinformer/impl/states_pods_test.go
koordlet: revise podsInformer, pass cgroupRoot during the runtime instead of the global initialization.
> koordlet: revise cgroupRoot param in podsInformer

- pkg/scheduler/plugins/coscheduling/core/gang.go
The use of pod and podgroup was confused during the gang init phase, result failed to update the GangMatchPolicy configuration
NONE
> scheduler: resolve the wrong use of gangmod in gang init phase

- pkg/koordlet/util/node.go
- pkg/koordlet/util/node_test.go
cpuset's value of sanbox container cloud always be set to all cpu ids of the machine by kubelet, if we use this value, the cpu eviction function will not take effect.
NONE
> koordlet: fix bug that cpu eviction does not take effect

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/frameworkext/testing/fake_reservation_nominator.go
- pkg/scheduler/plugins/reservation/nominator.go
- pkg/scheduler/plugins/reservation/nominator_test.go
- pkg/scheduler/plugins/reservation/pod_eventhandler.go
- pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
- pkg/scheduler/plugins/reservation/transformer.go
Extend the reservation nominator. Reservation plugin implements the BeforeFilter function. In this function, we do add the nominated reservation infos.
fix #1935
> scheduler: extend reservation nominator to support reservation preemption

- docs/proposals/scheduling/20240131-pod-level-numa-policy.md
Introduce new api for pod level numa topology policy. With the new api, users can specify numa topology policy for each 
pod, so that pods that are more sensitive to latency can decide how they need to be orchestrated, rather than being passively 
scheduled according to the numa topology policy on the node.
> proposal: support pod customizing numa policy

- pkg/scheduler/plugins/coscheduling/core/core.go
If the PreFilter of Coscheduling return UnschedulableAndUnresolvable since do not collect enough pods of a PodGroup, the PostFilter of Coscheduling will mark the schedule cycle invalid. But there is no need to do this, because once the Pods are collected enough, scheduling can be quickly performed instead of having to wait until the next cycle to actually start scheduling.
> scheduler: improve coscheduling's PostFilter if not collect enough

- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/reservation/plugin.go
> scheduler: fix reservation calc error

- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
The reservation plugin of koord-scheduler traverses all reservations with the Restricted policy and determines whether a certain Reservation satisfies the Pod. When all reservations cannot be satisfied, we lose reasonable information, such as which resources cannot be satisfied, which can help users diagnose themselves.
So this PR aggregate these messages to users.
fixes #1909 
make pods requiring allocate resource from reservation, check the failed event, like follows.
`Warning  FailedScheduling  12s   default-scheduler  0/50 nodes are available: 1 Insufficient cpu by reservation.`
> scheduler: improve the failed event of Reservation's scheduling

- pkg/scheduler/plugins/deviceshare/device_allocator.go
- pkg/scheduler/plugins/deviceshare/device_allocator_test.go
> scheduler: pick vf by random

- pkg/scheduler/plugins/deviceshare/device_allocator.go
> scheduler: give more context to device allocator

- pkg/descheduler/framework/plugins/loadaware/low_node_load.go
We firstly check len(lowNodes) after classifyNodes, which cloud lead to the sourceNodes lose a chance to be mark as abnormal. If we change the order, the sourceNodes cloud be evict more quickly when we just add a new node to a overloaded cluster.
> descheduler: change the order of check len(lowNodes) and len(sourceNodes)

- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
We have global weights for resources in LowNodeLoad plugin, and we sort pods on abnormal nodes based on these weights and their usage. In most cases, a abnormal node only has one kind of  resource that is overutilized, so we may need to adjust the weights according to the actual situation before sorting the removable pods. I had a idea that we only include the overused resource for each pod through preparing weights before sorting. Could you give more suggestions?
> descheduler: only include the overused resources when sorting removable pods

- pkg/webhook/pod/mutating/cluster_colocation_profile.go
- pkg/webhook/pod/mutating/cluster_colocation_profile_test.go
when we set priorityclass koord-xxx with preemptionPolicy=Never, priority admission refuse to create pod with error like this:
```text
pods "test" is forbidden: the string value of PreemptionPolicy (Never)
must not be provided in pod spec; priority admission controller computed
PreemptLowerPriority from the given PriorityClass name
```
we overwrite PriorityClassName/Priority in cluster_colocation_profile, so as well PreemptionPolicy.
see
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/priority/admission.go#L188
> webhook: fix priority admission conflict

- apis/extension/resctrl.go
- apis/extension/resctrl_test.go
Add resctrl API. The API should be like below which you can refer to [proposal of resctrl enhance](https://github.com/koordinator-sh/koordinator/blob/main/docs/proposals/koordlet/20231227-koordlet-resctrl-qos-enhance.md)
```yaml
{
"llc": {
"schemata": {
"range": [20,80],
},
"schemataPerCache": [
{
"cacheid" : 0,
"range": [20,50]
},
{
"cacheid" : 1,
"range": [20,60]
},
],
},
"mb": {
"schemata": {
"percent": 20,
},
"schemataPerCache": [
{
"cacheid": 0,
"percent": 20
},
{
"cacheid": 1,
"percent": 40
},
],
}
}
```
> apis: add Resctrl API

- Makefile
- docker/koordlet.dockerfile
fix https://github.com/koordinator-sh/koordinator/issues/1945
> chore: fix make docker build xxx

- pkg/scheduler/plugins/deviceshare/device_resources.go
- pkg/scheduler/plugins/deviceshare/device_resources_test.go
- pkg/scheduler/plugins/deviceshare/nominator.go
- pkg/scheduler/plugins/deviceshare/nominator_test.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
fix deviceshare plugin of add\remove pod. For example, pod A preempts a pod in node1 in the last round preemption. If the next to schedule pod is pod B, framework will add pod A when RunFiltersWithNominatedsPod. However, the deviceSharePlugin's allocation result of pod A is not stored. As a result, the resources nominated by pod A may be occupied by pod B, although pod B's priority is lower than pod A, this case will be happened in fractional gpu allocation or topology aware allocation.
> scheduler : fix deviceshare plugin of add\remove pod

- pkg/koordlet/metrics/internal_metrics.go
- pkg/koordlet/metrics/metrics_test.go
- pkg/koordlet/metrics/runtime_hook.go
- pkg/koordlet/runtimehooks/hooks/hooks.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
koordlet: add the following metrics to record the runtime hook's execution:
- koordlet_runtime_hook_invoked_duration_milliseconds
- koordlet_runtime_hook_reconciler_invoked_duration_milliseconds
Part of #1867.
> koordlet: record invoke metrics for runtime hook

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/coscheduling/coscheduling_test.go
scheduler: optimize QueueSort func when Gang and Barepod Coexists
> scheduler: optimize QueueSort func when Gang and Barepod Coexists

- pkg/scheduler/plugins/reservation/eventhandler.go
- pkg/scheduler/plugins/reservation/eventhandler_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/transformer.go
> scheduler: fix reservation nominator residual bug

- pkg/descheduler/controllers/migration/evict.go
- pkg/koordlet/metricsadvisor/collectors/coldmemoryresource/cold_page_kidled.go
- pkg/koordlet/qosmanager/framework/pod_qos_control.go
- pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
- pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
- pkg/koordlet/runtimehooks/hooks/coresched/helper.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/rule.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/rule/rule.go
- pkg/koordlet/statesinformer/impl/callback_runner.go
- pkg/koordlet/statesinformer/impl/states_pods.go
- pkg/koordlet/util/meminfo.go
- pkg/koordlet/util/system/config.go
- pkg/util/httputil/reverseproxy.go
- pkg/util/metrics/expire_metric.go
- pkg/webhook/api_debug_server.go
- pkg/webhook/pod/mutating/extended_resource_spec.go
> chores: fix some fmt err

- pkg/scheduler/plugins/deviceshare/device_allocator.go
- pkg/scheduler/plugins/deviceshare/device_allocator_test.go
This reverts commit beaafa3bdfead33117080fa458aa5333e10d4d82.
> Revert "scheduler: pick vf by random (#1953)"

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache.go
- pkg/scheduler/plugins/coscheduling/core/gang_summary.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/coscheduling/coscheduling_test.go
- pkg/scheduler/plugins/coscheduling/plugin_service_test.go
> scheduler: assure Fairness and DeadlockFree

- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/coscheduling/coscheduling_test.go
> scheduler: sort gang of same gangGroup by gangId

- apis/extension/node_qos.go
- apis/extension/node_qos_test.go
- pkg/slo-controller/nodeslo/resource_strategy.go
- pkg/slo-controller/nodeslo/resource_strategy_test.go
Introduce an extension API (through annotation) to specify the total bandwidth for a node. This parameter takes precedence over ones configured in cluster strategy or node strategy, and will take effect in NodeSLO.
fixes #1883 (part 1).
> apis & slo-controller: allow specifying node-wise total bandwidth via annotation

- pkg/descheduler/controllers/migration/arbitrator/filter.go
> descheduler: allow annotated pod pass non-retrievable filter

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/core/quota_info.go
- pkg/scheduler/plugins/elasticquota/core/quota_summary.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
If allow parent quota submit pods, show parent self used and request.
> scheduler: add more quota details used and request in quotaInfo

- cmd/koordlet/main.go
- cmd/koordlet/options/options.go
koordlet: add a registry for external HTTP handlers.
> koordlet: add extended HTTP handler registry

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
- pkg/scheduler/plugins/coscheduling/core/gang_summary.go
- pkg/scheduler/plugins/coscheduling/core/gang_test.go
- pkg/scheduler/plugins/coscheduling/core/ganggroup.go
- pkg/scheduler/plugins/coscheduling/core/ganggroup_test.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/coscheduling/coscheduling_test.go
- pkg/scheduler/plugins/coscheduling/plugin_service_test.go
> scheduler: refine coscheduling fairness consider gangGroup

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
If the PreFilter of Coscheduling return UnschedulableAndUnresolvable since do not collect enough pods of a PodGroup, the PostFilter of Coscheduling will mark the schedule cycle invalid. But there is no need to do this, because once the Pods are collected enough, scheduling can be quickly performed instead of having to wait until the next cycle to actually start scheduling.
> scheduler: optimize scheduleCycle logic when notEnoughChildren

- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache.go
- pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go
- pkg/scheduler/plugins/coscheduling/core/gang_test.go
- pkg/scheduler/plugins/coscheduling/core/ganggroup.go
- pkg/scheduler/plugins/coscheduling/core/ganggroup_test.go
> fix panic of podGroup and pod delete order issue2

- pkg/scheduler/frameworkext/topologymanager/policy.go
- pkg/scheduler/frameworkext/topologymanager/policy_best_effort_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_restricted_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_test.go
将 NUMA 对齐策略 Restricted 与上游 Kubelet 逻辑对齐，即不同资源的 Hint 的 NUMAAffinity 一样时，才讲该 merged 后的 Hint 置为 preferred
> scheduler: refine restricted topology policy

- pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile.go
- pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile_test.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology.go
- pkg/koordlet/statesinformer/impl/states_noderesourcetopology_test.go
- pkg/koordlet/util/system/config.go
- pkg/koordlet/util/system/config_test.go
- CPU topology reporting: always update the NodeResourceTopology's annotation `node.koordinator.sh/node-cpu-allocs` even if the Kubelet cpu manager policy is none or it failed to read the checkpoint file, instead of only updating when it succeeded in parsing the checkpoint file and at least one pod is managed by the static policy. It also helps when we want the koordlet to ignore the cpu manager cpuset in some special cases.
- Command args: Remove the misused argument `cgroup-kube-dir`. Add an argument to parameterize the host directory `/var/lib/kubelet`.
> koordlet: revise node topology reporting for the kubelet cpu manager

- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint_test.go
> scheduler: try best to distribute cpu and memory evenly across numa

- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
> scheduler: remove invalid hint in which some numaNode lack resource

- .licenseignore
- pkg/util/metricsserver/metrics_client.go
- pkg/util/metricsserver/metrics_client_test.go
- pkg/util/metricsserver/metrics_client_test_util.go
pkg name `metrics` is conflict in `pkg/util/metricsserver` and `pkg/util/metrics`
change to `metricsserver`
> utils: change metrics server util pkg name

- pkg/descheduler/controllers/migration/arbitrator/arbitrator.go
- pkg/descheduler/controllers/migration/arbitrator/filter.go
- pkg/descheduler/controllers/migration/util/util.go
- pkg/descheduler/node/node.go
- pkg/descheduler/pod/pods.go
Add detail logs for nonRemovable pods
fixes #1773
> descheduler: Add detail logs for nonRemovable pods

- pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
- pkg/features/features.go
> chore: fix some nit error

- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/config_test.go
- pkg/koordlet/runtimehooks/nri/server.go
- pkg/koordlet/runtimehooks/nri/server_test.go
- pkg/koordlet/runtimehooks/runtimehooks.go
Currently, if containerd restart or upgrade, koordlet will lost connection between koordlet and containerd. This PR will reconnect to containerd.
Restart containerd and see koordlet hooks still work.
> koordlet: add NRI reconnect

- apis/extension/numa_aware.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/frameworkext/topologymanager/manager.go
- pkg/scheduler/frameworkext/topologymanager/policy.go
- pkg/scheduler/frameworkext/topologymanager/policy_best_effort.go
- pkg/scheduler/frameworkext/topologymanager/policy_none.go
- pkg/scheduler/frameworkext/topologymanager/policy_none_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_restricted.go
- pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node.go
- pkg/scheduler/frameworkext/topologymanager/policy_test.go
- pkg/scheduler/plugins/deviceshare/topology_hint.go
- pkg/scheduler/plugins/nodenumaresource/node_allocation.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint.go
- pkg/scheduler/plugins/nodenumaresource/util.go
- pkg/scheduler/plugins/nodenumaresource/util_test.go
- test/e2e/scheduling/nodenumaresource.go
> scheduler: support numa topology policy on pod

- pkg/scheduler/plugins/coscheduling/controller/podgroup.go
- pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_test.go
https://github.com/koordinator-sh/koordinator/issues/2030
> scheduler: coscheduling plugin sync scheduled in controller

- pkg/koordlet/runtimehooks/hooks/hooks.go
- pkg/koordlet/runtimehooks/nri/server.go
- pkg/koordlet/runtimehooks/nri/server_test.go
- pkg/koordlet/runtimehooks/protocol/pod_context.go
- pkg/koordlet/runtimehooks/protocol/pod_context_test.go
- pkg/runtimeproxy/config/config.go
Add NRI RemovePodSandbox event handler into koordlet hook. It's part of the #1974. Resctrl runtime hook will leverage this to cleanup the resctrl group.
#1831
> koordlet: add nri remove

- .github/workflows/e2e-k8s-1.22.yaml
- .github/workflows/e2e-k8s-1.24.yaml
- .github/workflows/e2e-k8s-1.28.yaml
- .github/workflows/e2e-k8s-latest.yaml
- config/manager/scheduler-config.yaml
- config/manager/scheduler.yaml
- Fix the deployment arguments of the koord-scheduler since some klog flags are not supported anymore.
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components#removed-klog-flags
- Refine the E2E workflow so that the scheduler and descheduler images of the current branch are loaded.
- TODO: koord-descheduler image is still not loaded in E2E due to the "no space left on device" problem in the GitHub Actions.
> ci: fix scheduler e2e workflow after 1.28 upgradation

- pkg/koordlet/qosmanager/helpers/metrics_query.go
> koordlet: change CollectContainerThrottledMetric with duration=2*collectoInterval

- pkg/koordlet/qosmanager/plugins/cpuburst/cpu_burst.go
- pkg/koordlet/qosmanager/plugins/cpuburst/cpu_burst_test.go
Some containers are not running, maybe they have failed, just skip them.
It can also reduce the confusing err msgs.
>  koordlet: skip the container which is not running in cpuBurst applyCFSQuotaBurst

- pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile.go
> koordlet: fix BlkioReconcile file close

- pkg/koordlet/pleg/pleg_test.go
- Fix another flaky test in koordlet PLEG, which has a little chance of failing in the resource-constrained scenarios.
> koordlet: fix flaky test in pleg

- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/coscheduling/coscheduling_test.go
> scheduler: make gang quickCheck earlier

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta3/types.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/topology_hint.go
> scheduler: make device topology alignment switchable

- go.mod
> scheduler: remove unused imports

- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/config_test.go
- pkg/koordlet/runtimehooks/nri/server.go
- pkg/koordlet/runtimehooks/nri/server_test.go
- pkg/koordlet/runtimehooks/runtimehooks.go
- Fix the koordlet NRI plugin parameters which may leak during the reconnections.
- Fix a flaky test `TestNriServer_Start` in the koordlet NRI module.
- Add arguments for the koordlet NRI plugin.
> koordlet: fix nri reconnect params

- pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin.go
- pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin_test.go
> manager: only sync label when label key exists

- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/deviceshare/topology_hint.go
- pkg/scheduler/plugins/reservation/plugin.go
1. deviceShare NUMA 感知调度未考虑 reseration Affinity
2. reservation 插件未在 reserve 阶段和 prebind 阶段考虑 reservation 未找到但是又制定了 reservation affinity的情况
3. DeviceShare restricted reservation 模式下插件返回的 status 未考虑外层分配不成功的情况
> fix some reservationAffinity related error

- pkg/koordlet/metriccache/metric_result.go
func AddSeries is called frequently, it's within multiple loops.
it.Err() will take a lot of time when the data is huge, we'd better reduce calling it.
> koordlet: reduce unnecessary call of Err() for better performance

- pkg/koordlet/resourceexecutor/config.go
- pkg/koordlet/resourceexecutor/resctrl_updater.go
- pkg/koordlet/resourceexecutor/resctrl_updater_test.go
- pkg/koordlet/util/system/resctrl.go
Add new schemata updater for resctrl runtime hook. It's part of the https://github.com/koordinator-sh/koordinator/pull/1974. Resctrl runtime hook will leverage this to create the resctrl group and write schemata.
https://github.com/koordinator-sh/koordinator/issues/1831
> koordlet: add resctrl updater

- pkg/koordlet/qosmanager/framework/config.go
- pkg/koordlet/qosmanager/framework/config_test.go
- pkg/koordlet/qosmanager/framework/context.go
- pkg/koordlet/qosmanager/framework/context_test.go
- pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go
- pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict_test.go
- pkg/koordlet/qosmanager/plugins/memoryevict/memory_evict.go
- pkg/koordlet/qosmanager/plugins/memoryevict/memory_evict_test.go
> koordlet: kill container after calling eviction api success

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
fixed before: 0/5 reservations are available: 4 Reservation(s) Insufficient nvidia, 1 Reservation(s) is unschedulable.
after fix: 0/5 reservations are available: 4 Reservation(s) Insufficient nvidia.com/gpu, 1 Reservation(s) is unschedulable.
> koord-scheduler: fix gpu name to nvidia/gpu in reservation level event

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1beta3/defaults.go
- pkg/scheduler/apis/config/v1beta3/types.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
- pkg/scheduler/apis/config/zz_generated.deepcopy.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/loadaware/load_aware_test.go
add `enableScheduleWhenNodeMetricsExpired` parameter for `loadaware` scheduler plugin to mark whether scheduling is allowed on node with expired nodemetric.   
it be used to address the following issues：
1. not allow scheduling when `nodemetric` expired：avoid pods being scheduled to nodes with high load.
2. allow scheduling when `nodemetric` expired：the actual load of the node is very low but the nodemetric is very high. It may be blocked by the `filter` phase,  causing the node to be unable to schedule a new pod anymore. FYI:  https://github.com/koordinator-sh/koordinator/pull/1563
> koord-scheduler: add a parameter to mark whether scheduling is allowed on node with expired nodemetric

- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
- pkg/util/reservation/reservation.go
- pkg/util/reservation/reservation_test.go
- Add a prefix to define the Reservation-level error reasons when scheduling failed.
- Append the failure reasons when other plugins filter out a pod specifying reservation affinities.
> scheduler: refine reservation msg if matched filtered out by other plugins

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
> scheduler: change reservation event message format

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
before:
3 Reservation(s) didn't match pod topology spread constraints (missing required label)
after:
3 Reservation(s) for node reason that didn't match pod topology spread constraints (missing required label)
> scheduler: add node info in reservation level event

- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/nodenumaresource/node_allocation.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/reservation.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager_test.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint.go
support pod cunsume reserved numa resource
implements https://github.com/koordinator-sh/koordinator/issues/228 - koord-scheduler supports Pod allocate from Reservation according NUMA Topology
> scheduler: support consume reserved numa resource

- cmd/koord-descheduler/app/server.go
- pkg/descheduler/apis/config/types.go
- pkg/descheduler/apis/config/v1alpha2/types.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
- pkg/descheduler/apis/config/zz_generated.deepcopy.go
- pkg/descheduler/evictions/eviction_limiter.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
We want to limit the total number of pods rescheduled in each iteration. Currently, we have restrictions at the node and namespace levels, but there is no cluster-level restriction in place.
fixes #2086
> koord-descheduler: limit the total number of pod evictions

- test/e2e/slocontroller/batchresource.go
- test/e2e/testing-manifests/slocontroller/be-demo.yaml
- Revise the configurations of the E2E manifests to de-flaky E2E tests.
- Fixes the issue where the E2E tests occasionally fail after #1992 merged.
> chore: fix e2e configs after the load-aware scheduling updated

- pkg/client/clientset/versioned/fake/register.go
- pkg/client/clientset/versioned/scheme/register.go
- pkg/descheduler/apis/config/types_loadaware.go
- pkg/descheduler/apis/config/v1alpha2/conversion_plugins.go
- pkg/descheduler/apis/config/v1alpha2/types_loadaware.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
- pkg/descheduler/apis/config/validation/validation_loadaware.go
- pkg/descheduler/apis/config/zz_generated.deepcopy.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
Balance the usage of prod pods among nodes. Ensure that both the resource usage of prod pods on nodes and the overall node usage are balanced. This helps reduce the impact of node usage on prod applications.
fix #2043
> koord-descheduler: balance prod pods between nodes in LowNodeLoad

- pkg/scheduler/plugins/loadaware/pod_assign_cache.go
- pkg/scheduler/plugins/loadaware/pod_assign_cache_test.go
Pod updates should not update the timestamp in loadaware cache. This would cause pods that have been in the cache for a while to estimate resource during scheduling instead of using the actual resource reported on nodemetric. This discrepancy arises from the timestamp change without timely updating of nodemetric.
> koord-scheduler: Pod updates should not update the timestamp

- pkg/descheduler/controllers/migration/arbitrator/arbitrator.go
- pkg/descheduler/controllers/migration/arbitrator/filter.go
- pkg/descheduler/controllers/migration/arbitrator/filter_test.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
- pkg/descheduler/controllers/migration/evict.go
The arbitrator relies on golang's `rate.Limiter` package to implement workload-level eviction limter. However, only when the `MigrationController` evicts a pod **successfully**, the limiter's tokens will be consumed. That leads to a high possibility that the number of `PodMigrationJob` passes the arbitration is more than objectLimiter's upper bound, so that we cannot really limit the number of pods being evicted inside a timewindow. 
This PR moves the objectlimiter from arbitrator to reconciler. Thus it can be checked based on the real number.
fixes #2074
> koord-descheduler: fix object limiter by move it to reconciler

- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
- pkg/descheduler/utils/sorter/pod.go
- pkg/descheduler/utils/sorter/pod_test.go
- pkg/descheduler/utils/sorter/scorer.go
- pkg/descheduler/utils/sorter/scorer_test.go
What is your proposal:
When descheduler evaluates which pod to expel to reduce the utilization of high-load nodes to a reasonable level, can descheduler perform matching calculations on the actual usage of the pod and the amount of eviction resources in advance?
Why is this needed:
This can reduce the number of times a single node is repeatedly entered into the eviction logical unit, reduce the number of single node eviction instances, and indirectly improve the accuracy of the eviction results and the stability of the business while ensuring that hot issues are solved.
Is there a suggested solution, if so, please add it:
evict pod priority selector：podNowResourceUsages >= nodeNowResourceUsages - nodeHighResourceThresholds * nodeResourceAllocatable …
> koord-descheduler: enhance LowNodeLoad scorer

- pkg/koordlet/statesinformer/api.go
- pkg/koordlet/statesinformer/impl/config.go
- pkg/koordlet/statesinformer/impl/config_test.go
- pkg/koordlet/statesinformer/impl/states_pods.go
- pkg/koordlet/statesinformer/impl/states_pods_test.go
Add taskids for each pod as an attributes. It's part of the https://github.com/koordinator-sh/koordinator/pull/1974. Resctrl runtime hook will leverage this to write new taskids to resctrl group.
https://github.com/koordinator-sh/koordinator/issues/1831
> koordlet: add taskids in statesinformer

- cmd/koord-manager/main.go
> koord-manager: fix the prom metrics handler

- apis/extension/reservation.go
- apis/extension/reservation_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/transformer.go
> scheduler: support pod request exact match reservation

- pkg/scheduler/plugins/reservation/nominator_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/scoring_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
scheduler: fix the memory overhead issue for the reservation cycleState.
> scheduler: reduce cycleState overhead for reservation

- pkg/scheduler/plugins/nodenumaresource/reservation.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint.go
- pkg/scheduler/plugins/nodenumaresource/util.go
> scheduler: fix reserveNUMAResource bug

- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
Add Allpodslevel reconciler function in case some runtime hooks may need to consume all pods at once. It's part of the https://github.com/koordinator-sh/koordinator/pull/1974.
https://github.com/koordinator-sh/koordinator/issues/1831
> koordlet: add allpods reconciler func

- apis/configuration/slo_controller_config.go
- apis/configuration/zz_generated.deepcopy.go
- pkg/slo-controller/noderesource/plugins/cpunormalization/plugin.go
- pkg/slo-controller/noderesource/plugins/cpunormalization/plugin_test.go
In some dedicated clusters, we don't need complex CPU models; instead, we prefer manually configured default  CPU normalization settings for greater flexibility.
> koord-manager: support manually configured default cpu normalization settings

- docker/koordlet.dockerfile
- go.mod
- go.sum
- pkg/koordlet/resourceexecutor/reader.go
- pkg/koordlet/resourceexecutor/updater.go
- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/hooks/tc/helper.go
- pkg/koordlet/runtimehooks/hooks/tc/helper_test.go
- pkg/koordlet/runtimehooks/hooks/tc/ipset.go
- pkg/koordlet/runtimehooks/hooks/tc/iptables.go
- pkg/koordlet/runtimehooks/hooks/tc/netqos_tc.go
- pkg/koordlet/runtimehooks/hooks/tc/rule.go
- pkg/koordlet/runtimehooks/hooks/tc/tc.go
- pkg/koordlet/runtimehooks/hooks/tc/tc_linux.go
- pkg/koordlet/runtimehooks/hooks/tc/tc_linux_test.go
- pkg/koordlet/runtimehooks/protocol/pod_context.go
- pkg/koordlet/runtimehooks/protocol/protocol.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/util/system/cgroup_resource.go
- pkg/koordlet/util/system/common_linux.go
- pkg/koordlet/util/system/common_linux_test.go
- pkg/koordlet/util/system/util_test_tool.go
- pkg/koordlet/util/system/validator.go
- pkg/koordlet/util/system/validator_test.go
A plugin for netqos, and based on tc.
other discussion:  https://github.com/koordinator-sh/koordinator/discussions/1764
btw, there may be some duplicate defination with pr https://github.com/koordinator-sh/koordinator/pull/1843 .
> koordlet: tc plugin for netqos

- docker/koordlet.dockerfile
Fixes the E2E failures like:
```bash
Run export KUBECONFIG=/home/runner/.kube/config
GOBIN=/home/runner/work/koordinator/koordinator/bin go install github.com/onsi/ginkgo/ginkgo@v1.16.4
Failed to compile e2e:
/opt/hostedtoolcache/go/1.20.14/x64/pkg/tool/linux_amd64/link: mapping output file failed: no space left on device
Ginkgo ran 1 suite in 34.075041123s
Test Suite Failed
koord-manager has not restarted
Error: Process completed with exit code 1.
```
> chore: fix koordlet dockerfile

- pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
Fix threshold initialization for prod when useDeviationThresholds mode is true. Add more debug log.
> koord-descheduler: Fix threshold initialization for prod.

- pkg/scheduler/plugins/reservation/nominator.go
> scheduler: optimize when only 1 reservation/node

- pkg/descheduler/apis/config/types_pluginargs.go
- pkg/descheduler/apis/config/v1alpha2/defaults.go
- pkg/descheduler/controllers/migration/arbitrator/filter.go
- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/controller_test.go
This PR add a new type of migration object limiter for namespace. 
To implement this, the arbitrator of MigrationController traverses all objectLimiters and judge a pod through limiters enabled one by one. 
When a pod is judged by Workload limiter, first try to get its `ownerReference`, if there is no `ownerReference` of this pod, just skip it.
When a pod is judged by Namespace limiter, judge it by number of migrated pods in this namespace. 
The similar logic is implemented in `trackEvictedPod` function, too. 
fixes #2051
> koord-descheduler: add migration object limiter for namespace

- pkg/webhook/elasticquota/mutating/mutating_handler.go
- pkg/webhook/elasticquota/mutating/webhooks.go
- pkg/webhook/elasticquota/plugin_check_quota_meta_validate.go
- pkg/webhook/elasticquota/validating/validating_handler.go
In the current version of the koord-manager, the event handler of the elastic quota reconciling the quota topology cache is only instantiated by the elastic quota validating handler. It means the handler cannot work well when we enable the quota mutating but disable quota validating since the topology cache is invalid.
To fix this issue, we also try instantiating the event handler of the elastic quota in the quota mutating handler when it has not been instantiated.
> webhook: revise elasticquota mutating when validating disabled

- pkg/descheduler/apis/config/types_pluginargs.go
- pkg/descheduler/apis/config/v1alpha2/types_pluginargs.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.conversion.go
- pkg/descheduler/apis/config/v1alpha2/zz_generated.deepcopy.go
- pkg/descheduler/apis/config/validation/validation_pluginargs.go
- pkg/descheduler/apis/config/validation/validation_pluginargs_test.go
- pkg/descheduler/apis/config/zz_generated.deepcopy.go
- pkg/descheduler/controllers/migration/arbitrator/filter.go
- pkg/descheduler/controllers/migration/arbitrator/filter_test.go
If descheduler is first time used in some clusters, it might cause a bunch of Pods being evicted and re-scheduled through all namespaces, workloads and nodes. This might bring a big pressure to api-server.
This PR add a new config arg in MigrationController `MaxMigratingGlobally`  to limit the max number of pods being evicted in total. Default is set to 0, which means not enable this limitation.
> koord-descheduler: support max migrating globally limitation

- apis/extension/preemption.go
- apis/extension/preemption_test.go
- apis/extension/preemption_utils.go
- apis/extension/priority_utils.go
- apis/extension/priority_utils_test.go
- pkg/features/features.go
- pkg/features/scheduler_features.go
- pkg/util/transformer/pod_transformer.go
- pkg/util/transformer/pod_transformer_test.go
- pkg/util/transformer/transformers.go
Support features PriorityTransformer and PreemptionPolicyTransformer:
- PriorityTransformer: transform the priority value of the pod according to its priority class, allowing us to adapt the pods existing in the cluster that have not set priorities.
- PreemptionPolicyTransformer: transform the preemption policy of the pod according to a preemption label and the global default policy, allowing us to take over the pods existing in the cluster that may set the default preemptible policy. It helps when the cluster has many kinds of pods set the PreemptLowPriority by default priority classes but we want to enable the preemption only for specific pods.
> all: support priority and preemption policy transformer

- pkg/features/features.go
- pkg/features/scheduler_features.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
pod is deleted gracefully, it may be stuck long time. some user want ignore the pods when using elastic quota
> scheduler: elastic quota ignore terminating pod

- pkg/koordlet/koordlet.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/protocol/host_qos_context.go
- pkg/koordlet/runtimehooks/protocol/kubeqos_context.go
- pkg/koordlet/runtimehooks/protocol/pod_context.go
- pkg/koordlet/runtimehooks/protocol/pod_context_test.go
- pkg/koordlet/runtimehooks/protocol/protocol.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/runtimehooks/runtimehooks.go
- pkg/koordlet/runtimehooks/runtimehooks_test.go
Add record events for all the runtime hook
No
Add RecorderEvents in protocol, and kubectl describe pod.
> koordlet: add record events

- pkg/koordlet/resourceexecutor/cgroup.go
- pkg/koordlet/resourceexecutor/reader.go
- pkg/koordlet/runtimehooks/hooks/tc/rule.go
- koordlet: Fix the unsafe conversion in the tc runtime hook plugin.
Resolve code scanning alerts [#40](https://github.com/koordinator-sh/koordinator/security/code-scanning/40), [#41](https://github.com/koordinator-sh/koordinator/security/code-scanning/41),
> koordlet: fix unsafe conversion in net_cls

- pkg/scheduler/plugins/deviceshare/device_allocator.go
Currently, allocate by topology is time-consuming, we don't need it when deviceType isn't gpu.
> scheduler: assure only gpu will allocate by topology

- .licenseignore
- apis/extension/preemption.go
- apis/extension/preemption_test.go
- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1/types.go
- pkg/scheduler/apis/config/v1/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
- pkg/scheduler/apis/config/v1beta3/defaults.go
- pkg/scheduler/apis/config/v1beta3/types.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/frameworkext/reservation_info_test.go
- pkg/scheduler/plugins/reservation/cache_test.go
- pkg/scheduler/plugins/reservation/eventhandler_test.go
- pkg/scheduler/plugins/reservation/nominator.go
- pkg/scheduler/plugins/reservation/nominator_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/pod_eventhandler_test.go
- pkg/scheduler/plugins/reservation/preemption.go
- pkg/scheduler/plugins/reservation/preemption_test.go
- pkg/scheduler/plugins/reservation/scoring_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- Support the reservation preemption (Currently, only support a reservation preempt pods).
- Q: Why not adopt the DefaultPreemption?
- A: We want to support the case where a reservation preempts scheduled pods on a node. Perhaps, support the case where a pod preempts available reservations in the future. However, the DefaultPreemption relies on a real pod of the preemptor to [work](https://github.com/kubernetes/kubernetes/blob/release-1.28/pkg/scheduler/framework/preemption/preemption.go#L154). In this patch, we leverage the framework's preemption package and overwrite the SelectVictimsOnNode and PodLister of the DefaultPreemption to achieve the reservation preemption.
> scheduler: add reservation preemption

- go.mod
- go.sum
- pkg/descheduler/framework/plugins/kubernetes/adaptor/evictor.go
- pkg/descheduler/framework/plugins/kubernetes/adaptor/framework.go
- pkg/descheduler/framework/plugins/kubernetes/defaultevictor/evictor.go
- pkg/descheduler/framework/plugins/kubernetes/plugin.go
- pkg/descheduler/framework/plugins/kubernetes/plugin_test.go
Koordinator has update k8s version to 1.28.7 and koord-descheduler was adapted to Kubernetes Descheduler v0.26.0 which relies on k8s version 1.26.0.
This PR updates the k8s descheduler version to 0.28.0. In this version the k8s descheduler relies on k8s version 1.28.0, fixes some bugs and add more args in descheduler plugins.
> koord-descheduler: update k8s descheduler to 0.28.0

- apis/extension/reservation.go
- apis/extension/reservation_test.go
- apis/scheduling/v1alpha1/reservation_types.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/deviceshare/reservation_test.go
- pkg/scheduler/plugins/deviceshare/topology_hint.go
- pkg/scheduler/plugins/nodenumaresource/node_allocation.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/preempt.go
- pkg/scheduler/plugins/nodenumaresource/preempt_test.go
- pkg/scheduler/plugins/nodenumaresource/reservation.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
- pkg/scheduler/plugins/nodenumaresource/topology_hint.go
- pkg/scheduler/plugins/reservation/nominator.go
- pkg/scheduler/plugins/reservation/nominator_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/scoring.go
- pkg/scheduler/plugins/reservation/scoring_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_benchmark_test.go
- pkg/scheduler/plugins/reservation/transformer_test.go
- Support a pod-level API that ignores the reserved resources on nodes during the scheduling.
- Implement the preemption logic for the NodeNUMAResource plugin.
> scheduler: support reservation ignored and nodenumaresource preemption

- pkg/scheduler/frameworkext/topologymanager/manager.go
- pkg/scheduler/frameworkext/topologymanager/store.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/scoring.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/scoring.go
> scheduler: permit other plugin to set numaAffinity

- pkg/descheduler/evictions/evictions.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load.go
- pkg/descheduler/framework/plugins/loadaware/low_node_load_test.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
- pkg/descheduler/framework/plugins/loadaware/utilization_util_test.go
Currently we use `NodeFit` function to check if a pod can find some node that fits its affinity or tolerations. And it checks node's allocatable resources with pod's request.  
We also used the `totalAvailableUsages`to ensure the pod being re-scheduled won't cause the new node overutilized. It is the sum of remaining resources between node's usage and node's threshold, but it is the summary from all destination nodes. Anyway, we need to check node's available usage one by one. 
This PR add logic just after `NodeFit` to check if the target pod being evicted may cause a single destination node over utilized in LowNodeLoad plugin. 
fixes #2119
> koord-descheduler: LowNodeLoad check if evicted pod can cause new node over utilized

- pkg/features/features.go
- pkg/features/scheduler_features.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
proposal: #2179 
introduce a feature gate called ElasticQuotaImmediateIgnoreTerminatingPod, which would allow to bypass the deletion grace period and immediately ignore terminating pods.
> scheduler: elastic quota ignore terminating pod immediately

- pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go
Printed information does not meet expectations.
In the CPU normalization scenario, Allocatable is much greater than Capacity.
According to the logic here, the printed information should be Capacity.
> koordlet: fix wrong msg in calculateBESuppressCPU

- pkg/scheduler/plugins/deviceshare/device_allocator_test.go
- pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
- pkg/scheduler/plugins/deviceshare/devicehandler_gpu_test.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/reservation_test.go
- pkg/scheduler/plugins/deviceshare/topology_hint_test.go
> scheduler: support devices of the same node gpuMem not equal

- pkg/scheduler/plugins/nodenumaresource/preempt.go
- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
> scheduler: support pod preemption from numa awareless reservation

- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/schedulingphase/scheduling_phase.go
- pkg/scheduler/frameworkext/topologymanager/manager.go
- pkg/scheduler/frameworkext/topologymanager/store.go
当前每个节点的最佳 NUMA Affinity 再 Filter 阶段判断之后保存在 CycleState 中，这在通常调度场景下没有问题。但是在如下场景下会有问题，我们提供抢占者为 preemptor、被抢占者为 victim，两者都申请 NUMA 感知、绑核、8卡，并且亲和同一个 8 卡 节点。
1. Victim 调度成功
2. Preemptor 调度触发抢占，删除掉 Victim
3. Preemptor 开始调度，由于目标节点存在 NonimatingPod，所以会在 Filter 时：
a. 带 Nominating Filter：在 Filter 时候做一次 state.Clone，然后用 clone 的 state 去过 Filter，这时候 numa Affinity 保存到了 clone 的state 中
b. 不带 Nominating Filter：由于判断到 a 中并没有执行实际的 AddPod，所以这里逻辑认为 a Filter 结果有效，直接返回
上述流程就导致 NUMA Affinity 没有实际保存下来，倒是本来要申请双 NUMA 的节点只分到了单 NUMA 资源，看起来就像没有开启 NUMA 感知调度一样。
本 PR 将 affinityStore 的clone 方式改为浅拷贝，并：
1. 在调度阶段第一次带着抢占成功的 Pod 为当前 Pod 调度成功时时记录下来，调度流程中的后续阶段都复用该结果就好了
2. 抢占时忽略已经记录的结果，每次都重新判断是否满足 NUMA 对齐规则
> scheduler: optimize numa affinity store

- pkg/koordlet/qosmanager/plugins/resctrl/resctrl_reconcile.go
- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/hooks/hooks.go
- pkg/koordlet/runtimehooks/hooks/resctrl/resctrl.go
- pkg/koordlet/runtimehooks/hooks/resctrl/resctrl_test.go
- pkg/koordlet/runtimehooks/hooks/resctrl/rule.go
- pkg/koordlet/runtimehooks/hooks/resctrl/updater.go
- pkg/koordlet/runtimehooks/hooks/resctrl/updater_test.go
- pkg/koordlet/runtimehooks/nri/server.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/protocol/pod_context.go
- pkg/koordlet/runtimehooks/protocol/protocol.go
- pkg/koordlet/runtimehooks/proxyserver/server.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/runtimehooks/runtimehooks.go
- pkg/koordlet/util/resctrl/ctrl_mgr.go
- pkg/koordlet/util/resctrl/ctrl_mgr_test.go
- pkg/koordlet/util/resctrl/resctrl.go
- pkg/koordlet/util/resctrl/resctrl_test.go
- pkg/koordlet/util/system/resctrl.go
Add resctrl runtime hook for pod level. It's part of the https://github.com/koordinator-sh/koordinator/pull/1974.
https://github.com/koordinator-sh/koordinator/issues/1831
> koordlet: Add resctrl runtime hook for pod level

- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/plugins/elasticquota/plugin.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/scoring.go
- pkg/scheduler/plugins/reservation/scoring_test.go
Improve scheduler performance by several small changes.
> scheduler: optimize performance on transformer extension and Skip status

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/core_test.go
> scheduler: recover gang check in preFilter

- pkg/scheduler/frameworkext/eventhandlers/reservation_handler_test.go
- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/transformer.go
Reservation supports reserving "pods" resources. It helps when we want to limit the allocatable "pods" of the reservation owners.
> scheduler: support reserving pods resources

- apis/extension/device_share.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/schedulingphase/scheduling_phase.go
- pkg/scheduler/plugins/deviceshare/device_allocator.go
- pkg/scheduler/plugins/deviceshare/device_allocator_test.go
- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/utils.go
在 RDMA 和 GPU 联合分配中，RDMA 一般已经提前规划好满足 Pod 的诉求，只要能够保证 GPU 同 PCIE 下面有足够多的 VF 即可。这意味着调度器没必要再 Filter &Score 中分配 RDMA 资源，而只需要考虑 Device CR 是否已经规划好 RDMA 设备就行了，后者可以再Device CR 的事件处理函数中计算并缓存
> scheduler: support secondary device well planned

- pkg/scheduler/plugins/deviceshare/device_allocator.go
- pkg/scheduler/plugins/deviceshare/device_allocator_test.go
a node with two numaNode, two pcie per numaNode, two gpu and two rdma per pcie, user may want  two gpu and two rdma by following protocol
```
apiVersion: v1
kind: Pod
metadata:
name: hello-gpu
annotations:
scheduling.koordinator.sh/device-joint-allocate:|
{
"deviceTypes": [
"gpu",
"rdma"
]
}
spec:
containers:
- resources:
limits:
cpu: "16"
memory: 32Gi
nvidia.com/gpu: "2"
koordinator.sh/rdma: "200"
requests:
cpu: "16"
memory: 32Gi
nvidia.com/gpu: "2"
koordinator.sh/rdma: "200"
```
> scheduler: consider pod requests when gpu&RDMA joint allocate

- pkg/features/scheduler_features.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/plugins/coscheduling/coscheduling.go
- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/deviceshare/reservation_test.go
- pkg/scheduler/plugins/nodenumaresource/reservation.go
- pkg/scheduler/plugins/reservation/nominator.go
- pkg/scheduler/plugins/reservation/nominator_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/preemption.go
- pkg/scheduler/plugins/reservation/scoring.go
- pkg/scheduler/plugins/reservation/scoring_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_test.go
When reservations are widely used in the cluster, the resource restoration in the Reservation plugin can have a negligible overhead.
We added a feature called LazyReservationRestore, which improves scheduling performance by delaying the restoration after the PreFilter. When there is no need to restore resources for all nodes, e.g., if plugins give preFilterResult in the PreFilter phase, we can limit the reservation restoration to the necessary nodes.
> scheduler: optimize reservation perf with lazy restoring

- pkg/util/resource.go
- pkg/util/resource_test.go
Got an unexpected error when creating a new quota:
`webhook "velasticquota.koordinator.sh" denied the request: checkMinQuotaSum all brothers'' MinQuota > parent MinQuota`
childQuota's minResource: <cpu: 250, memory: 1000Gi>
parentQuota's minResource: <cpu: 99999999, memory: 39999996Gi>
I reproduced this error in unit test and found there's a potential issue when calling `Quantity#Value` in `resource.go#LessThanOrEqualCompletely`. `Quantity#Value` could overflow and the returned value should be verified for some risky scenarios. So I propose to use `Quantity#CmpInt64` to fix this issue.
NONE
UT
> util: fix incorrect comparison for resource.go#LessThanOrEqualCompletely

- pkg/scheduler/frameworkext/topologymanager/policy.go
- pkg/scheduler/frameworkext/topologymanager/policy_best_effort.go
- pkg/scheduler/frameworkext/topologymanager/policy_best_effort_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_none_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_restricted_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node.go
- pkg/scheduler/frameworkext/topologymanager/policy_single_numa_node_test.go
- pkg/scheduler/frameworkext/topologymanager/policy_test.go
- pkg/scheduler/plugins/deviceshare/plugin.go
1. BestEffort 策略下，当多种资源 merge 出的 NUMA 资源不足时，直接返回所有 NUMA Node 作为 Hint
2. DeviceShare 中，如果判断已经打开了 NUMA 感知调度，则后续 Filter 逻辑可以忽略
> scheduler: support besteffort policy

- apis/extension/device_share.go
- apis/extension/device_share_test.go
- pkg/scheduler/plugins/deviceshare/allocator_gpu.go
- pkg/scheduler/plugins/deviceshare/allocator_gpu_helper.go
- pkg/scheduler/plugins/deviceshare/allocator_gpu_test.go
在非 VM 情况下，gpu 不需要按照 Partition 分配，这种情况即使卡型匹配到了默认的 PartitionIndexer，需要根据 Node Or Device 上的 Label 来决定是否按照 Partition 分配
> gpu: setting default gpu partition policy

- pkg/koordlet/resourceexecutor/reader.go
- pkg/koordlet/resourceexecutor/reader_test.go
The CgroupReader interface under the resourceexecutor module is missing a method to read memory usage for cgroups. We need this method to obtain memory usage information for a specific cgroup.
> koordlet: add ReadMemoryUsage method to improve generality of cgroup reader interface

- pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
- pkg/slo-controller/noderesource/plugins/midresource/plugin.go
- pkg/slo-controller/noderesource/plugins/util/util.go
- pkg/slo-controller/noderesource/plugins/util/util_test.go
In order to better support mid resource in the future, we refactored the reporting code for oversale resources and extracted the public functions that mid resources and batch resources may use.
> koord-manager: refactor oversale resource calculate logic.

- pkg/util/sloconfig/nodeslo_config.go
- pkg/util/sloconfig/nodeslo_config_test.go
We've found a case that if we configure the resource qos config to `..."cgroupRoot":{"blkioQOS":{}}...`, koordlet would crash due to a NPE panic in [blkio reconcile](https://github.com/koordinator-sh/koordinator/blob/main/pkg/koordlet/qosmanager/plugins/blkio/blkio_reconcile.go#L166).
This PR add the previously missing defaulting to blkio qos to solve this issue.
> util: add defaulting to blkio qos to improve robustness

- pkg/webhook/pod/validating/evaluate_quota_test.go
- pkg/webhook/quotaevaluate/util.go
Currently admission will be set to max when the parsed value of it is zero, here including 3 situations:
(1) not configured.
(2) configured with no content.
(3) configured with specified-zero resources.
Situation (1) and (2) are suitable to use max since we better have a default limitation for pods. But for Situation (3), we have a usage scenario that new pod submissions should be pausing temporarily and keep running pods going, the most simplest approach is to set admission to zero without updating min/max (may be unable to recover it later for some verifications like checkMinQuotaSum). And I think it's reasonable to use configured admission even if it's zero.
If possible, we can change the condition that chooses to use max for admission, from "admission is zero" to "admission is empty", …
> webhook: Support setting quota admission to zero for special usage scenarios, such as temporarily pausing pod submissions.

- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/deviceshare/reservation.go
- pkg/scheduler/plugins/deviceshare/reservation_test.go
scheduler: Fix a bug for the DeviceShare plugin where the scheduling pod may allocate in-used devices when it allocates from a reservation and reservation-ignored pods also allocate the same devices.
> scheduler: fix deviceshare with reservation-ignored pods

- pkg/koordlet/metrics/host_application.go
- pkg/koordlet/metrics/internal_metrics.go
- pkg/koordlet/metrics/metrics_test.go
- pkg/koordlet/metricsadvisor/collectors/hostapplication/host_app_collector.go
To better monitor the resource usage of the host application, Prometheus metrics have been added.
> koordlet: export host application cpu and memory usage for prometheus

- pkg/scheduler/frameworkext/topologymanager/manager.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/scoring.go
scheduler:
- Support a pod with no matched resource to allocate reserved resources when it specifies a reservation affinity.
- Improve logs of the topology-aware scheduling for diagnosis.
It helps when a pod want to bind to a reservation even if it does not request any reserved resource.
e.g. A Batch pod can allocate to a reservation if there are sufficient resources from the node, even when batch resources are not reserved.
> scheduler: support allocating from reservation when no resource matched

- pkg/koordlet/prediction/prediction_test.go
- pkg/koordlet/statesinformer/api.go
- pkg/koordlet/statesinformer/impl/states_informer.go
- pkg/koordlet/statesinformer/impl/states_informer_test.go
- pkg/koordlet/statesinformer/mockstatesinformer/mock.go
add func GetNodeMetricSpec, so we can get nodeMetricSpec conveniently by statesInformer interface
add GetNodeMetricSpec in statesInformer interface
prepare for https://github.com/koordinator-sh/koordinator/pull/2273
> koordlet: add GetNodeMetricSpec in statesInformer interface

- apis/extension/device_share.go
- apis/extension/device_share_test.go
- docs/proposals/scheduling/20220629-fine-grained-device-scheduling.md
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
The RDMA device is mounted inside the container based on the scheduling assignment result.
The scheduling framework already supports joint allocation of Gpus and RDMA devices, but several semantics need to be tested in practice, including preference and samePCIE. In order to allow RDMA devices to access the container, we need to fix the lack of BDF addresses in the results assigned by the scheduling algorithm to RDMA devices
1. In the k8s cluster, prepare one or more servers that support rdma network adapters as cluster nodes. Install the new version of the koordlet component, koord-manager, and the revamped multus-cni on each node, and check the node status. The number of resources is displayed as the actual number of RDMA nics on the node.
2. Write a pod.YAML to apply for RDMA network …
> api: supply id for minor meaningless device

- pkg/koordlet/statesinformer/impl/callback_runner.go
- pkg/koordlet/statesinformer/impl/states_informer.go
clean up stateInformer.impl StateInformer interface
use api.StateInformer interface instead
> koordlet: remove useless stateInformer.impl StateInformer interface

- apis/slo/v1alpha1/pod.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor.go
- pkg/koordlet/runtimehooks/hooks/groupidentity/interceptor_test.go
> koordlet: support change pod CPUQOS by annotations

- pkg/koordlet/runtimehooks/config.go
- pkg/koordlet/runtimehooks/hooks/rdma/rdma.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
inject rdma  uverbs device into Container
> koordlet: rdma device inject

- pkg/slo-controller/noderesource/plugins/batchresource/plugin.go
- pkg/slo-controller/noderesource/plugins/batchresource/plugin_test.go
- pkg/slo-controller/noderesource/plugins/midresource/plugin.go
- pkg/slo-controller/noderesource/plugins/midresource/plugin_test.go
- pkg/slo-controller/noderesource/plugins/util/util.go
- pkg/slo-controller/noderesource/resource_calculator_test.go
…n calculate mid resource.
Just like batch resources, we should consider SafetyMargin, NodeReserved, and SystemUsed when calculating mid resources.
```
Allocatable[Mid]' := min(Reclaimable[Mid], NodeAllocatable * thresholdRatio) + Unallocated[Mid] * midUnallocatedRatio
Unallocated[Mid] = max(NodeCapacity - NodeSafetyMargin - SystemUsed - Allocated[Prod], 0)
```
ref node resource model:
https://github.com/koordinator-sh/koordinator/blob/main/docs/images/node-resource-model.png
> koord-manager: consider NodeReserved when calculate mid resource.

- pkg/koordlet/runtimehooks/reconciler/reconciler.go
Different conditions within the same reconciler correspond to different descriptions, similar to fn, but the current description has not been updated according to the condition; this PR fixes that issue.
> koordlet: fix reconciler description mismatch.

- pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin_test.go
- pkg/slo-controller/noderesource/plugins/rdmadevicereource/device_event_handler.go
- pkg/slo-controller/noderesource/plugins/rdmadevicereource/device_event_handler_test.go
- pkg/slo-controller/noderesource/plugins/rdmadevicereource/plugin.go
- pkg/slo-controller/noderesource/plugins/rdmadevicereource/plugin_test.go
- pkg/slo-controller/noderesource/plugins_profile.go
[koord-manager-rdma]
In order to implement the end-to-end scheme of the rdma device, it is necessary to add an rdma resource controller to update the status of node nodes in time, including Capacity and Allocatable. The koordinator.sh/rdma resources are mainly updated.
Fixed loss of functionality for rdma resource registration and update to nodes
1. In the k8s cluster, prepare one or more servers that support rdma network adapters as cluster nodes. Install the new version of the koordlet component on each node and install the new version of the koord-manager component. Check whether the number of rdma resources in a node is updated to the actual number of rdma nics on the node.
2. Uninstall one or more RDMA network cards of the node and restart the server. After the node is added to the …
> manager: sync rdma resource to node

- pkg/scheduler/plugins/nodenumaresource/resource_manager.go
> scheduler: add log for cpu/mem numaaware allocate

- pkg/koordlet/metricsadvisor/collectors/hostapplication/host_app_collector.go
- pkg/koordlet/metricsadvisor/collectors/hostapplication/host_app_collector_test.go
collect host application memory usage with page cache.
rely on https://github.com/koordinator-sh/koordinator/pull/2278
> koordlet: collect metric for host application memory usage with page cache

- pkg/slo-controller/noderesource/plugins/midresource/plugin.go
- pkg/slo-controller/noderesource/plugins/midresource/plugin_test.go
- pkg/slo-controller/noderesource/plugins/util/util.go
- pkg/slo-controller/noderesource/resource_calculator_test.go
When calculating *Allocatable[mid]* resources, due to possible oversold, *ProdReclaimableMetric* will be greater than *NodeAllocatable* * *thresholdRatio*, so the calculated *Allocatable[mid]* value accidentally includes the oversold part. 
In particular, when *thresholdRatio = 1*, *Allocatable[mid] = NodeAllocatable*, which is not the original intention of the koordinator resource model design.
I suggest taking the current free resources of this node into account when calculating Allocatable[mid], that is, *Allocatable[Mid]' := min(Reclaimable[Mid], NodeAllocatable * thresholdRatio, FreeResourceOnNode) + Unallocated[Mid] * midUnallocatedRatio*
> slo-controller: fix mid resource calculate formula

- apis/extension/device_share.go
- pkg/koordlet/runtimehooks/hooks/gpu/gpu.go
- pkg/koordlet/runtimehooks/hooks/gpu/gpu_test.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/protocol/protocol.go
- pkg/koordlet/util/system/config.go
- pkg/koordlet/util/system/config_test.go
> gpu: support strict gpu share with hami

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
> scheduler: refactor reset quota

- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/reservation/plugin.go
> scheduler: register pod delete event for resource plugin

- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/nodenumaresource/plugin.go
- pkg/scheduler/plugins/nodenumaresource/plugin_test.go
- pkg/scheduler/plugins/reservation/nominator.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
Koord-Scheduler: 
1. Revise the ReservationFilterPlugin interface to make it extensible and provide more accurate filtering results. Please see the section "Special notes" for the details.
2. Support node reservation API in a Reservation object.
3. Fix a bug about counting reservation's "pods" resources during the preemption.
Rename the ReservationFilterPlugin method `FilterReservation` to `FilterNominateReservation` since only the NominateReservation calls it during the PreScore or the Reserve phase.
Re-define the method `FilterReservation` that is invoked in the Filter phase:
```go
type ReservationFilterPlugin interface {
framework.Plugin
FilterReservation(ctx context.Context, cycleState *framework.CycleState, pod *corev1.Pod, reservationInfo *ReservationInfo, nodeInfo …
```
> scheduler: revise ReservationFilterPlugin and fix preempting pods resources

- pkg/scheduler/frameworkext/topologymanager/policy.go
- pkg/scheduler/plugins/deviceshare/topology_hint.go
- pkg/scheduler/plugins/deviceshare/topology_hint_test.go
> scheduler: make topology manager aware device preference

- pkg/scheduler/plugins/elasticquota/plugin_helper.go
> scheduler: fix quota check panic

- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/frameworkext/reservation_info_test.go
koord-scheduler: fix a bug where the reserved in a Reservation does not refresh for the Update event.
related to #2315.
> scheduler: fix reservation reserved updated

- pkg/scheduler/plugins/deviceshare/allocator_gpu_helper.go
- pkg/scheduler/plugins/deviceshare/allocator_gpu_helper_test.go
> scheduler: export GPUPartitionIndexOfNVIDIAHopper

- pkg/scheduler/frameworkext/scheduler_monitor.go
- pkg/scheduler/frameworkext/scheduler_monitor_test.go
scheduler: Fix a bug where the pod is leaked in the schedulerMonitor's cache if it is terminating and then dequeues.
> scheduler: fix monitor terminating pod

- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/plugins/deviceshare/device_cache.go
- pkg/scheduler/plugins/reservation/transformer.go
- pkg/scheduler/plugins/reservation/transformer_benchmark_test.go
Scheduler: Reduce overhead by changing unnecessary DeepCopy to shallow copy and pre-allocating memory for a heavy map copy.
> scheduler: some minor optimizations for reservation

- pkg/features/features.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/group_quota_manager_test.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator.go
- pkg/scheduler/plugins/elasticquota/core/runtime_quota_calculator_test.go
- pkg/webhook/elasticquota/quota_topology.go
- pkg/webhook/elasticquota/quota_topology_check.go
- pkg/webhook/elasticquota/quota_topology_test.go
Currently, the consistency check for resource types in elastic quota's add, delete and update is insufficient and too rigid. For example, maxResourceKey requires parent-child consistency, which can lead to the following problems:
1. There is no unified logic to check the various resource types of *min/max*, which can easily lead to inconsistencies
2. Unable to flexibly support changing resource types, especially when adding new resources, limited by the initial creation status
However, considering the original intention of quota design and current computing logic, it does not affect related calculations while supporting resource type checks(also already added more unitTest cases). Among them:
1. The setting intentions of *min* and *max* are different and the calculation logic is not …
> webhook: support elasticquota enable update resource key

- docs/proposals/koordlet/20241210-pod-resources-proxy.md
In order to be compatible with dcgm for GPU monitoring, adjust the adaptation of dcgm and GPU Hook NRI
fixes #2171
> docs: pod resources proxy

- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/runtimehooks/hooks/cpuset/rule_test.go
- pkg/koordlet/runtimehooks/protocol/container_context.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/runtimehooks/reconciler/reconciler_test.go
- pkg/koordlet/util/pod.go
- pkg/koordlet/util/pod_test.go
Set cpuset for init container in CPUSetAllocator.
https://github.com/koordinator-sh/koordinator/issues/2350
> koordlet: support init container for CPUSetAllocator

- pkg/koordlet/runtimehooks/hooks/cpuset/rule.go
- pkg/koordlet/runtimehooks/protocol/filters.go
- pkg/koordlet/runtimehooks/protocol/filters_test.go
- pkg/koordlet/runtimehooks/reconciler/reconciler.go
- pkg/koordlet/util/pod.go
skip reconcile containers in runtime hooks if match the ignore condition.
conditions are defined as ignore filters in independent files, which can be easily overwritten for extension.
filters can be defined as plugin level in future.
> koordlet: skip reconcile containers in runtime hooks for kata pods

- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/frameworkext/reservation_info_test.go
- pkg/scheduler/plugins/reservation/cache_test.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/scoring_test.go
scheduler: pre-calculate the available resources and remove useless processing to improve reservation filter performance.
> scheduler: pre-calculate reservation info for perf

- pkg/descheduler/framework/plugins/loadaware/utilization_util.go
https://github.com/koordinator-sh/koordinator/blob/bc78bd2034248aa143e90537536be08073fc3198/pkg/descheduler/framework/plugins/loadaware/utilization_util.go#L747
This will cause a panic when `podMetric` is nil here.
Added nil check and logging before calling podFitsAnyNodeWithThreshold.
<details><summary>panic log</summary>
<p>
```
E0415 14:02:12.302754       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 308 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x214daa0?, 0x3b96350})
/go/pkg/mod/k8s.io/apimachinery@v0.28.7/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00374d340?}) …
```
> koord-descheduler: add nil check for podMetric in NodeFit of loadaware plugin

- pkg/scheduler/plugins/reservation/eventhandler.go
- pkg/scheduler/plugins/reservation/eventhandler_test.go
- Fix a leakage issue for the reservation cache when a reservation is almost concurrently updated to Succeeded/Failed and deleted, causing by the inconsistent logic between the event handlers of the plugin and of the scheduler cache.
> scheduler: fix reservation cache leak when terminated and deleted

- apis/extension/elastic_quota.go
- pkg/webhook/elasticquota/quota_topology_check.go
- pkg/webhook/elasticquota/quota_topology_test.go
Adding an optional annotation `quota.scheduling.koordinator.sh/max-strict-check-resource-keys` for elastic quota that record resource keys that updates for quota spec should be checked max >= used in json format.
Example: `quota.scheduling.koordinator.sh/max-strict-check-resource-keys: '["cpu", "memory"]'`
NONE
> webhook: check quota that only allow max >= used for specific resources

- apis/extension/device_share.go
- pkg/scheduler/metrics/metrics.go
- pkg/scheduler/plugins/deviceshare/device_cache.go
In a production environment, sufficient VF resources are usually planned for the GPU. Under this condition, you can skip the resource check of the VF in the Filter stage and only do it in the Reserve stage.
> scheduler: optimize secondary device well planned

- pkg/descheduler/pod/pods.go
We should return the unmatched cases first,and leave the filter method for last, because it is computationally expensive.
> descheduler: return the unmatched cases first

- pkg/koordlet/statesinformer/impl/states_node.go
- pkg/koordlet/statesinformer/impl/states_nodemetric.go
- remove useless code and use generateQueryDuration() func in collectMetric() func
> chore(statesInformer):  remove useless code and use generateQueryDuration() func in collectMetric() func

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1/defaults.go
- pkg/scheduler/apis/config/v1/types.go
- pkg/scheduler/apis/config/v1/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
- pkg/scheduler/apis/config/v1beta3/defaults.go
- pkg/scheduler/apis/config/v1beta3/types.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
- pkg/scheduler/plugins/elasticquota/preempt.go
koord-scheduler
- The quota of pods that do not actively set through annotation will be recognized as the default quota. In some scenarios, many important pods are not scheduled by Koordinator, and their quotas are also recognized as default quota, this will cause the eviction operation to identify these important pods as victim pods, which is risky. We introduced a new argument `DisableDefaultQuotaPreemption` in ElasticQuota, when `DisableDefaultQuotaPreemption` is set to true, these pods can be avoided from being evicted.
unit tests passed.
> scheduler: add ElasticQuota arg to control preemption of default quota (#2413)

- pkg/features/scheduler_features.go
- pkg/scheduler/frameworkext/controllers.go
- pkg/scheduler/frameworkext/debug.go
- pkg/scheduler/frameworkext/framework_extender_factory.go
- Allow to disable Controller plugins for the multi-scheduler scenario.
> scheduler: allow to disable Controllers

- cmd/koordlet/options/options.go
- pkg/koordlet/extension/interface.go
- pkg/koordlet/koordlet.go
koordlet: support extension controllers
> koordlet: support extension controllers

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/hook_plugin_test.go
In #2415, pod-update hooks for elastic-quota were expected to be triggered when a pod changed regardless of whether used resources have changed, since there maybe some used-resource-regardless actions to be done in pod-update hooks.
But the action has been changed in #2456 :  when the used resources of the pod have not changed, pod-update hooks for elastic-quota won't be triggered.
This PR will move the GroupQuotaManager#runPodUpdateHooks before calculating the used resources to make sure the pod-update hooks must be triggered when a pod changed.
> scheduler: run pod-update hooks for elastic-quota regardless of whether used resources have changed

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/hook_plugin.go
- pkg/scheduler/plugins/elasticquota/core/hook_plugin_test.go
- pkg/scheduler/plugins/elasticquota/hook_plugin_test.go
- pkg/scheduler/plugins/elasticquota/quota_handler.go
There are 2 locations in quota_handler.go that need to be made compatible with hook plugins:
1) OnQuotaUpdate method: Add a GroupQuotaManager#IsQuotaUpdated call to determine whether the quota has been updated for hook plugins.
2) ReplaceQuotas method: Add a GroupQuotaManager#ResetQuotasForHookPlugins call to reset quotas during the initial phase for hook plugins.
> scheduler: Add hook plugins logic in ReplaceQuotas and OnQuotaUpdate methods of ElasticQuota plugin.

- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/loadaware/service.go
- pkg/scheduler/plugins/loadaware/service_test.go
Make the load-aware scheduling debuggable:
- Add a service for checking the podAssignCache.
- Add logs to print the calculation results.
> scheduler: make loadaware debuggable

- pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go
- pkg/scheduler/plugins/elasticquota/core/hook_plugin.go
- pkg/scheduler/plugins/elasticquota/core/hook_plugin_test.go
- pkg/scheduler/plugins/elasticquota/hook_plugin_test.go
Data race issues in UT report:
https://github.com/koordinator-sh/koordinator/actions/runs/15468364005/job/43545936919?pr=2468
Fixed:
1) hold readlock in GroupQuotaManager#IsQuotaUpdated to make sure HookPlugin#IsQuotaUpdated be called with lock as required.
2) Refactor MockHookPlugin to resolve data race issues when executing unit tests.
> scheduler: fix data race issues in GroupQuotaManager#IsQuotaUpdated and MockHookPlugin

- apis/extension/cluster_colocation_profile.go
- pkg/controller/colocationprofile/colocationprofile_controller.go
- pkg/controller/colocationprofile/colocationprofile_controller_test.go
- pkg/controller/colocationprofile/colocationprofile_util_test.go
koord-manager:
- Controller reconciles the ClusterColocationProfile only when it sets enabled.
> manager: reconcile colocation-profile if enabled

- apis/extension/device_share.go
- pkg/features/features.go
- pkg/koordlet/statesinformer/impl/states_device_linux.go
- pkg/koordlet/statesinformer/impl/states_device_linux_test.go
- pkg/scheduler/plugins/deviceshare/allocator_gpu_helper.go
- pkg/scheduler/plugins/deviceshare/device_plugin_adapter.go
- pkg/scheduler/plugins/deviceshare/device_plugin_adapter_test.go
- pkg/scheduler/plugins/deviceshare/devicehandler_gpu.go
- pkg/scheduler/plugins/deviceshare/devicehandler_gpu_test.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
- pkg/scheduler/plugins/deviceshare/utils.go
- pkg/scheduler/plugins/deviceshare/utils_test.go
- pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin.go
- pkg/slo-controller/noderesource/plugins/gpudeviceresource/plugin_test.go
- pkg/slo-controller/noderesource/plugins/gpudeviceresource/utils.go
This is the first time that we introduce a heterogeneous GPU (other than NVIDIA) to fine-grained device scheduling, so this PR also contains some fundamental works which would help us integrate other heterogeneous devices easier in the future.
Let's first explain the fundamental works:
As we all know, there're three major phases in the lifecycle of fine-grained device scheduling: **reporting, scheduling, allocating**.
**For reporting**, currently koordlet only supports reporting NVIDIA GPUs, but #2423 is working on heterogeneous GPU reporting including Huawei NPU, so **this PR only introduces the missing vendor label to device/node (which is necessary for the following works) and leaves the rest works to the implementation of #2423**.
**For scheduling**, current device share scheduling is …
> scheduler: fine-grained device scheduling support Huawei Ascend NPU (full card)

- pkg/descheduler/controllers/migration/controller.go
- pkg/descheduler/controllers/migration/evict.go
koord-descheduler uses limiterMap to manage object limiters. If multiple profiles are configured, all MigrationControllers in all profiles can evict pods from all PodMigrationJobs. But a workload limiter may be recorded inside one limiterMap of a profile, but evicted by another limiterMap. This may cause object limiter not working. 
This PR add a UUID to MigrationController and an Annotation to PodMigrationJob. Each time a PodMigrationJob is created by MigrationController, its UUID will be recorded into this Annotation. Each time a MigrationController from a profile reconciling a PodMigrationJob, it decide if to drop this PodMigraionJob by this annotation.
> koord-descheduler: fix descheduler object limiter with multiple profiles

- pkg/scheduler/plugins/defaultprebind/plugin_test.go
- pkg/util/utils.go
- pkg/util/utils_test.go
- Fix a bug where the async PreBind may Patch to an unexpected pod with the same name but a different UID.
This problem occurs when two pods with the same namespace and name are scheduled in nearly the same interval. Due to the binding cycles being executed out of order, the first pod to PreBind may not exist so it may Patch another pod.
We use the approach that Patch objects with their UIDs, so the Patch request will ensure that the object UID is unchanged since this field is immutable.
> scheduler: fix PreBind Patch for pods with same name but different uid

- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_factory_test.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- Check SchedulerName of the scheduling pod/reservation before entering the PreBind phase.
Due to the koord-scheduler allows the pod to change its schedulerName by the label `scheduling.koordinator.sh/scheduler-name`, there can be some pod who has a matched schedulerName in the scheduling cycle but changes its schedulerName during the Permit waiting of the binding cycle. So we add a double-check before the PreBind to filter out the scheduler unmatched pod.
> scheduler: reject schedulerName unmatched binding

- pkg/koordlet/statesinformer/impl/states_nodemetric.go
- pkg/koordlet/statesinformer/impl/states_nodemetric_test.go
In the documentation, AggregationType has "avg" as an optional value.
https://github.com/koordinator-sh/website/blob/f4a33b7ecc776ed74e7deeffdfd9fefc9fd9b88a/docs/user-manuals/load-aware-scheduling.md?plain=1#L120-L128
But koordlet does not collect avg data. This PR adds the collection of avg aggregation type.
> koordlet: fix avg not being collected in AggregatedUsage

- pkg/quota-controller/profile/profile_controller.go
- pkg/slo-controller/config/colocation_cm_event_handler.go
- pkg/slo-controller/noderesource/plugins/cpunormalization/configmap_event_handler.go
- pkg/slo-controller/noderesource/plugins/resourceamplification/configmap_event_handler.go
- pkg/slo-controller/nodeslo/nodeslo_cm_event_handler.go
- if evicting pod successfully, we should use `Normal` type
```go
// Valid values for event types (new types could be added in future)
const (
// Information only and will not cause any problems
EventTypeNormal string = "Normal"
// These events are to warn that something might go wrong
EventTypeWarning string = "Warning"
)
```
> chore: fix wrong event type

- pkg/koordlet/util/storageinfo.go
… volumes use lvm command simultaneously.
fix: GetLocalStorageInfo maybe hang, such as other component creating volumes use lvm command simultaneously.
NONE
If creating an lvm volume takes a lot of time and executing other lvm commands at the same time, the command may hang.
> fix: GetLocalStorageInfo maybe hang

- pkg/scheduler/plugins/coscheduling/controller/podgroup.go
- pkg/scheduler/plugins/coscheduling/controller/podgroup_test.go
Currently, PodGroup OccupiedBy field is not set correctly.
- set PodGroup's OccupiedBy field  correctly
> scheduler: set PodGroup's OccupiedBy field  correctly

- pkg/scheduler/plugins/deviceshare/device_plugin_adapter.go
- pkg/scheduler/plugins/deviceshare/device_plugin_adapter_test.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
We've met cases that the built-in `NVIDIA_VISIBLE_DEVICES=all` env of CUDA images invalidates the one injected by device plugin. Under this case users need to explicitly declare this env in pod template to override the one of pod image. Since the value of the env is decided by scheduler, this PR introduces a `scheduling.koordinator.sh/gpu-minors` annotation to device plugin adapter so that users can use this as a field ref of the env, like this:
```yaml
- name: NVIDIA_VISIBLE_DEVICES
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: metadata.annotations['scheduling.koordinator.sh/gpu-minors']
```
> scheduler: introduce gpu minors annotation to device plugin adapter

- pkg/scheduler/plugins/coscheduling/core/core.go
- pkg/scheduler/plugins/coscheduling/core/gang.go
- pkg/scheduler/plugins/coscheduling/core/gang_context.go
- pkg/scheduler/plugins/coscheduling/core/ganggroup.go
1. 一个 GangGroup 还未经过调度时，让 GangGroup 可调度的事件由所有 Member Pod 接收，我们会在所有可调度的 Member Pod 中选一个代表 Pod 进入 ActiveQ 或者 BackoffQ
2. 一个 GangGroup 调度周期开始后，我们应该将代表 Pod 删除，因为没有人在 ActiveQ 或者 BackoffQ 中排队了，但是
a. 应该避免后续 Pod 进入 ActiveQ 或者 BackoffQ，以避免删除它时间开销很大
b. 如果有已经尝试或者正在尝试的 Pod 的 PreEnqueue 事件，应该放行，因为这种 Enqueue 可能会让 Gang 重新调度成功
> scheduler: revise preEnqueue RepresentativePod

- pkg/descheduler/evictions/eviction_limiter.go
- pkg/descheduler/evictions/eviction_limiter_test.go
- pkg/descheduler/evictions/evictions.go
- use RWMutex instead of use Mutex
- add some unit test
> koord-descheduler: use RWMutex instead of use Mutex

- apis/extension/load_aware.go
- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1/types.go
- pkg/scheduler/apis/config/v1/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1/zz_generated.deepcopy.go
- pkg/scheduler/apis/config/v1beta3/types.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.deepcopy.go
- pkg/scheduler/apis/config/zz_generated.deepcopy.go
- pkg/scheduler/plugins/loadaware/estimator/default_estimator.go
- pkg/scheduler/plugins/loadaware/estimator/default_estimator_test.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/loadaware/load_aware_test.go
- pkg/scheduler/plugins/loadaware/pod_assign_cache.go
- pkg/scheduler/plugins/loadaware/pod_assign_cache_test.go
- pkg/scheduler/plugins/loadaware/service_test.go
For some workload, the process has to loading configuration and data in bootstraping for a while before it executes operators that consume a lot of cpu and memory.
The solution is to add args and pod annotations that can force loadaware to use estimated usage in the duration after the pod is scheduled or initialized (all init containers are executed successfully)
LoadAwareSchedulingArgs
- `forceEstimationSecondsAfterPodScheduled` default force estimated duration after scheduled, < 0 means disabled by default
- `forceEstimationSecondsAfterInitialized` default force estimated duration after initialized,  < 0 means disabled by default
- `allowCustomizeEstimationFromMetadata` whether plugin allow to customize pod estimation with its annotations
pod metadata.annotations
- …
> scheduler: loadaware support force estimated duration and other improvements

- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_factory.go
- pkg/scheduler/frameworkext/interface.go
- pkg/scheduler/plugins/deviceshare/plugin.go
Fix a bug when the feature ResizePod is enabled, the scheduler may miss the Unreserve when it fails to AssumePod.
> scheduler: fix missing Unreserve when ResizePod=true

- pkg/features/features.go
- pkg/features/scheduler_features.go
- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
This PR moves `DevicePluginAdaption` from common feature gates (utilfeature.DefaultMutableFeatureGate) to scheduler feature gates (k8sfeature.DefaultMutableFeatureGate). The former one cannot be recognized in scheduler and will crash the scheduler when this feature gate is set.
> scheduler: move DevicePluginAdaption to correct feature gates

- pkg/features/scheduler_features.go
- pkg/scheduler/plugins/reservation/plugin.go
- pkg/scheduler/plugins/reservation/plugin_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- Add the feature-gate SkipReservationFitsNode to improve performance when the Reservation's fitsNode duplicates the Filter of the NodeResourceFit plugin.
- Revise some minor issues.
> scheduler: Reservation skips fitsNode to deduplicate with NodeResourceFit

- apis/extension/reservation.go
- apis/extension/reservation_test.go
- pkg/features/scheduler_features.go
- pkg/scheduler/plugins/reservation/controller/controller.go
- pkg/scheduler/plugins/reservation/controller/controller_test.go
- pkg/scheduler/plugins/reservation/controller/garbage_collection_test.go
- pkg/scheduler/plugins/reservation/controller/node_eventhandler.go
- pkg/scheduler/plugins/reservation/controller/pod_eventhandler.go
- pkg/scheduler/plugins/reservation/controller/reservation_eventhandler.go
- pkg/scheduler/plugins/reservation/plugin.go
koord-scheduler
- The reservation controller supports cleaning the reservation-allocated annotation of owner pods when the reservation is deleted. Use a feature-gate CleanExpiredReservationAllocated to enable this mechanism. Thus, the reservation plugin can filter out the pods who is still allocating an alive reservation.
Part of #2150.
> scheduler: clean expired ReservationAllocated for pods when reservation deleted

- pkg/scheduler/plugins/deviceshare/plugin.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
During scheduling, it must consider whether hami-core is installed on the nodes.
Note: When installing hami-core, you must set the node affinity label to koordinator.sh/gpu-isolation-provider=HAMi-core.
fix: https://github.com/koordinator-sh/koordinator/issues/2548
> scheduler: during scheduling, it must consider whether hami-core is installed on the nodes

- pkg/koordlet/statesinformer/api.go
Unified prefix for registertype enumeration values, fix RegisterNodeMetadata to RegisterTypeNodeMetadata
> chore: fix typo for RegisterTypeNodeMetadata

- pkg/webhook/elasticquota/quota_topology_check.go
- pkg/webhook/elasticquota/quota_topology_test.go
Currently, webhook reject elasticquotas' mutation with go struct %v printf when min resource value exceeds max. It is hard to read.
```
resourceKey memory of quota e2e-test min :map[cpu:{{1 0} {<nil>} 1 DecimalSI} memory:{{4294967296 0} {<nil>} 4Gi BinarySI}] > max,map[cpu:{{1 0} {<nil>} 1 DecimalSI} memory:{{4 0} {<nil>} 4 DecimalSI}]
```
> webhook: fix elasticquota validation error for min > max

- pkg/scheduler/frameworkext/reservation_info.go
- pkg/scheduler/frameworkext/reservation_info_test.go
- pkg/scheduler/plugins/reservation/cache_test.go
- pkg/scheduler/plugins/reservation/scoring_test.go
- pkg/scheduler/plugins/reservation/transformer.go
- Reservation: Pre-calculate the unmatched allocated resources in ReservationInfo to improve performance.
> scheduler: preprocess unmatch reservation's allocated

- pkg/koordlet/statesinformer/impl/states_device_linux.go
- pkg/koordlet/statesinformer/impl/states_device_linux_test.go
- fix typo and add memory-ratio resource for buildXPUDevice()
- NONE
> koordlet: fix typo and add memory-ratio resource for buildXPUDevice()

- pkg/koordlet/statesinformer/impl/states_node.go
- pkg/koordlet/statesinformer/impl/states_node_test.go
在携程的使用过程中,发现 koordlet 会随机启动失败，发现原因是 koordlet  corev1.Node 数据在 cache 中状态维护方式有缺陷造成的，此 PR 修复了这个问题。
无
单元测试构造了对应场景，让 event handler 执行慢一些就会稳定复现
> koordlet: fix koordlet panic randomly,caused by node info not ready

- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1/defaults.go
- pkg/scheduler/apis/config/v1/types.go
- pkg/scheduler/apis/config/v1/zz_generated.conversion.go
- pkg/scheduler/apis/config/v1beta3/defaults.go
- pkg/scheduler/apis/config/v1beta3/types.go
- pkg/scheduler/apis/config/v1beta3/zz_generated.conversion.go
- pkg/scheduler/apis/config/validation/validation_pluginargs.go
- pkg/scheduler/plugins/loadaware/load_aware.go
- pkg/scheduler/plugins/loadaware/load_aware_test.go
Add a new argument `dominantResourceWeight` in load aware scheduling plugin, which is a integer >= 0 and <= 100. When dominantResourceWeight is not zero, it is used as the weight for dominant resource's score on node.
The node's dominant resource is defined as the most used resource on node:
> dominant resource score = min(allocatable - usedOfExistingPods - estimatedOfIncomingPod) / allocatable)
When dominantResourceWeight is set non zero, plugin will not use default resource weight list.
fixes #2596
> scheduler: loadaware support dominantResourceWeight

- apis/extension/device_share.go
- config/manager/koordlet.yaml
- pkg/features/koordlet_features.go
- pkg/koordlet/runtimehooks/hooks/gpu/gpu.go
- pkg/koordlet/runtimehooks/hooks/gpu/gpu_test.go
- pkg/scheduler/frameworkext/schedule_diagnosis.go
- pkg/scheduler/frameworkext/schedule_diagnosis_test.go
- pkg/scheduler/plugins/deviceshare/device_plugin_adapter.go
- pkg/scheduler/plugins/deviceshare/device_plugin_adapter_test.go
- pkg/scheduler/plugins/deviceshare/plugin_test.go
Provides vGPU allocation and utilization metrics.
This only enables the configuration for hami-core to correctly export vGPU allocation and utilization to the node's /usr/local/vgpu directory. The vGPUMonitor component from hami-device-plugin needs to be integrated into the hami-core pod. vGPUMonitor will convert vGPU allocation and utilization into metrics. Detailed configuration will be documented.
doc：[Integrate the vGPUMonitor provided by HAMi into hami-core-distribute](https://github.com/koordinator-sh/website/pull/228)
fix: https://github.com/koordinator-sh/koordinator/issues/2560
> all: provides vGPU allocation and utilization metrics

- pkg/koordlet/statesinformer/impl/states_device_linux.go
Partition annotations should only exist if the device information includes p2p links.
None
> koordlet: fix partition in buildXPUDeviceAnnotations()

- pkg/features/scheduler_features.go
- pkg/scheduler/frameworkext/eventhandlers/event_handler.go
- pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go
- pkg/scheduler/frameworkext/framework_extender.go
- pkg/scheduler/frameworkext/framework_extender_test.go
- pkg/scheduler/frameworkext/interface.go
- Add a feature-gate `DynamicSchedulerCheck` to control whether to verify the scheduler name during the scheduling runtime. The verification is necessary with the schedulerName transformer, and in other cases, we can disable it if needed. 
- Add the scheduling extension point `Allocate`, which tries to allocate fine-grained resources without reserving the scheduler cache. It helps when we just want to filter GPU allocation against a node without changing the plugin cache (which the Reserve plugin does).
> scheduler: enhance framework extender for multi-scheduler
